### ISSUE TITLE
Conversion of WindSpeed

### ISSUE THREAD

**Issue by Pred8or** [steepleian/weewx-Weather34#1]
Hello Ian,
thanks for your efforts and a great WeeWX skin. 
I still have an issue with the the Windspeed. Maybe you can take a look. Thanks.

![Bildschirmfoto 2020-02-03 um 15 29 49](https://user-images.githubusercontent.com/5671328/73661365-3c5f2e00-469a-11ea-883f-c3f443ae8962.jpg)
![Bildschirmfoto 2020-02-03 um 15 29 24](https://user-images.githubusercontent.com/5671328/73661367-3c5f2e00-469a-11ea-9566-7494ba300db0.jpg)
![Bildschirmfoto 2020-02-03 um 15 28 45](https://user-images.githubusercontent.com/5671328/73661368-3c5f2e00-469a-11ea-8146-692e1bbd78ba.jpg)

**Comment by steepleian** [comment]
Can you check the version you are running

**Comment by steepleian** [comment]
Also, if you are on the latest version check that your weewx.conf file has
been updated correctly. Towards the bottom you will see the stanza with the
settings for w34realtime.txt. The units must be set to METRICWX as the wind
speed conversion calculations are based on wind units of m/s

Your main WeeWX skin, any other skin and WeeWX database will not be
affected in any way.

**Comment by Pred8or** [comment]
I am running the current version (WX-UB40-IHVN-0.9.1). I forgot to change to METRICWX. Changed that now, but did not change anything. Maybe it needs some time to update. I will check later. Thank you!
`##############################################################################

# Options for extension 'Weather34'
[Weather34RealTime]
    binding = loop
    exclude_fields = rain
    filename = /var/www/html/weewx/w34realtime.txt
    unit_system = METRICWX
    cache_stale_time = 900
    cache_directory = /tmp

##############################################################################

# Options for extension 'Weather34'
[Weather34WebServices]
    filename = /var/www/html/weewx/weather34/settings1.php
`
