### ISSUE TITLE
Fresh install - a few issues

### ISSUE THREAD

**Issue by m90att** [steepleian/weewx-Weather34#1]
Hello again!

I've been forced to factory reset my weather station so I've set everything up fresh.  I'm seeing issues again and I cannot find emails or past resolved issues on github regarding their resolution to refer to.

From what I can see on the w34 page it appears:

Forecasts are not working
Weather station readings show time of 00:00:00
Temperature readings are wildly incorrect

![image](https://user-images.githubusercontent.com/56609577/105628000-12b29000-5e32-11eb-9e29-2055fee1bbb8.png)

I've attached various files in zips

Many thanks, Matt

**Comment by m90att** [comment]
[syslog.zip](https://github.com/steepleian/weewx-Weather34/files/5862010/syslog.zip)

**Comment by m90att** [comment]
[skin.zip](https://github.com/steepleian/weewx-Weather34/files/5862012/skin.zip)

**Comment by m90att** [comment]
[wee_debug.zip](https://github.com/steepleian/weewx-Weather34/files/5862013/wee_debug.zip)

**Comment by m90att** [comment]
The seasons report is working ok
![image](https://user-images.githubusercontent.com/56609577/105629309-28c44e80-5e3a-11eb-9830-b71f663539e1.png)
W34 current, for comparison
![image](https://user-images.githubusercontent.com/56609577/105629315-34b01080-5e3a-11eb-94d5-909384206f8d.png)

**Comment by balloonhotair** [comment]
Hi,
First your  process_services = weewx.engine.StdConvert, weewx.engine.StdCalibrate, weewx.engine.StdQC, weewx.wxservices.StdWXCalculate
does not have user.weather34.Weather34RealTime 
Not sure how you can do an install and not have that happen let have all the other template entries.  For now add the service and restart weewx.

**Comment by m90att** [comment]
Thank you.  I followed the installation to the letter so it does seem strange.  Adding that string appears to have worked. 
![image](https://user-images.githubusercontent.com/56609577/105634847-ef024080-5e57-11eb-89d2-39526add8310.png)


I am seeing a few w34 errors in the log, I saw these a couple of times and have watched the log for a few more cycles and not seen them, are they ok?

```
Jan 24 15:17:13 weatherpi weewx[20195] ERROR user.weather34: Failed getting web                                                                                                          service data. URL: http:///weewx/weather34/eualert.php?country=UK&region=UK001 H                                                                                                         eader: {'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US)                                                                                                          AppleWebKit/534.3 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/534.3'}, Error                                                                                                         : <urlopen error no host given>
Jan 24 15:17:53 weatherpi weewx[20195] ERROR user.weather34: [Errno 2] No such file or directory: '/tmp/weather34/RetainedLoopValues.txt'
```
Thanks for your help

**Comment by m90att** [comment]
...the first log entry above should read

```
Jan 24 15:17:11 weatherpi weewx[20195] ERROR user.weather34: Error Invalid Webservice Data: None, {'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/534.3'}
Jan 24 15:17:13 weatherpi weewx[20195] ERROR user.weather34: Failed getting web service data. URL: http:///weewx/weather34/eualert.php?country=UK&region=UK001 Header: {'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/534.3'}, Error: <urlopen error no host given>

```

**Comment by steepleian** [comment]
Matt,
I am afraid you will have to disable your EUAlert web service. UK has been removed from Meteoalarm, it has not worked since the 14 January. Unfortunately Brexit is to blame. Not sure why that is the case as Norway, Switzerland bizarrley Israel are getting a service.

**Comment by balloonhotair** [comment]
Also need to remove your eq service since that service has gone MIA

**Comment by balloonhotair** [comment]
Also the install config files did not have overwrite set to True that is why you had the issue with the missing service. That has been updated in the repository

**Comment by balloonhotair** [comment]
On this 
Jan 24 15:17:53 weatherpi weewx[20195] ERROR user.weather34: [Errno 2] No such file or directory: '/tmp/weather34/RetainedLoopValues.txt'

Does the directory /tmp/weather34 exists?

**Comment by m90att** [comment]
It does exist

**Comment by balloonhotair** [comment]
Does the file RetainedLoopValues.txt exists in /tmp/weather34 and if so is it updating?

**Comment by m90att** [comment]
Yes and yes

**Comment by m90att** [comment]
Ok, makes sense.  Thank you for your help.
