### ISSUE TITLE
AQI quality vs Purpleair, mutual exclusive?

### ISSUE THREAD

**Issue by europacafe** [steepleian/weewx-Weather34#1]
Issues: Purpleair = yes + purpleair station id, AQI token filled in--->aqi.txt will not be produced-->AQI Quality section = offline, Purpleair has values
But if Purpleair=no, AQI token filled in--->aqi.txt generated in jsondata folder, but AQI Quality section still = offline (it's supposed to be online with corresponding air quality icon), no Purpleair value as expected. By checking the aqi.txt content, it has error:
{"status":"error","data":"Invalid geo position - Can not parse ''.13.717268.','.100.590727.''"}

![latlong](https://user-images.githubusercontent.com/51871976/78342155-0c150c80-75c3-11ea-83ac-b0e5bb93af82.png)

**Comment by steepleian** [comment]
Was this working correctly for you in the previous version? There have been no changes made to this section in this new release

**Comment by europacafe** [comment]
I always has this issue.

After posting the above issue, I remove all the weather34 components and had a fresh installation by following your latest instruction (packaged method, as I install weewx by debian method). Latest status, aqi.txt has correct data now, but the Air Quality section still shows as offline and no correct display.
The other issue came up. The webcam section, it no long displays my jpg photo; however, when I press for bigger photo, it displays fine.
![weather34](https://user-images.githubusercontent.com/51871976/78419941-e21c2280-7674-11ea-86ba-bcaf01d3c814.png)

**Comment by europacafe** [comment]
**update**: It is strange. When I switch the position of webcam and air quality. The air quality panel works!. Then I switched back, it is now working properly now. But the webcam image still no display.

**Comment by steepleian** [comment]
Hi,

That is very strange!

I would like to try and simulate your situation on my test server. As I do
not have a Purpleair monitor or a webcam could you please send me your
aqi.txt file and an image file from your webcam. (I do have another type of
particle monitor but the output is different to the Purpleair version).

Thank you
Ian

**Comment by europacafe** [comment]
You don't need to have the purpleair equipment, I don't have mine; but anyone can freely use other station data as long as you know its station id. I use purpleair id 42031. I attach my webcam snapshot for your test....thanks
![europacafe](https://user-images.githubusercontent.com/51871976/78422241-0fbe9700-7688-11ea-8997-f53fa7bed589.jpg)

**Comment by steepleian** [comment]
Fixed with commit 43f7309b389e96e217500e9316157c93bb90b754

**Comment by europacafe** [comment]
Thanks. It's working now.
