### ISSUE TITLE
Links to Documentation/Guides Broken

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#1]
In the installation guide all links to any url starting with https://claydonsweather.org.uk/weewx/ are broken.
At least, from my location, all get a 404 error.
Example URLs that 404:
https://claydonsweather.org.uk/weewx/docs/
https://claydonsweather.org.uk/weewx/docs2

**Comment by steepleian** [comment]
Hi Gary,
Sorry my error. Forgot to remove them. It is a hangover from when WeeWX 4
was in beta testing. You can find those docs now here: -
http://weewx.com/docs.html

I will update the repos this evening.

Thanks,
Ian

**Comment by steepleian** [comment]
Corrected

**Comment by gary-hammer** [comment]
There is still a link to your site for docs that goes 404.

Please familiarise yourself with the location of your WeeWX system files in http://weewx.com/docs/ including your bin/user folder, skins folder and weewx.conf file. If you are unsure where to find these, please refer to the installation processes here: - https://claydonsweather.org.uk/weewx/docs/ which shows various WeeWX installation scenarios.
