### ISSUE TITLE
Weewx Weather34 Skin

### ISSUE THREAD

**Issue by Jmknet** [steepleian/weewx-Weather34#1]
Hello!

Have some odd results that stop me using the skin.

Attache file for debugging and hopfully some answer/help

Regards

Peter
[Weather34.txt](https://github.com/steepleian/weewx-Weather34/files/4990745/Weather34.txt)

**Comment by steepleian** [comment]
Hello Peter,

You don't actually say what your problem is. Do you have a website which us public facing?

Ian

**Comment by Jmknet** [comment]
Hi!
I going to change my current windows server to publish the weather and also
have tellstick server and other web pages to the Raspberry.
Have had my own domain for awhile "jokkmokk.net" at home.

The problem is that weewx works fine but not the weather34 skin, in the
file I sent you can see that its get some error in a script that should
update the files for the skin.
I have tried to search where it goes wrong where it search for "sun" in the
calendar and even tag out for Dark ... because the close down shortly so I
not get error from that either.

Hopefully its explain little more of the problem.

I really like the set up other wise its nice layout just in my taste.

Regards

Peter

Den tis 28 juli 2020 kl 21:53 skrev Ian Millard <notifications@github.com>:

**Comment by steepleian** [comment]
Peter,

It looks like you do not have PyePhem installed. The archivedata.php.tmpl
file is searching for extended data that PyePhem generates. As it cannot
find it, archivedata.php fails.

Please look closely at the installation instructions which details how to
install PyePhem.

Ian

**Comment by Jmknet** [comment]
Hi!

Ohh, check that directly after work, I did think I followed the install
instructions but I must have missed it or something went wrong.

I have gone true everything so many times, just get Tellstick and weewx
working I reinstall from scratch 4 times.

Lyckley its goes fast with a SSD disk and the new PI 4 8Gb :-)

Best regards

Peter


Den ons 29 juli 2020 08:17Ian Millard <notifications@github.com> skrev:

> Peter,
>
> It looks like you do not have PyePhem installed. The archivedata.php.tmpl
> file is searching for extended data that PyePhem generates. As it cannot
> find it, archivedata.php fails.
>
> Please look closely at the installation instructions which details how to
> install PyePhem.
>
> Ian
>

**Comment by Jmknet** [comment]
Hi!
Have Pyephem installed:
Requirement already satisfied: pyephem in
/usr/local/lib/python3.7/dist-packages (3.7.7.0)
Requirement already satisfied: ephem==3.7.7.0 in
/usr/local/lib/python3.7/dist-packages (from pyephem) (3.7.7.0)

Still get this:
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.restx: StationRegistry:
Registration not requested.
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.restx: Wunderground-PWS:
Data for station IBDJOKKM2 will be posted
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.restx: PWSweather:
Posting not enabled.
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.restx: CWOP: Posting not
enabled.
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.restx: WOW: Posting not
enabled.
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.restx: AWEKAS: Posting
not enabled.
Jul 29 16:34:19 raspberrypi weewx[2579] INFO __main__: Starting up weewx
version 4.1.1
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.engine: Using binding
'wx_binding' to database 'weewx.sdb'
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.manager: Starting
backfill of daily summaries
Jul 29 16:34:19 raspberrypi weewx[2579] INFO weewx.engine: Starting main
packet loop.
Jul 29 16:35:20 raspberrypi weewxd: w34rt: Error writing web service file:
/var/www/html/weewx/weather34/jsondata/aqi.txt, Error: 'ascii' codec can't
encode character u'\xe5' in position 224: ordinal not in range(128)
Jul 29 16:35:24 raspberrypi weewx[2579] INFO weewx.manager: Added record
2020-07-29 16:35:00 CEST (1596033300) to database 'weewx.sdb'
Jul 29 16:35:24 raspberrypi weewx[2579] INFO weewx.manager: Added record
2020-07-29 16:35:00 CEST (1596033300) to daily summary in 'weewx.sdb'
Jul 29 16:35:24 raspberrypi weewx[2579] INFO weewx.restx: Wunderground-PWS:
Published record 2020-07-29 16:35:00 CEST (1596033300)
Jul 29 16:35:26 raspberrypi weewx[2579] INFO weewx.cheetahgenerator:
Generated 8 files for report SeasonsReport in 1.93 seconds
Jul 29 16:35:26 raspberrypi weewx[2579] INFO weewx.imagegenerator:
Generated 15 images for report SeasonsReport in 0.61 seconds
Jul 29 16:35:26 raspberrypi weewx[2579] INFO weewx.reportengine: Copied 5
files to /var/www/html/weewx
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator:
Generate failed with exception '<class 'NameMapper.NotFound'>'
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator: ****
Ignoring template /etc/weewx/skins/Weather34/archivedata.php.tmpl
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator: ****
Reason: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator: ****
 Traceback (most recent call last):
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator: ****
   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator: ****
     unicode_string = compiled_template.respond()
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator: ****
   File "_etc_weewx_skins_Weather34_archivedata_php_tmpl.py", line 2346, in
respond
Jul 29 16:35:27 raspberrypi weewx[2579] ERROR weewx.cheetahgenerator: ****
 NotFound: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jul 29 16:35:27 raspberrypi weewx[2579] INFO weewx.cheetahgenerator:
Generated 0 files for report Weather34Report in 0.39 seconds
Jul 29 16:35:27 raspberrypi weewx[2579] INFO weewx.reportengine: Copied 0
files to /var/www/html/weewx/weather34/
Jul 29 16:35:27 raspberrypi weewx[2579] INFO weewx.cheetahgenerator:
Generated 6 files for report w34Highcharts in 0.36 seconds
Jul 29 16:35:27 raspberrypi weewx[2579] INFO weewx.reportengine: Copied 0
files to /var/www/html/weewx/weather34/w34highcharts

Regards

Peter

Den ons 29 juli 2020 kl 08:17 skrev Ian Millard <notifications@github.com>:

> Peter,
>
> It looks like you do not have PyePhem installed. The archivedata.php.tmpl
> file is searching for extended data that PyePhem generates. As it cannot
> find it, archivedata.php fails.
>
> Please look closely at the installation instructions which details how to
> install PyePhem.
>
> Ian
>

**Comment by steepleian** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by Jmknet** [comment]
Hi!

Phyton 2.7.16 update to 3.8.5 now but still get same error

Jul 30 22:05:18 raspberrypi weewx[5968] INFO weewx.restx: Wunderground-PWS:
Published record 2020-07-30 22:05:00 CEST (1596139500)
Jul 30 22:05:19 raspberrypi weewx[5968] INFO weewx.cheetahgenerator:
Generated 8 files for report SeasonsReport in 2.01 seconds
Jul 30 22:05:20 raspberrypi weewx[5968] INFO weewx.imagegenerator:
Generated 15 images for report SeasonsReport in 0.64 seconds
Jul 30 22:05:20 raspberrypi weewx[5968] INFO weewx.reportengine: Copied 5
files to /var/www/html/weewx
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator:
Generate failed with exception '<class 'NameMapper.NotFound'>'
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator: ****
Ignoring template /etc/weewx/skins/Weather34/archivedata.php.tmpl
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator: ****
Reason: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator: ****
 Traceback (most recent call last):
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator: ****
   File "/usr/share/weewx/weewx/cheetahgenerator.py", line 322, in generate
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator: ****
     unicode_string = compiled_template.respond()
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator: ****
   File "_etc_weewx_skins_Weather34_archivedata_php_tmpl.py", line 2346, in
respond
Jul 30 22:05:20 raspberrypi weewx[5968] ERROR weewx.cheetahgenerator: ****
 NotFound: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jul 30 22:05:20 raspberrypi weewx[5968] INFO weewx.cheetahgenerator:
Generated 0 files for report Weather34Report in 0.42 seconds
Jul 30 22:05:20 raspberrypi weewx[5968] INFO weewx.reportengine: Copied 0
files to /var/www/html/weewx/weather34/
Jul 30 22:05:21 raspberrypi weewx[5968] INFO weewx.cheetahgenerator:
Generated 6 files for report w34Highcharts in 0.42 seconds
Jul 30 22:05:21 raspberrypi weewx[5968] INFO weewx.reportengine: Copied 0
files to /var/www/html/weewx/weather34/w34highcharts

Regards
Peter

Den ons 29 juli 2020 18:11Ian Millard <notifications@github.com> skrev:

**Comment by steepleian** [comment]
Hi,

I have replicated your error on my test server by removing Py Ephem. Did you do a full re-install of WeeWX after you updated to Python3.8. Try uninstalling WeeWX completely as per the instructions in the WeeWX documentation and the re-install using setup.py and the instructions for Python3. You will find all the instructions at http://weewx.com/docs/setup.htm <http://weewx.com/docs/setup.htm>

I.

**Comment by Jmknet** [comment]
Reinstall both weewx an weather34 skin and it's working now, some small
details to fix but yees

Thanks for all your support.

Best regards

/Peter

Den tor 30 juli 2020 23:36Ian Millard <notifications@github.com> skrev:

> Hi,
>
> I have replicated your error on my test server by removing Py Ephem. Did
> you do a full re-install of WeeWX after you updated to Python3.8. Try
> uninstalling WeeWX completely as per the instructions in the WeeWX
> documentation and the re-install using setup.py and the instructions for
> Python3. You will find all the instructions at
> http://weewx.com/docs/setup.htm <http://weewx.com/docs/setup.htm>
>
> I.
>
