### ISSUE TITLE
fewe minor errors in new release

### ISSUE THREAD

**Issue by kc7ngc** [steepleian/weewx-Weather34#1]
Realize its a fresh push with major revisions.   But  noticed a few minor errors when I first went to test it:

currentconditions34.php
`if ($windunit=='kts'){$windunit="kn";}` 
on line 7 needs to be moved till after the include
`include('metar34get.php');` 
As that is what defines winunit

Remove the include from yearlywindspeedgustmendium.php as no longer needed?
w34charts/yearlywindspeedgustmedium.php
`include('chartslivedata.php');`

index.php  
I am guessing that
`include('w34CombinedData.php.php');`
should be
`include('w34CombinedData.php');`

A bunch of references to mbcharts/ directory that should be w34charts/ :

barometeralmanac.php:  
`<iframe  src="mbcharts/yearlybarometermedium.php" frameborder="0" scrolling="no" width="100%" height="205px"></iframe>`

index.php:
`if ($position12=='solaruvwu.php') {echo ' <span class="yearpopup"><a alt="Solar Chart" title="Solar Chart" href="mbcharts/todaysolar.php" data-lity>&nbsp;'. $menucharticonpage. " Solar chart </a></span>";}`

index.php:
`if ($positionlastmodule=='solaruvwu.php') {echo ' <span class="yearpopup"><a alt="Solar Chart" title="Solar Chart" href="mbcharts/todaysolar.php" data-lity>&nbsp;' .$menucharticonpage. " Solar chart </a></span>";}`

rainfallalmanac.php:
`    <iframe    src="mbcharts/yearlyrainfallmedium.php" frameborder="0" scrolling="no" width="100%"    height="225px"></iframe>
solaralmanac.php:  <iframe  src="mbcharts/todaysolarsmall.php" frameborder="0" scrolling="no" width="100%" height="100%"></iframe>`

tempalmanac.php:
`  <iframe  src="mbcharts/yearlytemperaturemedium.php" frameborder="0" scrolling="no" width="100%" height="120px" ></iframe>`

uvalmanac.php:
`  <iframe  src="mbcharts/todayuvsmall.php" frameborder="0" scrolling="no" width="100%" height="100%"></iframe>`

windalmanac.php: 
`<iframe  src="mbcharts/yearlywindspeedgustmedium.php" frameborder="0" scrolling="no" width="100%" height="210px"></iframe>`

Keep up the good work.

**Comment by steepleian** [comment]
All updated. Thanks
