### ISSUE TITLE
MacOS install has incorrect user/group settings

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#10]
The installer fails when attempting to install onto MacOS X as it complains that there is no www-data user and group.

The standard user/group for the web directory as created by weewx in macOS is: 
user: root 
group: staff

I changed these in the installer.py file manually and the installation completed but this would need to be a user-configured option, or specific to macOS.conf.

Cheers
Chris

**Comment by balloonhotair** [comment]
Hi,
Changes add to development so the user and group are now read from the config files.  
Ian still needs to test the installs and move changes to master.
