### ISSUE TITLE
index.php

### ISSUE THREAD

**Issue by rolsch** [steepleian/weewx-Weather34#106]
Hmm,
i think there was some small problems:

1) wpop__solaralmanac.php do not exist, should rename to pop__solaralmanac.php

2) ...php echo $chartsource ;?>/todaysolar.php" was not parsed...?

index.php

`
if ($position12 == 'solaruvwu.php')
{
    echo ' <span class="yearpopup"><a alt="Solar Almanac" title="Solar Almanac" href="**wpop**_solaralmanac.php" data-lity>' . $chartinfo . " Solar Almanac </a></span>";
}
if ($position12 == 'solaruvwu.php')
{
    echo ' <span class="yearpopup"><a alt="Solar Chart" title="Solar Chart" href="<?php echo $chartsource ;?>/todaysolar.php" data-lity>&nbsp;' . $menucharticonpage . " Solar chart </a></span>";
}`

**Comment by Rayvenhaus** [comment]
Thank you for reporting this issue, the fix has been pushed to the dev branch for testing and will be pushed to Main asap.

**Comment by rolsch** [comment]
Fine,
the link to pop__solaralmanac.php works now :-)

But this works not:

`if ($position12 == 'solaruvwu.php') { echo ' <span class="yearpopup"><a alt="Solar Chart" title="Solar Chart" href="<?php echo $chartsource ;?>/todaysolar.php" data-lity>&nbsp;' . $menucharticonpage . " Solar chart </a></span>"; }`

I see no todaysolar.php file in the /var/www/html/weewx/ dir.

**Comment by Rayvenhaus** [comment]
That one will take a little more time to track down, we'll get back to you asap on it, thank you for reporting the error

**Comment by steepleian** [comment]
That link is a legacy and should have been removed. Weather Underground is no longer used as a source of solar data due to unreliable data and flaky performance in many regions. Apologies if this has caused you a problem.

**Comment by Rayvenhaus** [comment]
Push fix for Issue #106

**Comment by steepleian** [comment]
Issue closed. Thank you Stephen
