### ISSUE TITLE
Cloud cover never shows beyond a couple of percent

### ISSUE THREAD

**Issue by CoryManson** [steepleian/weewx-Weather34#11]
I've just recently updated to the latest version but this has been an issue since the cloud cover feature was introduced.

Cloud cover on my install has never really shown beyond 2%. What settings should I be looking at to ensure the correct data?

![image](https://user-images.githubusercontent.com/5052021/99925202-48cf8700-2d91-11eb-9e68-b8656d35572d.png)

**Comment by steepleian** [comment]
Cory,
Remind me of your location again. Although I was reassured that sat24 now
covered most continents, recent experience for users in the Americas
suggest that now not always the case. You can disable in weewx.conf and
then it will not appear in the module.

I am looking at alternative methods including current conditions APIs from
forecasting providers.

Ian

**Comment by CoryManson** [comment]
Hi ian,

I'm in Australia, NSW.

**Comment by steepleian** [comment]
Hi Cory,

I remember now. Can you let me have your co-ordinates and I will check with
sat24 what the actual coverage is there.

Thank you
Ian

**Comment by CoryManson** [comment]
Hi Ian,

My coords are -34.969410, 149.029434

**Comment by balloonhotair** [comment]
I just checked the api from sat24 and it looks like au is not support just yet.

**Comment by steepleian** [comment]
Interestingly I have checked the API from here in the UK using the Australian co-ordinates and they appear to work. Does this mean that the functionality has not replicated correctly outside Europe? I will see what sat24 has to say.

**Comment by steepleian** [comment]
Unfortunately the sat24 API is not yet capable in The Americas and Oceania. Disabling in weewx.conf removes the field from the current conditions. Will continue to monitor the situation with sat24 and look at alternative solutions for Cloud Cover
