### ISSUE TITLE
A request for kPa - and a Thanks!

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#12]
Hello folks,

I first want to thank you for your hard work! I just completed the install of the new version with the big changes in settings files and remote web server stuff and I *think* I've got it all working.  It was much simpler than it ever has been before to get the remote side working, I may ask another question on that front but I just wanted to make sure I thanked you here.

The request:  May I kindly request an addition to the units for barometric pressure of kiloPascals (kPa)?

This is the official standard measurement for barometric pressure in Canada. WeeWx just included it as a standard unit in its latest release, which is pretty exciting for this Canadian!  It'd be wonderful if Weather34 would display as well so everything was consistent.

Thanks again,
Chris

**Comment by steepleian** [comment]
Hi Chris,

Thanks for the compliment. Most of the install improvements are down to
Jerry although there is a tiny bit of me in there as well. I am sure Jerry
will appreciate your feedback as well.

I will have a look at the conversions required and work on the development
repository to let you have a play at we come up with.

Cheers,
Ian

**Comment by balloonhotair** [comment]
All the highchart plots now support kPa, just need to change the php files.

**Comment by chrisale** [comment]
Wow great!!

“They always tell me it takes time. How much more time do you want...for your progress?”
James Baldwin

Chris Alemany
3854 6th Ave
Port Alberni, BC
V9Y4M2
h:250-723-0889
w: 250-753-3245 x2106
e: chrisale@gmail.com
w: www.chrisalemany.ca
w: www.alberniweather.ca
w: www.vifreightbyrail.ca

**Comment by balloonhotair** [comment]
Ok changes for kPa to php files completed in dev.

**Comment by chrisale** [comment]
Sounds great, thanks Ian.

**Comment by steepleian** [comment]
Incorporated in the next version of weewx-Weather34
