### ISSUE TITLE
some svg images missed: no *.svg generated

### ISSUE THREAD

**Issue by rolsch** [steepleian/weewx-Weather34#121]
Hello.
Some svg images was missed.
I see that the html output show no .../svg/image-name.svg, only .../svg/ in the path.

- any hints, i come from 4.2.2 to 4.2.8.2 with new pre-install services.txt file.

![image](https://user-images.githubusercontent.com/5867018/161335850-b02103d2-455c-40b6-89e6-a9b90f0b7915.png)

**Comment by Rayvenhaus** [comment]
The SVG files in question are most defiantly in the GitHub repo here. Those images are in the [webroot]/css/svg/

Plese verify that your [webroot]css/svg on your server directory matches what is in the [weewx-Weather34]/[www]/[css]/svg/ here

**Comment by steepleian** [comment]
Also can you check in your jsondata folder to see if you have a file called lookupTable.json. This matches the AerisWeather forecast code and description to the correct svg image.

**Comment by rolsch** [comment]
Hi Ian,
the lookupTable.json was missed in the jsondata.
I have manually copy this file and after weewx restart the image-names was filled in the html output :-)

**Comment by steepleian** [comment]
Excellent, I am glad it is now working OK for you.
