### ISSUE TITLE
pop_europealerts.php: missing eu.txt file

### ISSUE THREAD

**Issue by rolsch** [steepleian/weewx-Weather34#122]
Hello.
I had the version 4.2.2 and was upgraded to 4.2.8.2
After some trial and error i removed the old 4.2.2 Weather34 skin (weewx.conf, skin/, user/ and www/...)
Weewx starts fine and works with no error messages in the log.

Now with a fresh install (yes, new sevices.txt from the web-form) i see an empty weather alerts.

My findings:

pop_europealerts.php
-> $json_string = file_get_contents("jsondata/eu.txt");
-> i have no eu.txt in this path

I see this Log-Message when weewx restarted:
ERROR user.weather34: Error Invalid Webservice Data: None, {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'}

This message disapears when i remove the eu service in the file weewx.conf in the section [Weather34WebServices]:
services = aq.awc.awh.awd.awp.awa.wu.eq.ki.me.**eu**

Any helpful hints for this problem?

**Comment by steepleian** [comment]
Your weewx.conf looks something like this?: -

eu_url = https://api.aerisapi.com/alerts/51.940, -0.987?format=json&limit=10&lang=en&client_id=your_id&client_secret=your_secret
    eu_interval = 3600

**Comment by rolsch** [comment]
No,
no "eu_url = ..." in my weewx.conf.

 I think no "eu" web-service was generated...?

**Comment by steepleian** [comment]
Ok if you add to your web services section in weewx.conf using your own AerisWeather I’d and secret keys and add .eu to the string, restart WeeWX, you should be Ok

**Comment by rolsch** [comment]
Hi.
Many thanks - it works :-)

I have added this lines and .eu to services = aq.awc.awh.awd.awp.awa.wu.eq.ki.me.**eu**

eu_url = https://api.aerisapi.com/alerts/49.2xxxx,6.8xxxx?format=json&limit=10&lang=en&client_id=---deleted---&client_secret=---deleted---
eu_interval = 3600

Is there a bug in the pre-installation process or why must i manually set the lines?

**Comment by steepleian** [comment]
Not a bug in the normal sense but now improved in version 4.2.8.3

European weather alerts jsondata now defaults to awa.txt

**Comment by steepleian** [comment]
Not a bug in the normal sense but now improved in version 4.2.8.3

European weather alerts jsondata now defaults to awa.txt
