### ISSUE TITLE
world AQI values are 0

### ISSUE THREAD

**Issue by rolsch** [steepleian/weewx-Weather34#123]
Weather32 version 4.2.8.2

The world AQI values are 0
- the aq.txt is refreshed and present.

https://api.waqi.info/feed/geo:49.23503;6.823372/?token=---deleted---

`{"status":"ok","data":{"aqi":38,"idx":7663,"attributions":[{"url":"http://air-lorraine.org/","name":"Air Lorraine - Surveillance et Ã©tude de la qualitÃ© de l'air en Lorraine","logo":"France-AirLorraine.png"},{"url":"http://www.atmo-grandest.eu/","name":"AtmoGE - La qualitÃ© de l\u0026#8217;air dans le Grand Est","logo":"France-atmo-grand-est.png"},{"url":"https://waqi.info/","name":"World Air Quality Index Project"}],"city":{"geo":[49.18748553504153,6.910756864974066],"name":"Forbach-Centre, France","url":"https://aqicn.org/city/france/lorraine/forbach-centre"},"dominentpol":"pm25","iaqi":{"h":{"v":59.5},"no2":{"v":4.6},"o3":{"v":41.9},"p":{"v":982.2},"pm10":{"v":12},"pm25":{"v":38},"t":{"v":3},"w":{"v":3},"wg":{"v":4.5}},"time":{"s":"2022-04-02 18:00:00","tz":"+02:00","v":1648922400,"iso":"2022-04-02T18:00:00+02:00"},"forecast":{"daily":{"o3":[{"avg":33,"day":"2022-04-02","max":35,"min":31},{"avg":32,"day":"2022-04-03","max":41,"min":24},{"avg":32,"day":"2022-04-04","max":42,"min":19},{"avg":28,"day":"2022-04-05","max":39,"min":22},{"avg":21,"day":"2022-04-06","max":21,"min":19}],"pm10":[{"avg":6,"day":"2022-04-02","max":7,"min":4},{"avg":10,"day":"2022-04-03","max":14,"min":7},{"avg":14,"day":"2022-04-04","max":26,"min":6},{"avg":6,"day":"2022-04-05","max":9,"min":4},{"avg":9,"day":"2022-04-06","max":10,"min":9}],"pm25":[{"avg":19,"day":"2022-04-02","max":25,"min":14},{"avg":39,"day":"2022-04-03","max":54,"min":23},{"avg":46,"day":"2022-04-04","max":78,"min":23},{"avg":22,"day":"2022-04-05","max":32,"min":16},{"avg":33,"day":"2022-04-06","max":40,"min":33}],"uvi":[{"avg":0,"day":"2022-04-02","max":2,"min":0},{"avg":0,"day":"2022-04-03","max":2,"min":0},{"avg":0,"day":"2022-04-04","max":3,"min":0},{"avg":0,"day":"2022-04-05","max":1,"min":0},{"avg":0,"day":"2022-04-06","max":2,"min":0},{"avg":0,"day":"2022-04-07","max":0,"min":0}]}},"debug":{"sync":"2022-04-03T02:23:37+09:00"}}}`

Regards
Roland

**Comment by steepleian** [comment]
That is a different format of jsondata that I get from waqi for my location. I will have to look at that in more detail. How far are you from the location of that sensor? If you are not in the immediate location, it is probably irelevant anyway. It might be simpler to use a predicted level from AerisWeather.

**Comment by rolsch** [comment]
This sensor is 5 miles away.

But i have an own pm25 sensor running in my local lan network thats reports to:
https://opensensemap.org/explore/5eab2cd2712645001bc48e85
and
https://devices.sensor.community/sensors/24021/data?lang=en

This is a project from
https://sensor.community/en/sensors/airrohr/

I think the sensor can post the pm values directly to weewx with some plugin development.

I found this posting :-)
https://www.mail-archive.com/weewx-user@googlegroups.com/msg31861.html

- any hints fpr me :-)

**Comment by steepleian** [comment]
Yes I can help. As this not directly related to the issue can you contact me via email and  I will guide you through the process. ***@***.***
Thanks

**Comment by rolsch** [comment]
Hi Ian.

Ok, look to the jsondata format...

I have send a mail for the airrohr sensor issue ;-)

Last problem- the cloud cover is empty, i open a new issue for this...

**Comment by steepleian** [comment]
Closing, treating issue as a seperate new project

**Comment by steepleian** [comment]
Closing issue, treating issue as a seperate new project
