### ISSUE TITLE
Curent Conditions - Cloud Cover empty

### ISSUE THREAD

**Issue by rolsch** [steepleian/weewx-Weather34#124]
Hello Ian.
Now my last issue after upgrading/fresh install from 4.2.2 to 4.2.8.2.

My Curent Conditions -> Cloud Cover pop-up is empty.

I read the weewx-Weather34-main\HIGHCHARTS_GUIDE.md but see some diff to my plots_config.js.

guide.md:

        var pathweewx = '/weewx/'             //Path from web server home location to weewx directory
        var pathpws   = '/weather34/'               //Path from web server home location to weather34 directory
        var pathweewxbin ='/home/weewx/bin'  //Physical path to weewx include files for wee_report_w34 if setup.py installed WeeWX
        //var pathweewxbin ='/usr/share/weewx'  //Physical path to weewx include files for wee_report_w34 if DEB installed WeeWX

        var realtimefile =  pathweewx   + "w34realtime.txt";    //Location of real-time data from web server
        var pathjsonfiles = pathpws + "w34highcharts/json/";                    //Location weewx report output json files from home             location of weewx. DO NOT CHANGE UNLESS YOU CHANGE SKIN DIRECTORY.

        var dayplotsurl =   pathpws   + "w34highcharts/getDayChart.php"; //Location of day reports php file from home location of pws.
        var pathjsondayfiles = "json_day/";                         //Location day report output json files from home location of where         wee_report_34 run. DO NOT CHANGE UNLESS YOU CHANGE SKIN DIRECTORY.
        var weereportcmd = "./wee_reports_w34";                     //Command to run wee_report_34. DO NOT CHANGE.
 
my .js file

```
var pathjsonfiles =  "json/";            //Location weewx report output json files from home location of weewx. DO NOT CHANGE UNLESS YOU CHANGE SKIN DIRECTORY.
var pathjsondayfiles = "json_day/";      //Location day report output json files from home location of where wee_report_34 run. DO NOT CHANGE UNLESS YOU CHANGE SKIN DIRECTORY.
var weereportcmd = "./w34_reports";  //Command to run w34_reports. DO NOT CHANGE.
var realtimefilename = "serverdata/w34realtime.txt"; //File name must match what is in the weewx config for realtime


Compared to claydonsweather.org.uk my file is correct ;-)

Any hints?

**Comment by balloonhotair** [comment]
In case Ian is busy, we need the webserver error log. If apache it would be located in /var/log/apache2. Also we need the browser error console output.
Thanks

**Comment by steepleian** [comment]
Can you check that in weewx.conf under the [Weather34CloudCover] stanza that you have (substitute your own lat and lon values): -

enable = True
    db_field = signal8
    cc_interval = 300
    cc1_url = https://api.sat24.com/crop?type=visual5hdcomplete&lat=51.940&lon=-0.987&width=300&height=300&zoom=1.00&continent=eu
    cc1_filename = /tmp/sat1.png
    cc2_url = https://api.sat24.com/crop?type=infraPolair&lat=51.940&lon=-0.987&width=300&height=300&zoom=1.00&continent=eu
    cc2_filename = /tmp/sat2.png

**Comment by rolsch** [comment]
Yes, both URL show an picture and my position is in the center
`
{ 
   'enable':'true', 
   'db_field':'signal8', 
   'cc_interval':'300', 
   'cc1_url':'https://api.sat24.com/crop?type=visual5hdcomplete&lat=49.23503&lon=6.823372&width=300&height=300&zoom=1.00&continent=eu', 
   'cc1_filename':'/tmp/sat1.png', 
   'cc2_url':'https://api.sat24.com/crop?type=infraPolair&lat=49.23503&lon=6.823372&width=300&height=300&zoom=1.00&continent=eu', 
   'cc2_filename':'/tmp/sat2.png', 
}''', 
}

`

**Comment by rolsch** [comment]
Browser-console

`
{temp: 'C', pressure: 'hPa', wind: 'km/h', rain: 'mm'}pressure: "hPa"rain: "mm"temp: "C"wind: "km/h"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() 'cloudcoverplot' ['weekly']0: "weekly"length: 1[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}[[Prototype]]: Object false false null false false 'plot_div'
plots.js:604 
        
       Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at reinflate_time (plots.js:604:12)
    at Array.create_cloudcover_chart (plots.js:1593:35)
    at setup_plots (plots.js:1823:77)
    at Object.<anonymous> (plots.js:1854:24)
    at i (jquery.min.js:2:27449)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28213)
    at Object.e.<computed> (jquery.min.js:2:29192)
    at i (jquery.min.js:2:27449)
    at Object.add [as done] (jquery.min.js:2:27748)
    at Object.<anonymous> (jquery.min.js:2:28848)
reinflate_time @ plots.js:604
create_cloudcover_chart @ plots.js:1593
setup_plots @ plots.js:1823
(anonym) @ plots.js:1854
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
e.<computed> @ jquery.min.js:2
i @ jquery.min.js:2
add @ jquery.min.js:2
(anonym) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
y @ jquery.min.js:4
c @ jquery.min.js:4
XMLHttpRequest.send (asynchron)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.<computed> @ jquery.min.js:4
getJSON @ jquery.min.js:4
(anonym) @ plots.js:166
map @ jquery.min.js:2
jQuery.getMultipleJSON @ plots.js:165
display_chart @ plots.js:1852
plot_js @ plots.js:1984
(anonym) @ dark-charts.html?chart=%27cloudcoverplot%27&span=%27weekly%27&temp=%27C%27&pressure=%27hPa%27&wind=%27km/h%27&rain=%27mm:25
window.onload @ dark-charts.html?chart=%27cloudcoverplot%27&span=%27weekly%27&temp=%27C%27&pressure=%27hPa%27&wind=%27km/h%27&rain=%27mm:25
load (asynchron)
(anonym) @ dark-charts.html?chart=%27cloudcoverplot%27&span=%27weekly%27&temp=%27C%27&pressure=%27hPa%27&wind=%27km/h%27&rain=%27mm:18

`

**Comment by rolsch** [comment]
apache2 log show no error.

`
petrus@debian10-weewx:/var/log/apache2# tail -f other_vhosts_access.log|grep dark-chart
debian10-weewx.localdomain:80 192.168.0.2 - - [06/Apr/2022:19:28:07 +0200] "GET /weewx/weather34/w34highcharts/json/solar_week.json HTTP/1.1" 200 69380 "http://192.168.0.209:81/weewx/weather34/w34highcharts/dark-charts.html?chart=%27cloudcoverplot%27&span=%27weekly%27&temp=%27C%27&pressure=%27hPa%27&wind=%27km/h%27&rain=%27mm" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29"
^C

`

**Comment by rolsch** [comment]
cc1_filename = /tmp/sat1.png
cc2_filename = /tmp/sat2.png

- i don't find this files...

**Comment by steepleian** [comment]
I have spotted the problem

enable = True

The T must be upper case

**Comment by steepleian** [comment]
Closing

**Comment by rolsch** [comment]
Hi Ian.

I have change to True but no cloud-cover was displayed.

weewx.conf

`# Apply your own latitude and longitude and continent to the URLs in this section
 
[Weather34CloudCover]
    enable = True
    db_field = signal8
    cc_interval = 300
    cc1_url = https://api.sat24.com/crop?type=visual5hdcomplete&lat=49.23503&lon=6.823372&width=300&height=300&zoom=1.00&continent=eu
    cc1_filename = /tmp/sat1.png
    cc2_url = https://api.sat24.com/crop?type=infraPolair&lat=49.23503&lon=6.823372&width=300&height=300&zoom=1.00&continent=eu
    cc2_filename = /tmp/sat2.png
#
`
