### ISSUE TITLE
new options in weewx.conf

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#125]
Hi there,

I've been upgrading to the new versions of weewx and weather34. Things have gone smoothly with my remote setup but I'm getting some intermittent behaviour so I'm troubleshooting.

Can you refresh my memory on what should be in the
"realtime_path_only" 
and
"weewx_file_transfer"

options under Weather34RealTime?

Thanks!
Chris

**Comment by balloonhotair** [comment]
realtime_path_only is a path to where a user wants to put the realtime.txt file if it is different that what is normal.
weewx_file_transfer very rarely used option to move files when doing remote webservers. The default mode is rysnc but it can also be a socket, if security is not an issue and the webserver can be accessed by the weewx machine. Mostly used for testing remote webservers.

**Comment by balloonhotair** [comment]
So to directly answer your question both config variables should not have any values.

**Comment by steepleian** [comment]
Closing issue

**Comment by steepleian** [comment]
Closed
