### ISSUE TITLE
Barometer "pinned" - related to kPa unit?

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#127]
Hi again,

Hopefully this one is much easier to diagnose than the last, apologies for the quick succession. :)
I believe this has been like this for awhile so it's not upgrade related.
The Barometer meter is 'pinned' on the right side all the time.
I remember when we added kPa support in both weewx and weather34 there was some mis matching of units and values so I suspect this is the same. It may be a weewx.conf issue or something a little deeper.
![Screen Shot 2022-04-13 at 09 19 17](https://user-images.githubusercontent.com/1987081/163225756-61b646da-0d92-4ee7-80b4-8e83c54e5445.png)

The live screen is here: www.alberniweather.ca

**Comment by balloonhotair** [comment]
Does it only happen when in Kpa mode? What about the other values? Some of them look wrong also.

**Comment by steepleian** [comment]
Corrected rotation error when kPa units selected in commit 

barometer.php updated in main and development
