### ISSUE TITLE
Wind Gust not displayed properly (metric/us units problem?)

### ISSUE THREAD

**Issue by kamiKAC** [steepleian/weewx-Weather34#13]
Since July 28th I can see strange values for Wind Gust. Most of the time Wind Gust value is lower than Wind Speed.
I've also observed that I have the same value for Wind Gust when displayed in US and metric units while Wind Speed is properly recalculated. See attached screenshots.
![capture_007_30082020_233149](https://user-images.githubusercontent.com/13069647/91670172-4dcac480-eb1b-11ea-8141-70f1c7190169.jpg)
![capture_006_30082020_233135](https://user-images.githubusercontent.com/13069647/91670173-4efbf180-eb1b-11ea-8fff-fe05526621f6.jpg)

**Comment by steepleian** [comment]
Hi,

I have updated the file windspeeddirection.php. There was an error causing
the problem. Apologies for that.

Also please make sure that you do not change the the [[[Groups]]] settings
in the [[Weather34Report]] stanza of weewx.conf

They should remain METRICWX as follows : -

[[Weather34Report]]
        skin = Weather34
        HTML_ROOT = /var/www/html/weewx/weather34/
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_degree_day = degree_C_day
                group_pressure = hPa
                group_rain = mm
                group_rainrate = mm_per_hour
                group_speed = meter_per_second
                group_speed2 = meter_per_second2
                group_temperature = degree_C

The conversion calculations take place in the skin, not in WeeWX. The skin
expects data to arrive in METRICWX units and this is what the conversions
calculations are based upon. Any other skins you may be using are
unaffected by this.

Final comment regarding wind gust speed. The WeeWX interpretation of wind
gust speed is used, that is the maximum wind speed over an archive period.
As this is essentially an historical record, it is perfectly possible to
have a wind gust speed lower than the current wind speed. Of course it
would be very strange if this happened consistently.

**Comment by kamiKAC** [comment]
My [[Weather34Report]] stanza looks like in your example.
After updating windspeeddirection.php my Wind Gust values look much better (more realistic).

Thanks for the prompt solution.
