### ISSUE TITLE
weewxserverinfo.txt , settings1.php, file paths, weewx_file_transfer and other variables questions

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#13]
Hello all,

As you know I've been working at getting the remote install working.  I think I've come to understand mostly how it is working but there are some hiccups I hope to address here.

My setup:

Local side
- Local weewx server (an iMac) running weewx and the weather34 Skin along with numerous other skins and extensions.
- The local weewx server is already running rsync through cron every 60 seconds and weewx updating a few separate 'realtime' style files. 

Remote side: 
- Offsite (public) web server (Linux) at 34.130.36.232 (fake IP:)) running php/apache/nginx hosting alberniweather.ca

I installed the latest weather34 skin today.  The install went very smoothly.  I used the utility to create the 'services.txt' file which seems to have gone a long way toward getting everything right.

In weewx.conf there is now a section with the following configuration settings and I've filled in my settings:

[[Weather34Report]]
    skin = Weather34
    HTML_ROOT = /var/www/weather34/

[Weather34RealTime]
  filename = /var/www/weather34/serverdata/w34realtime.txt
  unit_system = METRICWX
  exclude_fields = rain
  cache_enable = True
  cache_directory = /tmp
 weewx_port = 25252
 webserver_address = www.alberniweather.ca
 weewxserver_address = 34.130.36.232
 weewx_file_transfer = yes

[Weather34WebServices]
  aq_url = https://api.waqi.info/feed/geo:49.246321;-124.803613/?token=
  aq_interval = 3600
  aq_filename = /var/www/weather34/jsondata/aqi.txt
  ds_url = https://api.forecast.io/forecast//49.246321,-124.803613?lang=English&units=ca
  ds_interval = 3600
  ds_filename = /var/www/weather34/jsondata/darksky.txt
  wu_url = https://api.weather.com...
  wu_interval = 3600
  wu_filename =/var/www/weather34/jsondata/wuforecast.txt
  eq_url = https://earthquake-report.com/feeds/recent-eq?json
  eq_interval = 3600
  eq_filename = /var/www/weather34/jsondata/eqnotification.txt
  ki_url = https://services.swpc.noaa.gov/products/geospace/planetary-k-index-dst.json
  ki_interval = 43200
  ki_filename = /var/www/weather34/jsondata/kindex.txt
  me_url = https://api.checkwx.com/metar/CYQQ/decoded
  me_header = X-API-Key:...
  me_interval = 3600
  me_filename = /var/www/weather34/jsondata/metar34.txt
  pu_url = https://www.purpleair.com/json?show=36625
  pu_interval = 3600
  pu_filename = /var/www/weather34/jsondata/purpleair.txt
  al_url = http://www.alberniweather.ca/weewx/weather34/eualert.php?country=&region=
  al_interval = 3600
  al_filename =/var/www/weather34/jsondata/meteoalarm.txt
  services = ds.me.eq.ki.wu.pu

[Weather34RemoteWebServer]
  enable = true
  port = 25252

.....

Problems:

1) The settings file.
I had to remove the settings1.php file on the local side as my regular weewx rsync update was replacing the generated settings1.php file on the remote side with the default from the installation.  I deleted the settings1.php file on the local side and this resolved this issue.

2) The weewxserverinfo.txt file

Is the weewxserver_address field supposed to populate the weewxserverinfo.txt file?  Currently, the weewxserverinfo.txt file is reporting my local network IP address rather than the address in the weewx.conf.

3) The filename paths are set to a path that makes sense for the remote server. Is this correct or should some be local and some remote?

**Comment by balloonhotair** [comment]
Lot to answer here.
1) The settings1.php file does not get touched or used with the new remote webserver. It is now only used by the template running on the web server.
2)The file weewxserverinfo.txt should contain the ip address of the weewx machine. This is needed by the remote webserver when getting data for the graphs. The code weather34.py tries to figure out what is the ip address when it starts up, but there are no sure way of getting the correct address. If the address is incorrect then in the weewx.conf put the correct ip addreess in the config entry called weewxserver_address. Again this is the ip address of the weewx machine as seen by your remote web server.
3)For the web services filename and paths are remote web server locations. When in remote mode the output from the web services is written to a /tmp directory on the weewx machine and then rsync to the filename paths on the remote webserver.
For w34realtime.txt, archivedata.php, weewxserverinfo.txt the paths are local web server paths also, with the additional care of not changing the serverdata part of the path. The path above serverdata can be changed if needed.

**Comment by chrisale** [comment]
Hi Jerry! 

Thanks so much on your work on this, it’s amazing stuff.

1) On the settings file. I’m a little confused. Should I have run through the settings process on the remote side at all? When it installed, it wiped out the previous settings (which I expected) and I did the normal setup on the remote web side as if it were a normal local install.

Although come to think of it, I did not remove the previous weather34 directory on the remote side before installing the new version. Maybe I should have?

2) So this appears to be a problem as the proper public network address I am putting into the weewxserver_address setting in weewx.conf is being ignored and the file is overwritten with the local network IP address of the weewx machine whenever weewx updates.

3 a) OK, I believe I have the web server paths correct. By default they are headed into the jsondata directory inside weather34, yes:
Ie:
/var/www/vhosts/alberniweather.ca/weather34/jsondata/xxxx.txt

3 b) What config variables in weewx.conf (or elsewhere) are setting local weewx server paths? Just so I can double check them?

Additional question:

4) I still have section for [Weather34RemoteWebServer] in weewx.conf. Is this still needed?

Thanks again! I’m looking forward to being able to create a new tutorial to help folks through this once I get mine all figured out!

Cheers
Chris

**Comment by balloonhotair** [comment]
The remote web server needs the settings1.php file since that is where php runs. There is on php running on the weewx machine so the settings1.php is not needed. Deleting the old weather34 directory would be the best way, but save your settings1.php incase you forget what settings you have.
The weexserver_ip was not being read from the config file. The attached version should correct that.
Just the webservices files and the w34realtime file. And really these can go away with a code change to use the HTML_ROOT, so I will add this to the todo list.
The Remote section is no longer used so it can be deleted.

[weather34.txt](https://github.com/steepleian/weewx-Weather34/files/5645111/weather34.txt)

**Comment by chrisale** [comment]
Great!  Making progress!

1) Perfect, we’re on the same page. Thanks.
2) Fixed now, proper IP is being transmitted.

OK, subsequent questions/comments:

1) I must be misunderstanding because you seem to say a local path should be in place for the Weather34Report and w34highcharts reports at HTML_ROOT.  But weewx seems to be expecting the remote path all the time in all path settings.  If I have any local path (either as public_html/weather34/blah or /Users/Shared/weewx/weather34/blah…) I am getting errors from rsync for paths that don’t match the remote server.

ERROR weeutil.rsyncupload: [['rsync', '--archive', '--stats', '-e ssh', 'public_html/weather34/serverdata', 'alberniweather@199.204.214.53:public_html/weather34/serverdata']] reported errors: rsync: link_stat "/Users/Shared/weewx/skins/purple/public_html/weather34/serverdata" failed: No such file or directory (2). rsync: connection unexpectedly closed (8 bytes received so far) [sender]. rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/io.c(453) [sender=2.6.9]
weewx[63004] ERROR weeutil.rsyncupload: [['rsync', '--archive', '--stats', '-e ssh', 'public_html/weather34/w34highcharts/json', 'alberniweather@199.204.214.53:public_html/weather34/w34highcharts/json']] reported errors: rsync: link_stat "/Users/Shared/weewx/skins/purple/public_html/weather34/w34highcharts/json" failed: No such file or directory (2). rsync: connection unexpectedly closed (8 bytes received so far) [sender]. rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/io.c(453) [sender=2.6.9]

2) Noticed a possible issue on the settings configuration page.  There is no actual spot to specific the jsondata folder.  The WeewxChart Data field is overtop.  I’ve attached a screenshot.

3) What can I look for in the operation of the webpage that would indicate the direct communication over port 25252 is working?

4) I checked my /tmp directory to see what was being generated. I was suprised by the number of folders weather34 created, so I specified /tmp/weather34 instead. Personal preference not a suggestion or complaint. :)

5) What effect will shortening the cache_stale_time have under Weather34RealTime? I assume this is just checking the various web services? Is there a way to disable services we are not using?

Thanks!
Chris

**Comment by balloonhotair** [comment]
1) So for rsync to work the remote path must exist. Need more info on this one.
2) The jsondata directory needs to exist in the weather34 directory. There is no configuration for it. It is what is required by the template, just like the serverdata directory.
3) If port 25252 is not working then none of the plots will work.
4) Understand.
5) cache_stale time is just used for the loop data on systems that loop packet events do not contain all the loop data so a cache is used to fill out the loop packet with the missing data. Nothing to do with web services. 
Yes there is config entry called services and is a string of two characters for each service, just remove the two characters of the service you do not want.

**Comment by balloonhotair** [comment]
So HTML_ROOT needs to be the location on the web server. 
Are both filesystems IOS or is it a mix of Linux and IOS?
 Are you still running you own rsync to move archived data? If so that is not necessary with these changes, since now weather34.py rsyncs everything the web server should need.

**Comment by balloonhotair** [comment]
There are a ton of moving pieces going one, so it would best to just look at one issue at a time.

**Comment by chrisale** [comment]
Thank you for all of the answers. It’s just the rsync stuff remaining I think!

Weewx server is macOS, remote is Linux.
My rsync outside of weewx is only uploading the former realtime directory which weather34 used to use..

Weewx is syncing the entire public_html directory including the weather34 directory.

Cheers
Chris

**Comment by balloonhotair** [comment]
So do not see the need anymore for weewx to rsync the public_html directory anymore since it will be doing the same as what the rsync of weather34.py. is doing which is the jsondata directory and the serverdata directory which has the realtime and archived data and the json directory for plots. When day plots are displayed then there is a one time rsync of the json-day directory. If we stop the weewx rsync it will be good to know if the serverdata directory is getting updated. If if is then we can check the other directories, but if not then we need to look at what the paths are and the errors.

**Comment by chrisale** [comment]
I am still using other skins that are updating inside the public_html directory and are being rsync’ed by weewx.  However, for testing I’ll turn off weewx rsync for now and see how weather34 reacts.

**Comment by balloonhotair** [comment]
Yes understand, just trying to see if the weather34.py rsync is working since it is being done from a macos to linux which is a test case we could not test.

**Comment by chrisale** [comment]
Yes I can confirm it is working just fine.
It’s a little difficult to tell as we are in a very stagnant weather pattern right now. No wind and very small temperature/barometer changes!
But everything does seem to be updating.  The only one that lags seems to be the purple air AQ reading. It only seems to update when I refresh the browser window.

You can check it out here:
https://www.alberniweather.ca

It’s very impressive to see 15 years of data plotted so quickly and easily in your charts!

Cheers
Chris

**Comment by balloonhotair** [comment]
Here is the issue with the rsync. Since you have two different file systems due to two different os the config variable HTML_ROOT is in conflict. HTML_ROOT is used by the Cheetah reporting system to write reports and it is also used to know the location of the install of the template.  So on your setup these locations are different. For your setup the only way I can think to make it work is to create a new config entry called HTML_ROOT in the weather34Realtime section of the weewx config. So in most cases it would be the same as HTML_ROOT but in your case you would put in your linux path on your web server and have the HTML_ROOT in the template section with a macos path so Cheetah can still work.

**Comment by chrisale** [comment]
That makes sense. Anyone hosting on a paid web server space will be almost guaranteed to have a different file path than on their local system as they often use virtual hosts and such or have multiple domains hosted on one web server account.

I will await your updates and thank you again for your work. Glad to help figure it out.

I have noticed the forecasts are not updating. This may be due to this issue.

Cheers
Chris

“They always tell me it takes time. How much more time do you want...for your progress?”
James Baldwin

Chris Alemany
3854 6th Ave
Port Alberni, BC
V9Y4M2
h:250-723-0889
w: 250-753-3245 x2106
e: chrisale@gmail.com
w: www.chrisalemany.ca
w: www.alberniweather.ca
w: www.vifreightbyrail.ca

**Comment by balloonhotair** [comment]
Changes submitted to dev branch to allow a remote HTML_ROOT in the weather34Realtime section. Also all files and directories written to /tmp are now in a parent directory called weather34. In addition all config entries dealing with filenames have been removed and weather34.py creates the filenames.

**Comment by chrisale** [comment]
Wonderful!

“They always tell me it takes time. How much more time do you want...for your progress?”
James Baldwin

Chris Alemany
3854 6th Ave
Port Alberni, BC
V9Y4M2
h:250-723-0889
w: 250-753-3245 x2106
e: chrisale@gmail.com
w: www.chrisalemany.ca
w: www.alberniweather.ca
w: www.vifreightbyrail.ca

**Comment by steepleian** [comment]
All changes incorporated in the next version of weewx-Weather34
