### ISSUE TITLE
Unable to scroll popup windows on mobile

### ISSUE THREAD

**Issue by CoryManson** [steepleian/weewx-Weather34#133]
Good morning,

I'm currently unable to scroll in any popup window (forecasts, temp charts etc) on Mobile. Using Edge on Android, have also tested with Chrome.

version: 4.3.0
Weewx: 4.8.0

![msedge_elmbERc7W3](https://user-images.githubusercontent.com/5052021/182067894-82f100ca-40cd-46e8-85d5-90113482d812.gif)

**Comment by steepleian** [comment]
Hello,
Unfortunately the popup menus are not designed to scroll on a mobile device. You will find if you turn you phone to landscape you will have a little more control. This is is one of the issues which will be addressed in the complete re-write that is being undertaken at this moment.
Thank you,
Ian

**Comment by CoryManson** [comment]
Thanks Ian, Will keep a lookout for the rewrite.
