### ISSUE TITLE
browsing to /index.php returns a 500

### ISSUE THREAD

**Issue by danrhjones** [steepleian/weewx-Weather34#134]
Hi, 
First time user of weather34.
I am using nginx version: nginx/1.18.0, PHP 8.1.9 and version 4.3.0 of weather34

When I browse to /weewx/weather34/index.php I get a 500 error 

If I check the files in the includes, then only w34CombinedData.php is returning a 500. however it exists in my directory, with the same owners and permissions as the other files.

Nothing in the nginx error logs

Any ideas?

**Comment by steepleian** [comment]
Hi Dan,

I am not an Nginx user myself so there maybe some nuances that I am not aware of. Before we dig into that can ask you to check your archivedata for errors. The combined data is made up of real-time data and archive data (which is where there might be a problem). You will find it in the server data folder.
Thanks for using the template.
Regards
Ian

**Comment by danrhjones** [comment]
I dont have archivedata, only filepileformat.txt (which is empty) and weewxserverinfo.txt which contains:

:25252::/usr/share/weewx%

**Comment by danrhjones** [comment]
And checking again, webserver_ip_address.php is also returning a 500

**Comment by steepleian** [comment]
Ok that sounds like a WeeWX issue then. There are .tmpl files which should generate the archive data. Set your debug to 2 in weewx.conf, restart and use sudo tail to look at your sys logs as they created. I am travelling at the moment but full instructions on checking system logs in the WeeWX documentation.
Ian

**Comment by danrhjones** [comment]
Aug 17 12:07:57 weewx weewx[7918] INFO user.weather34: Cache values not use since they are past the sell by date
Aug 17 12:07:57 weewx weewx[7918] DEBUG user.weather34: w34rt: Exception while handling data: '<' not supported between instances of 'NoneType' and 'int'
Aug 17 12:07:57 weewx weewx[7918] INFO weewx.engine: Main loop exiting. Shutting engine down.
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__: Caught unrecoverable exception:
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****  '<' not supported between instances of 'NoneType' and 'int'
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****  Traceback (most recent call last):
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 153, in main
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****      engine.run()
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 210, in run
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****      callback(event)
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****    File "/usr/share/weewx/user/weather34.py", line 822, in handle_new_loop
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****      self.handle_data(event.packet)
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****    File "/usr/share/weewx/user/weather34.py", line 857, in handle_data
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****      data = self.calculate(event_data, dbm)
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****    File "/usr/share/weewx/user/weather34.py", line 1060, in calculate
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****      data['is_daylight'] = calc_is_daylight(alm)
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****    File "/usr/share/weewx/user/weather34.py", line 288, in calc_is_daylight
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****      if sunrise < alm.time_ts < sunset:
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****  TypeError: '<' not supported between instances of 'NoneType' and 'int'
Aug 17 12:07:57 weewx weewx[7918] CRITICAL __main__:     ****  Exiting.

**Comment by danrhjones** [comment]
Sorry, mea culpa, I had to set my raspberry pi up again, and I didn't add the proper weewx.conf.

Have done that now, and I DO have an archivedata.php

`<?php







$sta['location'] = "Pitstone, UK";
$sta['name'] = "Pitstone, UK";
$sta['latitude'] = "51.8342";
$sta['longitude'] = "0.6428";
$sta['altitude_meters'] = "0.0";
$sta['link'] = "";
$sta['hardware'] = "SDR";



$theme_switch = "light";
$weewxapi[17] = "0.6";
$weewxapi[18] = "   N/A";
$weewxapi[19] = "0.0";
$weewxapi[20] = "0.0";
$weewxapi[21] = "   N/A";
$weewxapi[25] = "22.2";
$weewxapi[26] = "22.3";
$weewxapi[27] = "12:30";
$weewxapi[28] = "-0.1";
$weewxapi[29] = "10:29";
$weewxapi[30] = "0.6";
$weewxapi[31] = "12:40";
$weewxapi[32] = "2.1";
$weewxapi[33] = "12:32";
$weewxapi[34] = "1053.2";
$weewxapi[35] = "10:06";
$weewxapi[36] = "1053.1";
$weewxapi[37] = "10:29";
$weewxapi[40] = "1.3";
$weewxapi[41] = "22.2";
$weewxapi[44] = "0.0";
$weewxapi[46] = "188";
$weewxapi[47] = "0.0";
$weewxapi[48] = "16.8";
$weewxapi[49] = "20220817123327";
$weewxapi[50] = "-3.2";
$weewxapi[51] = "20220817102959";
$weewxapi[52] = "   N/A";
$weewxapi[53] = "   N/A";
$weewxapi[54] = "16.8";
$weewxapi[55] = "20220817123327";
$weewxapi[56] = "-3.2";
$weewxapi[57] = "20220817102959";
$weewxapi[58] = "11.9";
$weewxapi[59] = "80";
$weewxapi[60] = "20220817100639";
$weewxapi[61] = "69";
$weewxapi[62] = "20220817123815";
$weewxapi[63] = "16.8";
$weewxapi[64] = "20220817123327";
$weewxapi[65] = "-3.2";
$weewxapi[66] = "20220817102959";
$weewxapi[67] = "22.1";
$weewxapi[68] = "71";
$weewxapi[69] = "16.6";
$weewxapi[70] = "   N/A";
$weewxapi[71] = "   N/A";
$weewxapi[72] = "0.6";
$weewxapi[73] = "0.6";
$weewxapi[74] = "0";
$weewxapi[75] = "0";
$weewxapi[76] = "0"; //"0";
$weewxapi[77] = "   N/A";
$weewxapi[78] = "0";
$weewxapi[79] = "   N/A";
$weewxapi[80] = "853";
$weewxapi[81] = "0 days, 0 hours, 10 minutes";
$weewxapi[82] = "   N/A";
$weewxapi[83] = "   N/A";
$weewxapi[84] = "   N/A";
$weewxapi[85] = "   N/A";
$weewxapi[86] = "22.3";
$weewxapi[87] = "20220817123027";
$weewxapi[88] = "-0.1";
$weewxapi[89] = "20220817102959";
$weewxapi[90] = "22.3";
$weewxapi[91] = "20220817123027";
$weewxapi[92] = "-0.1";
$weewxapi[93] = "20220817102959";
$weewxapi[94] = "   N/A";
$weewxapi[95] = "   N/A";
$weewxapi[96] = "2.1";
$weewxapi[97] = "20220817123251";
$weewxapi[98] = "2.1";
$weewxapi[99] = "20220817123251";
$weewxapi[100] = "   N/A";
$weewxapi[101] = "0.0";
$weewxapi[102] = "20220817100639";
$weewxapi[103] = "0.0";
$weewxapi[104] = "20220817100639";
$weewxapi[105] = "853";
$weewxapi[106] = "20220817102959";
$weewxapi[107] = "   N/A";
$weewxapi[108] = "   N/A";
$weewxapi[109] = "853";
$weewxapi[110] = "20220817102959";
$weewxapi[111] = "853";
$weewxapi[112] = "20220817102959";
$weewxapi[113] = "20220817102959";
$weewxapi[114] = "   N/A";
$weewxapi[115] = "   N/A";
$weewxapi[116] = "11.9";
$weewxapi[117] = "20220817102959";
$weewxapi[118] = "11.9";
$weewxapi[119] = "20220817102959";
$weewxapi[120] = "   N/A";
$weewxapi[121] = "   N/A";
$weewxapi[122] = "20220817124000";
$weewxapi[123] = "22.1";
$weewxapi[124] = "   N/A";
$weewxapi[125] = "22.3";
$weewxapi[126] = "20220817123027";
$weewxapi[127] = "-0.1";
$weewxapi[128] = "20220817102959";
$weewxapi[129] = "16.8";
$weewxapi[130] = "20220817123327";
$weewxapi[131] = "-3.2";
$weewxapi[132] = "20220817102959";
$weewxapi[133] = "2.1";
$weewxapi[134] = "20220817123251";
$weewxapi[135] = "   N/A";
$weewxapi[136] = "   N/A";
$weewxapi[137] = "   N/A";
$weewxapi[138] = "   N/A";
$weewxapi[139] = "1053.2";
$weewxapi[140] = "20220817100639";
$weewxapi[141] = "1053.1";
$weewxapi[142] = "20220817102959";
$weewxapi[143] = "1053.2";
$weewxapi[144] = "20220817100639";
$weewxapi[145] = "1053.1";
$weewxapi[146] = "20220817102959";
$weewxapi[147] = "1053.2";
$weewxapi[148] = "20220817100639";
$weewxapi[149] = "1053.1";
$weewxapi[150] = "20220817102959";
$weewxapi[151] = "0.0";
$weewxapi[152] = "6.4";
$weewxapi[153] = "5";
$weewxapi[154] = "67";
$weewxapi[155] = "14:32";
$weewxapi[156] = "22:29";
$weewxapi[157] = "12:28";
$weewxapi[158] = "0.2";
$weewxapi[159] = "80";
$weewxapi[160] = "20220817100639";
$weewxapi[161] = "69";
$weewxapi[162] = "20220817123815";
$weewxapi[163] = "80";
$weewxapi[164] = "20220817100639";
$weewxapi[165] = "69";
$weewxapi[166] = "20220817123815";
$weewxapi[167] = "   N/A";
$weewxapi[168] = "   N/A";
$weewxapi[169] = "   N/A";
$weewxapi[170] = "   N/A";
$weewxapi[200] = "0.4";
$weewxapi[201] = "2.1";
$weewxapi[202] = "0.0";
$weewxapi[203] = "707";
$weewxapi[204] = "70";
$weewxapi[205] = "23.8";
$weewxapi[206] = "80";
$weewxapi[207] = "20220817100639";
$weewxapi[208] = "69";
$weewxapi[209] = "20220817123815";
$weewxapi[210] = "11.9";
$weewxapi[211] = "20220817102959";
$weewxapi[212] = "853";
$weewxapi[213] = "20220817102959";
$startcivil = "1660709180.607658";
$endcivil = "1660766121.7134664";
$sunrise = "05:44:47";
$sunset = "20:17:08";
$rain_year_start = "Jan -";
$rain_year_end = "Dec";
$daymaxrainrate = "0.0";
$daymaxrainratetime = "20220817100639";
$yesterdaymaxrainratetime = "   N/A";
$alltimemaxrainrate = "0.0";
$alltimemaxrainratetime = "20220817100639";
$yesterdaymaxwind = "   N/A";
$yesterdaymaxwindtime = "   N/A";
$yesterdaymaxwindtime2 = "   N/A";
$monthmaxwind = "0.6";
$monthmaxwindtime = "20220817124000";
$monthmaxwindtime2 = "17:08";
$yearmaxwind = "0.6";
$yearmaxwindtime = "20220817124000";
$yearmaxwindtime2 = "17:08";
$alltimemaxwind = "0.6";
$alltimemaxwindtime = "20220817124000";
$alltimemaxwindtime2 = "17:08:2022";
$pm25now = "   N/A";
$pm10now = "   N/A";
$pm25avg24 = "   N/A";
$pm10avg24 = "   N/A";
//lightning for Ecowitt sensor
$lightning['light_last_distance'] = "   N/A";
$lightning['last_time'] = "";
$lightning['strike_count'] = "0";
$lightning['strike_count_3hr'] = "   N/A";


$astronomical_twighlight_begin = "03:21:49";
$nautical_twighlight_begin     = "04:19:24";
$civil_twighlight_begin        = "05:06:20";
$sun_rise 		       = "05:44:47";
$sun_meridian_transit	       = "13:01:31";
$sun_set 		       = "20:17:08";
$civil_twighlight_end 	       = "20:55:21";
$nautical_twighlight_end       = "21:41:53";
$astronomical_twighlight_end   = "22:38:36";
$sun_azimuth		       = "171.6165351990343";
$sun_alt		       = "51.26780289127674";
$sun_right_ascension	       = "146.85747475774107";
$sun_declination	       = "13.332806986241827";
$sidereal_time		       = "141.47665883665576";
$winter_solstice	       = "21/12/22 21:47:58";
$summer_solstice	       = "21/06/23 15:57:53";
$vernal_equinox		       = "20/03/23 21:24:13";
$autumnal_equinox	       = "23/09/22 02:03:31";
$total_daylight		       = "14 hours, 32 minutes, 21 seconds";
$moon_rise		       = "22:29:13";
$moon_meridian_transit	       = "05:12:44";
$moon_set		       = "12:28:54";
$moon_azimuth		       = "291.9205365979175";
$moon_altitude		       = "-1.3947932505734213";
$moon_right_ascension	       = "32.49104580808857";
$moon_declination	       = "11.412561320993413";
$new_moon		       = "27/08/22 09:17:02";
$first_quarter_moon	       = "03/09/22 19:07:40";
$full_moon		       = "10/09/22 10:58:58";
$last_quarter_moon	       = "19/08/22 05:36:02";
$moon_phase		       = "Waning gibbous";
$moon_fullness		       = "67% full";
$mercury_hlongitude	       = "239.93520184376337";
$venus_hlongitude	       = "101.86057818688111";
$earth_hlongitude	       = "324.57042543446585";
$mars_hlongitude	       = "12.293473925772007";
$jupiter_hlongitude	       = "0.0060136689029488205";
$saturn_hlongitude	       = "321.987165928097";
$uranus_hlongitude	       = "45.9703423219607";
$neptune_hlongitude	       = "353.8417475376891";
$pluto_hlongitude	       = "297.4905285453062";

$civilam = $sun['civil_twilight_begin'];

if (
    strtotime(date("G.i")) >= strtotime($civil_twighlight_begin) &&
    strtotime(date("G.i")) < strtotime($civil_twighlight_end)
) {
    $dayPartCivil = "day";
} else {
    $dayPartCivil = "night";
}
if (
    strtotime(date("G.i")) >= strtotime($nautical_twighlight_begin) &&
    strtotime(date("G.i")) < strtotime($nautical_twighlight_end)
) {
    $dayPartNautical = "day";
} else {
    $dayPartNautical = "night";
}
if (
    strtotime(date("G.i")) >= strtotime($astronomical_twighlight_begin) &&
    strtotime(date("G.i")) < strtotime($astronomical_twighlight_end)
) {
    $dayPartAstronomical = "day";
} else {
    $dayPartAstronomical = "night";
}
if (
    strtotime(date("G.i")) >= strtotime($sun_rise) &&
    strtotime(date("G.i")) < strtotime($sun_set)
) {
    $dayPartNatural = "day";
} else {
    $dayPartNatural = "night";
}
?>`

**Comment by danrhjones** [comment]
If some one has an example apache config they can paste, I can then, perhaps, determine if it's nginx or how I have set up up weather34

**Comment by danrhjones** [comment]
Update, I have tried apache and I get the same problem

Clean install, this time on ubuntu, with php 8.1

**Comment by balloonhotair** [comment]
If still getting the 500 error with w34CombinedData.php then look into the file and it includes other files, also some of the includes are at the bottom of the file.  Try loading the include files into the browser url and see if any of them give a 500 error. Also check the error log file for the web server.

**Comment by danrhjones** [comment]
I have now downgraded to php7.2 and all the files are returning a 200, however the screen is blank,

**Comment by danrhjones** [comment]
just checked, and every file is now returning a 200

**Comment by steepleian** [comment]
Sorry Dan,I have just found several of your posts which ended up in my spam folder.I have identified a problem but the annoying thing is that it does not happen all the time. Although this version is no longer in development (the new version will be called DivumWX) I am working hard to fix the problem. When ready (hopefully very soon), I will give you access to the devlopment branch so you try before I patch into the main branch.IanOn 12 Oct 2022, at 22:34, Dan Jones ***@***.***> wrote:just checked, and every file is now returning a 200—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by danrhjones** [comment]
Hi @steepleian, any news on when the new version will be released? 

Is there a repo I can watch or will it be announced in this one?

**Comment by steepleian** [comment]
Hi Dan,If you would like to email me directly on ***@***.*** I can share the progress with you. RegardsIanSent from my iPad.On 18 Dec 2022, at 22:03, Dan Jones ***@***.***> wrote:﻿
Hi @steepleian, any news on when the new version will be released?
Is there a repo I can watch or will it be announced in this one?

**Comment by steepleian** [comment]
Closed as user now satisfied with outcome
