### ISSUE TITLE
Yr.no forecast api

### ISSUE THREAD

**Issue by raffaellogalli** [steepleian/weewx-Weather34#135]
Hi,  
I know that Yr.no stopped to deliver forecast xml from their api in february 2022 and moved to a different site/format.
I see that you have included in your https://claydonsweather.org.uk/weewx/divumdev/index.php the forecast meteogram from your Yr.no in your "divumdev" folder.
Are you working on the new Yr.no api to be released in the future?
Thank you very much.

**Comment by steepleian** [comment]
Hi,Not only working on it but we have a working solution using the new API. This will be part of the next version of weewx-Weather34 which will be called DivumWX.If you wish to be involved in the development of DivumWX, please email me directly.IanSent from my iPhoneOn 18 Oct 2022, at 10:24, raffaellogalli ***@***.***> wrote:﻿
Hi,
I know that Yr.no stopped to deliver forecast xml from their api in february 2022 and moved to a different site/format.
I see that you have included in your https://claydonsweather.org.uk/weewx/divumdev/index.php the forecast meteogram from your Yr.no in your "divumdev" folder.
Are you working on the new Yr.no api to be released in the future?
Thank you very much.

**Comment by raffaellogalli** [comment]
Hi Ian,
It is a very interesting proposal.
I am working two jobs, in Italy and in the US, but I can find some time.

What are the minimum requirements (both technical and time wise) that you expect for me to help?

Thanks,
Raffaello

________
Raffaello Galli  
Direct: 917.683.1780  / 351.896.9967
Email:  ***@***.***

**Comment by Millardiang** [comment]
Hi Raffaello,
Can you email me directly please steepleian@btinternet.com
Thanks,
Ian
