### ISSUE TITLE
Have WU forecasts in weewx, get them in Weather34?

### ISSUE THREAD

**Issue by 03fatboy** [steepleian/weewx-Weather34#138]
I've got WU forecasts in weewx, how to stuff <choose you poison> to Weather34 (ugly as they maybe)

Make sense?

**Comment by Millardiang** [comment]
Sorry it does not make a lot of sense to me. Are you asking if you can use Weather Underground for your forecasts?

The default forecasts for this final version of WeeWX-Weather34 are supplied by AerisWeather as they offer a much more comprehensive and reliable service.

**Comment by 03fatboy** [comment]
https://www.aerisweather.com/account/

Under maintenance, no idea howto get and api key

**Comment by 03fatboy** [comment]
D'oh
Done, thx @Millardiang

Howto: https://groups.google.com/g/weewx-user/c/oX8QVIlYgWU
