### ISSUE TITLE
Title Change Request- Indoor Temp/Hum

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#14]
Currently, when you click on Indoor Temp value, a graph opens and shows a title of Greenhouse Temperature Humidity

As my (and likely others) indoor sensor is not in a greenhouse, could this just be titled Indoor Temperature/Humidity

**Comment by balloonhotair** [comment]
Yea that is a UK thing I think, since it has been that from the start, but you can change it by the following.
1) Put $lang['Greenhouse']              = 'Indoor';      in the file  .../languages/lang.en.php at the bottom
2) Then display the following URL ...languages/create_translations.php  Note if it works the displayed page will be blank.
3) Reload your page and you should see the change

**Comment by gary-hammer** [comment]
I'm attaching the file as edited on my server.
Here's the link I use afterwards. I do get a blank page.
[https://weather.ghammer.net/languages/create_translations.php](url)

No change, still Greenhouse.

[lang.en.php.txt](https://github.com/steepleian/weewx-Weather34/files/5704007/lang.en.php.txt)

**Comment by balloonhotair** [comment]
You need the semi-colon and the end of the line, since php is very touchy about them.

**Comment by gary-hammer** [comment]
Done, I also made the single quote a double to match the other entries.
Did the create_translations page.
ctl-f5 to clear cache in FF, still greenhouse.

**Comment by balloonhotair** [comment]
Need to see the translations.js file in the languages directory and the file /var/log/apache2/error.log

**Comment by gary-hammer** [comment]
I'm going to include the create_translations file from my server as that is what the error log points to.

[error.log](https://github.com/steepleian/weewx-Weather34/files/5704115/error.log)
[create_translations.php.txt](https://github.com/steepleian/weewx-Weather34/files/5704121/create_translations.php.txt)

**Comment by balloonhotair** [comment]
There is an error in which it looks like a $defaultlanguage is not setup in your settings1.php file. Check to see if this variable has a value.
Here is the error message that is giving this idea.
[Wed Dec 16 11:35:20.891069 2020] [php7:error] [pid 172443] [client 2601:19b:4800:de:1802:8c34:de8d:b959:60527] PHP Parse error:  syntax error, unexpected '.' in /var/www/html/weewx/weather34/languages/create_translations.php on line 1

**Comment by gary-hammer** [comment]
This is what I find in the settings1 file:
`$defaultlanguage = 'en';
$language = 'en';`

**Comment by balloonhotair** [comment]
Ok not sure what happen here but the first line in create_translations.php should be
<?php include('../settings1.php');
The version you posted is missing the single quotes. They need to be there since the file name is a string.

**Comment by gary-hammer** [comment]
Should be? I saw: `<?php
include(../settings1.php);`

And changed it to be two lines.

**Comment by balloonhotair** [comment]
Replace first line with
<?php include('../settings1.php');

**Comment by gary-hammer** [comment]
Not seeing it.
Got a file?

Don't know if you want a blank line, a dash, something else.

**Comment by balloonhotair** [comment]
<?php include('../settings1.php');
$fn = fopen('lang.'.$defaultlanguage.'.php', "r") or die("Cannot read input file "."lang.".$defaultlanguage.".php");
$rWrite = fopen('translations.js', 'w') or die("Cannot write output file ".'translations.js');
fwrite( $rWrite, "var translations = {" . PHP_EOL);
while($row = fgets($fn)) {
   if ((strpos($row, "#") == 0) && (strpos($row, "span") == 0) && (strpos($row, "=") > 0)){
      $row = str_replace(array("'", "]", ";", "\$lang["), "", $row);
      $row = str_replace("'", '"', $row);
      if (strpos($row, "//") > 0) $row = substr($row, 0, strpos($row, "//"));
      list($key, $value ) = explode( "=", $row );
      fwrite($rWrite, "'".trim($key)."': "."'".trim($value)."',\n");}}
fwrite($rWrite,"};" . PHP_EOL);
fclose( $fn );
fclose( $rWrite );
?>

**Comment by balloonhotair** [comment]
[create_translations.php.txt](https://github.com/steepleian/weewx-Weather34/files/5705245/create_translations.php.txt)

**Comment by gary-hammer** [comment]
Gosh, look at that!

Thanks. Sorry for being dense on the blank line.

**Comment by balloonhotair** [comment]
If you change the translation in lang.en.php from "Indoor" to 'Indoor' you will get rid of all the quotes around Indoor.
Just thought you may like it without any quotes around the word Indoor.

**Comment by gary-hammer** [comment]
Ha!
I noticed that myself.

As soon as I'm finished preparing for the snow storm, I'll settle in with
the computer and some hot coffee.

Then I can edit the file and now what we did.

**Comment by steepleian** [comment]
Greenhouse has been removed from the next version of weewx-Weather34
