### ISSUE TITLE
NWS in weather advisory?

### ISSUE THREAD

**Issue by 03fatboy** [steepleian/weewx-Weather34#140]
Can NWS advisory here in US get scraped?

Perhaps I simply missed it in the docs.

Thanks!

**Comment by steepleian** [comment]
Hi,There was a textual based advisory for the US included at one time. The data for this was supplied by DarkSky which no longer has a public API. I am fairly sure that AerisWeather carries advisory data for the US and you should be able to retrieve this by setting up a web service for it in weewx.conf.Although we are no longer developing the current weewx-Weather34 as we are working on its successor at this very moment, I am prepared to look at this for you as it is relevant to the new version. If you can let me no your coordinates, I can check what data is available from AerisWeather at your location.RegardsIanSent from my iPhoneOn 24 Dec 2022, at 23:41, 03fatboy ***@***.***> wrote:﻿
Can NWS advisory here in US get scraped?
Perhaps I simply missed it in the docs.
Thanks!

**Comment by 03fatboy** [comment]
Yep, have Aeris all setup, no advisories last week.

What stage is the new version at?

**Comment by steepleian** [comment]
I have found some data now so will use this as a basis for developing the scripts.The new version is progressing. You can see how far if your go to my website: -https://Claydon weather.org.ukSent from my iPad.On 26 Dec 2022, at 07:05, 03fatboy ***@***.***> wrote:﻿
Yep, have Aeris all setup, no advisories last week.
What stage is the new version at?

**Comment by steepleian** [comment]
NWS advisory fixed.
All the files that need to be added or updated are in the www folder of the repository and are marked NWS in the status column.
Make sure that $position4 in settings1.php is set to “top_advisory_nws.php”
Make sure awa is set in the web services section of weewx.conf and restart.

Example of popup window for NWS advisory
![2DFCF442-E59E-40A9-B7B2-18A1FB8EF0B3](https://user-images.githubusercontent.com/18438654/209726173-31bfca05-a744-4850-837b-d3666318df4e.jpeg)
