### ISSUE TITLE
forecast3aw.php, forecast3awlarge.php

### ISSUE THREAD

**Issue by jfwjfw** [steepleian/weewx-Weather34#143]
Both forecast3aw.php and forecast3awlarge.php have calls to pop_menu_forecast_alt.php, which does not exit, should be changed to pop_menu_forecast.pop

**Comment by secstwice** [comment]
I just came here looking for the same issue

**Comment by Millardiang** [comment]
Thank you for reporting. Link in index.php corrected and bumped to 4.3.1
