### ISSUE TITLE
site looks incorrect

### ISSUE THREAD

**Issue by gitty85** [steepleian/weewx-Weather34#144]
Hi,
I have installed the latest version but the images look very different from: https://claydonsweather.org.uk/ have I done something incorrectly. I have updated from an older version so it could be that. However I did remove the weather34 directory before installing.

![image](https://user-images.githubusercontent.com/29286698/227775238-c71e85c2-6dd8-4ebc-990e-3fb1b23eb905.png)

Any help/advice appreciated.

Thanks

**Comment by Millardiang** [comment]
No you have done nothing wrong. You have installed correctly the final version of weewx-Weather34. What you are viewing on my website is its successor which will be known as DivumWX. Although the dashboard format will be familiar, underneath is a complete re-write of the legacy code, new graphics, a greater integration with WeeWX, enhanced setup process and a much improved user admin interface for setting your own preferences both for DivumWX and WeeWX. I have a small team working with me on the development of DivumWX which is in early Alpha phase at the moment. If you interested in contributing either as a coder or tester please contact me at steepleian@btinternet.com
