### ISSUE TITLE
w34CombinedData.php Does not seem to handle missing sensors

### ISSUE THREAD

**Issue by EmeraldMu** [steepleian/weewx-Weather34#145]
Caveat: I have little knowledge of the platform and this is based on what fault-finding I could do only with my setup.
Weather Hardware: Weather station from DFRobot
Computer Hardware: Raspberry Pi
WeeWX Version: 4.10.2
OS: Raspbian 10 (like debian Buster)

**Symptom**
Blank screen
**Issue**
Lines 509 and 510 of w34CombinedData.php will not parse because of a data type error.
This is presumably because I don't have internal air temp/humidity sensors.
Commenting out these two lines allows something to be shown, however many other undefined variables are then shown _although this could be my installation, so I will follow this up if it is unrelated._

**Comment by Millardiang** [comment]
You can comment out those two lines using //

**Comment by EmeraldMu** [comment]
I have done this already (this is how I diagnosed line 510). However, as a "solution" it lacks elegance and is far from robust. 
I do not know enough about PHP to be able to code a solution, but I would recommend that (in Python terms) there should be implemented a try-except function for variables to be encoded. If that fails, an error/log can be made but it will not cause the sequence to fail.

**Comment by Millardiang** [comment]
w34CombinedData.php in repository updated to a more elegant solution. 

This is the final version of weewx-Weather34. It is being superseded by weewx-DivumWX. See https://claydonsweather.org.uk to view an Alpha phase build.
