### ISSUE TITLE
earthquakereport.com no longer available

### ISSUE THREAD

**Issue by Damien0505** [steepleian/weewx-Weather34#147]
Hi Ian,

I recently noticed that the earthquake data was no longer updating.
On the setting page it states that it is using earthquakereport.com which now appears to be defunct.

Have been trying to investigate where and how it pulls the earthquake data in, but I am pretty much at a loss.

Kind regards,
Damien

**Comment by Rayvenhaus** [comment]
Good morning Damien,
    The Weather34 skin gets its earthquake data from https://www.seismicportal.eu/, which is most definitely online, and based on several factors such as lat, long, distance, etc. Can you please give a few more insights as to what the issues appear to be, log files, errors, etc., to help us help you?
    Please note that Weather34 is EOL (End Of Line), and we are furiously working on a completely rewritten, more modern replacement that is currently in Alpha. Any efforts here will be best effort only, and only bug fixes will be addressed.

**Comment by Damien0505** [comment]
Good afternoon,
My apologies, I was only going by what is on the settings page.  and you are correct, https://www.seismicportal.eu/ is definitely available. 

My instance of Weather34 appeared to stop pulling earthquake data on 3/3/23.

Based on the URL within my weewx.conf,  **https://www.seismicportal.eu/fdsnws/event/1/query?limit=50&lat=-37.650916&lon=145.512319&maxradius=10000&format=json&minmag=2** , I am receiving the following error:

**Error 400: 1 validation error for Request
query -> maxradius
  ensure this value is less than or equal to 180.0 (type=value_error.number.not_le; limit_value=180.0)

Request:
http://ws2/fdsnws/event/1/query?limit=50&lat=-37.650916&lon=145.512319&maxradius=10000&format=json&minmag=2

Request Submitted:
2023-05-29T07:14:14.361

Service version:
fdsnws-event: v 1.2.1**

I'm not sure if this is due to a change in the seismicportal API or not.....  
I've manually reconfigured the maxradius value to the limit of 180 and it now appears to be working.

Attempting to generate a new services.txt file, I see that the maxradius of 1000 is coming from there.

Kind regards,
Damien

(P.S.  Looks like you may have been a few kms closer to last night rumble than I!)

**Comment by Rayvenhaus** [comment]
You're correct, currently, the max raxius element should be 180. I've corrected the generator page to reflect that now.

Great catch!

**Comment by Damien0505** [comment]
Strange how it had worked previously!  Anyway many thanks!
