### ISSUE TITLE
Earthquake Alert won't show 8

### ISSUE THREAD

**Issue by ijg1963** [steepleian/weewx-Weather34#149]
Just playing around with code and realized the eq notification will never show an 8.  Not that we want to see it but it does 4 below, 5 below, etc to 8 below and then 8 above.  But never 8.

There's also a folder called 'metar' which calls on the jsondata file, but it doesn't go up a level to get it, so it would never see it.

ig.
http://ajaxweather.com
Ontario, Canada

**Comment by Rayvenhaus** [comment]
Thank you for catching this, however, Weather34 is EOL at this time. We are working hard for the replacement, DivumWX and expect to be at closed beta very soon. We will double-check to ensure that the same issue does not appear there as well.

**Comment by Millardiang** [comment]
Fixed in commit 5eba717
