### ISSUE TITLE
No such column error

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#15]
Hi there,

I tried to upgrade to the latest version of the skin today and have run into a few problems.

First, the archivedata.php file is not generating.  It is complaining that there are no pm2.5/pm10 etc columns in the database so is refusing.

Here is the log:

error	19:30:22.904164-0700	Python	no such column: pm2_5 in "SELECT avg(pm2_5) FROM archive WHERE dateTime > 1587868200 AND dateTime <= 1587954600 AND pm2_5 IS NOT NULL"
default	19:30:22.904539-0700	Python	cheetahgenerator: Generate failed with exception '<class 'weedb.NoColumnError'>'
default	19:30:22.904747-0700	Python	cheetahgenerator: **** Ignoring template /Users/Shared/weewx/skins/Weather34/archivedata.php.tmpl
default	19:30:22.904777-0700	Python	cheetahgenerator: **** Reason: no such column: pm2_5
error	19:30:22.966469-0700	Python	no such column: uva in "SELECT dateTime, uva, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.966603-0700	Python	no such column: uvb in "SELECT dateTime, uvb, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.966677-0700	Python	no such column: uvaWm in "SELECT dateTime, uvaWm, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.966742-0700	Python	no such column: uvbWm in "SELECT dateTime, uvbWm, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.966804-0700	Python	no such column: full_spectrum in "SELECT dateTime, full_spectrum, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.966866-0700	Python	no such column: lux in "SELECT dateTime, lux, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.966926-0700	Python	no such column: infrared in "SELECT dateTime, infrared, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.966984-0700	Python	no such column: pm2_5 in "SELECT dateTime, pm2_5, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"
error	19:30:22.967042-0700	Python	no such column: pm10_0 in "SELECT dateTime, pm10_0, usUnits, `interval` FROM archive WHERE dateTime >= ? AND dateTime <= ?"

There are some other issues around changes with how it addresses settings1.php which might be making it hard to host the web files remotely, but I'd like to focus on this issue first.

Thanks for your help and work on this!

Chris

**Comment by steepleian** [comment]
archivedata.php.tmpl updated
