### ISSUE TITLE
Rsync tries to sync data even when unconfigured

### ISSUE THREAD

**Issue by kamiKAC** [steepleian/weewx-Weather34#15]
I found strange beahaviour of weather34 extension causing fail2ban on web server to ban my weewx server.

Even without any configuration of realtime sync (I have cron job for this) weather34.py tries to sync w34realtime.txt file using rsync with default user on remote machine (which is root as weewx runs as root). I have configured another user for transfer on remote machine so connection with public key for user root fails. At the same item I have RSYNC skin configured for this user and this one works fine until fail2ban bans my weewx server.

My config for w34realtime sync:
```
[Weather34RealTime]
    filename = /var/www/html/w34realtime.txt
    unit_system = METRICWX
    exclude_fields = rain
    cache_enable = True
    cache_directory = /tmp
    cache_stale_time = 900
    weewx_port = 25252
    webserver_address = ""
    weewxserver_address = ""
    weewx_file_transfer = ""
```
Error I got in errorlog:
```
Aug 30 23:39:38 PiWerki weewx[4004] ERROR weeutil.rsyncupload: [['rsync', '--archive', '--stats', '-e ssh', '/var/www/html/w34realtime.txt', '10.8.0.1:/var/www/html/w34realtime.txt']] reported errors: ssh: connect to host 10.8.0.1 port 22:
Connection refused. rsync: connection unexpectedly closed (0 bytes received so far) [sender]. rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.3]
```
I can see one issue and one improvement request here:
Disable rsync when weewx_file_transfer is not defined.
Add "user" parameter to [Weather34RealTime] stanza so rsync can connect with different credentials than root.

Another thing is that 10.8.0.1 is resolved from domain name in this case while Rsync skin invokes rsync with domain name.

**Comment by balloonhotair** [comment]
Hi,
The current version in development has the ability to use the config field "user" in the RSYNC section of the weewx.conf for the user name for rsyncing.
The weewxserver_address field in the weewx.conf under w34Realtime can be used to override the ip address that weather34.py figures out.
Rsync is only active if the weewx_file_transfer is set to "rsync" or if the machine making the connection ip's address is different than the host ip address.  When the file to transfer field is blank then weather34.py does no transfers since it expects the webserver and the weex machine are the same machine. If this the case and the code got the wrong host ip address then using the weewxserver_address should disable rsync if the two addressing match. (weewx machine, websever machine on the same box)

**Comment by kamiKAC** [comment]
Hi
Thanks for extensive explanation. I've replaced weater34.py with the one from development branch and now w34realitme.txt is properly synced as user value is used to access remote machine. I had no time for tests with empty filename value but suspect it works as you stated.
One more question: Is this necessary to try to sync ~/weather34/serverdata folder as it's empty in my case?
My config looks like this:
```
[Weather34RealTime]
    filename = /var/www/html/w34realtime.txt
    unit_system = METRICWX
    exclude_fields = rain
    cache_enable = True
    cache_directory = /tmp
    cache_stale_time = 900
    weewx_port = 25252
    webserver_address = "my_webserver.com"
    weewxserver_address = "my_weewx.lan"
    weewx_file_transfer = "rsync"
    user = myuser
```
I can see in log:
```
Aug 31 22:02:24 PiWerki weewx[10987] INFO weeutil.rsyncupload: rsync'd 1 files (286 bytes) in 5.36 seconds
Aug 31 22:02:24 PiWerki weewx[10987] INFO weeutil.rsyncupload: rsync'd 0 files (0 bytes) in 5.47 seconds
Aug 31 22:02:29 PiWerki weewx[10987] INFO weeutil.rsyncupload: rsync'd 1 files (286 bytes) in 5.59 seconds
Aug 31 22:02:29 PiWerki weewx[10987] INFO weeutil.rsyncupload: rsync'd 0 files (0 bytes) in 5.58 seconds
```
First one is sync of w34realitme.txt file, second one is empty ~/weather34/serverdata/ folder

Best Regards

**Comment by balloonhotair** [comment]
Hi,
The serverdata folder should not be empty since this is where w34realtime.txt, archivedata.php,weexserverinfo, airquality.php. files now live. But since you only copied weather34.py file you only got part of the changes.  So in a way all bets are off, and happy it has not broken.

**Comment by kamiKAC** [comment]
Hi
OK. I'll wait until all changes go to master branch and then everything should work as expected.
Once again, thanks.

Best Regards
