### ISSUE TITLE
Debian 12 nope..

### ISSUE THREAD

**Issue by jult** [steepleian/weewx-Weather34#150]
```
# pip3 install ephem
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

Funny how your own site shows it's running bookworm, yet the installation guide fails using it..

**Comment by Rayvenhaus** [comment]
The site you are referencing, which I assume is this one, [Claydon's Weather](https://claydonsweather.org.uk/), is running, as shown below, DivumWX version 0.6.6 ALPHA on Debian 12 (bookworm).
![2023-08-07 07_07_22-NVIDIA GeForce Overlay](https://github.com/steepleian/weewx-Weather34/assets/4164076/de687c95-df82-4910-ad05-c16558b26392)

DivumWX is the completely rewritten replacement for Weather34, and Weather34 is no longer being developed and is being supported only for bug fixes and security issues.

I am sorry that you are experiencing an issue with your site and the pip installation of ephem on what I assume is a Debian Bookworm externally managed site, however, that is not a Weather34 issue.

Thank you for your input and I hope that you are able to resolve your issue.

**Comment by jult** [comment]
OK, so why did the DivumWX running website get me to the wrong codebase? Something's not clear there. The info on the github page with this code says it's used on that website.

What is it with weewx and the people using it? Seems like none of them have proper documentation skills. I'm not an idiot in IT, but every damn part or skin or driver for weewx ends up being a huge can of worms having been opened. Either people have to run docker instances that fail to operate, or aren't updated, or if they're not, they're supposed to run the latest version of weewx, but if they do it suddenly requires deviating config from what it says on the weewx website. And now with debian 12 it looks like none of the related websites is up to date about anything. This is not just the normal 'open source' issues, or because it's free, it's damn near impossible to find a decent write-up for an up to date distro with weewx and the currently sold weather stations. I'll see what I can do, but it all starts with the weewx conf itself being amazingly strange in how it's designed.

**Comment by Rayvenhaus** [comment]
I am sorry that you are having issues. The fact that one of the sites running an Alpha version of DivumWX and points you to the previous version of that skin may be a tad misleading, but we do not point you to the current repo as it is closed and private whilst we working on getting it to a closed beta.

Concerning the state of weewx and your displeasure with anything else concerned with it, I am also truly sorry that you are having so many issues, especially concerning the newest release of debian. The vast majority of the people who maintain these things are just hobbyists and do this when they may have a spare moment between work, family and friends, and whatever else life throws at them.

May I suggest that if you find a problem with something, jump in and assist in fixing the issue?  May you have fair winds and following seas, my friend.

**Comment by Millardiang** [comment]
A status update has been added.

 Weather34 skin for WeeWX

# Please note. This skin for WeeWX has reached end of life status. It will be maintained for bug fixes only until its successor, weewx-DivumWX, currently approaching Beta testing, achieves launch status. The new version will be called weewx-DivumWX and will be compatible with Debian 12 and the forthcoming WeeWX version 5. A demonstration of weewx-DivumWX can be seen at https://claydonsweather.org.uk
 
# This version has only been tested with versions of Debian 11 and below. There are no guarantees that it will work with later versions of Debian, or versions of WeeWX beyond 4.10.2.
