### ISSUE TITLE
When will you open up weewx-DivumWX written for WeeWX 5 for testing?

### ISSUE THREAD

**Issue by G400** [steepleian/weewx-Weather34#151]
I admire you work and I'm looking forward to see if I can use your teamplate!
When will you open up weewx-DivumWX written for WeeWX 5 for testing?

**Comment by Rayvenhaus** [comment]
Of course, the standard answer is "when it's ready"  :)   However, it is in closed beta now, and fast approaching open beta.  We are at internal version 0.8.20dev right now. Don't worry mate, we're ramping up to get the beta open to the public.

**Comment by steepleian** [comment]
Hi G400,It depends on your skill level at the moment. We have a working template using WeeWX version 5 (WeeWX installed by pip which is all we will support going forward).I am opening up a Telegram group in addition to our Telegram Development group to allow users with suitable skill levels to start using DivumWX.So is what is required?WeeWX version 5.0.0rc3 installed by pip into a virtual environment as per the WeeWX version 5 documentation.Able to install DivumWX manually in advance of our new install tools being ready.If you fit the bill, I am happy to give you access to the Telegram DivumWX Beta Testing Group.Regards,Ianhttps://claydonsweather.org.ukOn 12 Jan 2024, at 09:16, G400 ***@***.***> wrote:﻿
I admire you work and I'm looking forward to see if I can use your teamplate!
When will you open up weewx-DivumWX written for WeeWX 5 for testing?

**Comment by G400** [comment]
Hi Ian,
Thank you for reaching out!
It looks like I have the required skills.
I have already installed WeeWX version 5 and updated to latest release candidate (3) in my Ubuntu 22.04 test environment.
Regarding ability to perform DivumWX manual installation, it is hard to tell as it might depend on the level of documentation details provided.

All in all, I’m interested in making a try and see how it goes.
For sure, I will not bother you and your team with basic questions.

Med vennlig hilsen
Kjell Inge Meisal

**Comment by G400** [comment]
Hi,
Do you have any updtaes regarding availablility of DivumWX?
Regards
Kjell Inge

**Comment by steepleian** [comment]
I am looking for one more person for a pre beta test before we go public. Email me directly if you wish to be that person:-)https://claydonsweather.org.ukOn 30 Jan 2024, at 13:00, G400 ***@***.***> wrote:﻿
Hi,
Do you have any updtaes regarding availablility of DivumWX?
Regards
Kjell Inge

**Comment by G400** [comment]
Hi,
I'm interested in becoming a beta tester.

What will be expected from me?

Med vennlig hilsen
Kjell Inge Meisal

**Comment by steepleian** [comment]
https://claydonsweather.org.ukOn 30 Jan 2024, at 14:05, G400 ***@***.***> wrote:﻿
Hi,

I'm interested in becoming a beta tester.



What will be expected from me?



Med vennlig hilsen

Kjell Inge Meisal



From: Ian Millard ***@***.***>

Sent: tirsdag 30. januar 2024 14:32

To: steepleian/weewx-Weather34 ***@***.***>

Cc: Kjell Inge Meisal ***@***.***>; Author ***@***.***>

Subject: Re: [steepleian/weewx-Weather34] When will you open up weewx-DivumWX written for WeeWX 5 for testing? (Issue #151)



Please be cautious

This email was sent outside of your organisation

________________________________

I am looking for one more person for a pre beta test before we go public. Email me directly if you wish to be that person:-)https://claydonsweather.org.ukOn 30 Jan 2024, at 13:00, G400 ***@***.***<mailto:***@***.***>> wrote:﻿

Hi,

Do you have any updtaes regarding availablility of DivumWX?

Regards

Kjell Inge

**Comment by steepleian** [comment]
Can you email me directly please steepleian@btinternet.com
