### ISSUE TITLE
Cloud Cover Percentage / Stop Reporting

### ISSUE THREAD

**Issue by MauroSwiss88** [steepleian/weewx-Weather34#16]
Hi!

I'm opening this issue thread because since a few days I've noted that the cloud cover percentage displays 0% every 10 minutes, interspersed with the real percentage value of the currently cloud cover. This is an example to get the error tho know:

![Schermata 2020-12-16 alle 10 33 57](https://user-images.githubusercontent.com/64233475/102330859-5d66ff80-3f8a-11eb-9f17-7b2f3556b725.png)

I really don't know what could happen because it worked fine.

The second issue I want to report is that since two weeks, Weewx stops to report and upload my files after an interval of 7/8 hours. If I restart it, everything works normally how before, but after the same interval hours, it stops again. What could it be?
I've tried to get some information from the syslog, but there is nothing related to this.

Thank you in advance!

Mauro

**Comment by balloonhotair** [comment]
Without any additional info or syslogs these are just guesses.
1) The cloud cover relies on a third party system that has its ups and downs, so suspect that is why you see this.
2) Sounds like a weewx issue why do you think it is a weather34 issue?

**Comment by MauroSwiss88** [comment]
1. Ups and downs since two weeks? 
2. I think it’s a Weather34 issue because it happens since I refreshed the skin with the last commits did by Ian.

I will post a log as soon as I can

Greetings

**Comment by MauroSwiss88** [comment]
> Without any additional info or syslogs these are just guesses.
> 
> 1. The cloud cover relies on a third party system that has its ups and downs, so suspect that is why you see this.
> 2. Sounds like a weewx issue why do you think it is a weather34 issue?


This is a parte of the log with the Cloud Cover:

Dec 16 17:38:03 raspberrypi weewx[15169] DEBUG user.weather34: CloudCover url1 exit code 0
Dec 16 17:38:05 raspberrypi weewx[15169] DEBUG user.weather34: CloudCover url2 exit code 0
Dec 16 17:38:05 raspberrypi weewx[15169] DEBUG PIL.PngImagePlugin: STREAM b'IHDR' 16 13
Dec 16 17:38:05 raspberrypi weewx[15169] DEBUG PIL.PngImagePlugin: STREAM b'gAMA' 41 4
Dec 16 17:38:05 raspberrypi weewx[15169] DEBUG PIL.PngImagePlugin: STREAM b'pHYs' 57 9
Dec 16 17:38:05 raspberrypi weewx[15169] DEBUG PIL.PngImagePlugin: STREAM b'IDAT' 78 65458
Dec 16 17:38:05 raspberrypi weewx[15169] DEBUG PIL.Image: Error closing: 'Image' object has no attribute 'fp'

**Comment by balloonhotair** [comment]
Yep that look like the file from the third party system is bad.

**Comment by MauroSwiss88** [comment]
But it happens only with my website, not on others that I saw having the same skin. Do you have any suggests?

**Comment by balloonhotair** [comment]
There should be two png files in the /tmp directory called sat1.png, sat2.png you can look at them to see if they good images and that the date stamp is changing., but based on what you sent above looks like the files are corrupt. 
Also the different sat files are created for different parts of the world so a UK file can be good but a EU file can be bad.

**Comment by MauroSwiss88** [comment]
I will have a look if something changes in the. est days. Thank you for your help!

**Comment by balloonhotair** [comment]
How often are you getting the images? If it is very often that may have a limit on the number of times a download can be done. The default for the config entries is every 5 minutes (300 seconds). Have you changed this?

**Comment by MauroSwiss88** [comment]
It’s still set to default, I’ve never changed it. Maybe I have to try to set the interval higher?

**Comment by MauroSwiss88** [comment]
Hi Jerry,
in conclusion I can tell you that the images are not corrupt, neither I have changed the times of download.
Maybe it is a Python problem (DEBUG PIL.Image: Error closing: 'Image' object has no attribute 'fp')

Greetings

**Comment by balloonhotair** [comment]
There are posts on the internet about PIL Image throwing the last error. No solutions though. What version of python are you using? I would change the interval to 30 minutes (1800) to see if anything changes.

**Comment by MauroSwiss88** [comment]
Yes, I saw different posts too, but sincerely I don't understand them to move on the problem itself.
I changed the interval to 30 minutes. I will observe and get back to yo.

**Comment by MauroSwiss88** [comment]
Even I changed the interval to 30 minutes, on the syslog I can see the engine still asking for Cloud Cover every 5 minutes.

**Comment by balloonhotair** [comment]
If you changed the interval you need to restart weewx.

**Comment by MauroSwiss88** [comment]
I’ve first restarted weewx and then tried a completely system reboot. Nothing is changed.

**Comment by balloonhotair** [comment]
So the interval is changed in weewx config and there was a restart. This means that the the third party system is now being accessed every 30 minutes, but the updates to the chart will still be at archive interval which is 5 minutes and that is fine. This just proves that the error is not in the files but in the PIL or Python software. It would be nice to see what version of python you are running. If you went to a terminal window and type python it will tell you the python version. also if you did a pip -l in a terminal window it will list all the versions of what is install. Be curious what version of PIL you are using.

**Comment by balloonhotair** [comment]
There is a new weather34.py in the release area that closes an open file handler if the PIL operation fails. 
The file is in the skins directory. Since you are having a lot of issues with PIL you should use this file. It does not fix the PIL error but will prevent file handlers from being left un-closed.

**Comment by MauroSwiss88** [comment]
Hello Jerry!

This is the python version I have: Python 2.7.16 (default, Oct 10 2019, 22:02:15) 

If I do pip -l it charges and charges, but nothing is showed.

I have released the weather34.py file with the last commit, It seems to be great with the cart, but I will definitely check it during this evening if there are any 0% on it.

**Comment by balloonhotair** [comment]
the pip command is **pip list**  I gave you my version of pip list command which only runs in my env.
So nothing in the code changed to prevent the 0%. If you still get them the choices I see are updating PIL or installing Pillow, or having the code loop a couple of times to see if it can get a result that is not 0%. This last suggestion would be a one off code change for your setup.

**Comment by MauroSwiss88** [comment]
Hi Jerry,
this is my pip list:

Package           Version    
----------------- -----------
arandr            0.1.9      
asn1crypto        0.24.0     
automationhat     0.2.0      
blinker           1.4        
blinkt            0.1.2      
buttonshim        0.0.2      
Cap1xxx           0.1.3      
certifi           2018.8.24  
chardet           3.0.4      
Click             7.0        
colorama          0.3.7      
colorzero         1.1        
configparser      3.5.0b2    
cookies           2.2.1      
cryptography      2.6.1      
drumhat           0.1.0      
entrypoints       0.3        
enum34            1.1.6      
envirophat        1.0.0      
ExplorerHAT       0.4.2      
Flask             1.0.2      
fourletterphat    0.1.0      
funcsigs          1.0.2      
gpiozero          1.5.1      
gyp               0.1        
idna              2.6        
ipaddress         1.0.17     
itsdangerous      0.24       
Jinja2            2.10       
keyring           17.1.1     
keyrings.alt      3.1.1      
MarkupSafe        1.1.0      
mcpi              0.1.1      
microdotphat      0.2.1      
mock              2.0.0      
mote              0.0.4      
motephat          0.0.3      
numpy             1.16.2     
oauthlib          2.1.0      
olefile           0.46       
pantilthat        0.0.7      
pbr               4.2.0      
phatbeat          0.1.1      
pianohat          0.1.0      
picamera          1.13       
picraft           1.0        
piglow            1.2.5      
pigpio            1.44       
Pillow            5.4.1      
pip               18.1       
pycairo           1.16.2     
pycrypto          2.6.1      
pyflakes          2.0.0      
pygame            1.9.4.post1
PyGObject         3.30.4     
pyinotify         0.9.6      
PyJWT             1.7.0      
pyOpenSSL         19.0.0     
pyserial          3.4        
pyxdg             0.25       
rainbowhat        0.1.0      
requests          2.21.0     
requests-oauthlib 1.0.0      
responses         0.9.0      
RPi.GPIO          0.7.0      
RTIMULib          7.2.1      
scrollphat        0.0.7      
scrollphathd      1.2.1      
SecretStorage     2.3.1      
sense-emu         1.1        
sense-hat         2.2.0      
setuptools        40.8.0     
simplejson        3.16.0     
six               1.12.0     
skywriter         0.0.7      
sn3218            1.2.7      
spidev            3.4        
touchphat         0.0.1      
twython           3.7.0      
unicornhathd      0.0.4      
urllib3           1.24.1     
Werkzeug          0.14.1     
wheel             0.32.3 

I checked the cloud cover chart now and I definitely get the 0% every 10 minutes. 
If I understood you well, I have to update PIL or installing Pillow?

Is there any possibility that I get this 0% because my data logger of the Davis seems to be near to "die"?
Since a couple of days, I always get CRC Errors 4 times in a row.

**Comment by balloonhotair** [comment]
So you have Pillow install which is better that Pil, since Pillow contains PILL. You can see if you have the latest version of Pillow..
As a general rule I do not tell users to install/upgrade software since there seems to be unwanted side effects, but it may fix the issue.

**Comment by MauroSwiss88** [comment]
Hi Jerry,
I've tried to disable all the web services to look if something changes with the CRC Errors of the data logger (what maybe cause the crash of my weewx on regular intervals). I restarted Weewx 30 minutes ago and saw that at the moment I'm not getting the mentioned errors as before. Maybe I have a problem with only the web services? How can I do a "clean" reinstall of the skin without loosing my changes?

I did an upgrade/update of the system. I could check what happens if I active the services one at a time.

Greetings

**Comment by balloonhotair** [comment]
There is no way to do a clean install without losing changes with any software. By definition clean install means loose all changes. Also do not expect a reinstall to change anything. You can enable one service at a time using the config entry services and just remove one service at a time. Note using just 30 minutes as a test interval is way to short to be sure on anything base on the problem you are trying to solve.

**Comment by balloonhotair** [comment]
Another note the earthquake reporting site has been offline for a couple weeks now. So I would remove the eq service from the services list, in case that is causing any issues.

**Comment by MauroSwiss88** [comment]
Hi Jerry,
thank you for information. I think my main problem is still the data logger that seems going to abandon me.
I always get the CRC Errors and after disabling two of the web services, of course I got my weewx to work for more hours, but in the end it shuts down anyway. I've already tried to clear the memory of the data logger itself, without success.

**Comment by balloonhotair** [comment]
Just a FYI my memory usage would climb very slowly when I had that dead service active, hoping the service would start back up. So far it has not started back up. Since I stop using the earthquake service my memory usage has stop climbing.

**Comment by MauroSwiss88** [comment]
I have the CRC errors even if I disable every web service, so I'm thinking my data logger is really going to "die".

**Comment by balloonhotair** [comment]
So I have verified on my python 2.7 system that there is a internal memory leak within python urlopen when trying to access the website earthquake-report.com which is currently down. To stop the memory leak remove eq from the services list in the weather34Realtime section. A code change to weather34.py in dev branch was made to stop the memory leak, but cannot prevent it since it an internal python leak.

**Comment by MauroSwiss88** [comment]
Witch code change do you mean to weather34.py?

**Comment by balloonhotair** [comment]
The code change is in dev only. All you have to do is remove eq from the services list as described above and that will stop the memory leak.  The earthquake-report site is down.

**Comment by MauroSwiss88** [comment]
Two days ago, I removed all web services and I didn't get any memory leaks of the logger and the cloud cover percentage didn't show 0% as well. Now that I have activated me, al and wu again, I get the same problems I had before with memory leaks.  Strange, very strange,

**Comment by balloonhotair** [comment]
I run with those services and have python2.7 without any leaks.  The only issue I see is with eq since the service hangs. I would suggest for now run without services and wait for the next release of template, or look into migrating to python 3.5.

**Comment by MauroSwiss88** [comment]
I have python2.7 too, so I don't have any ideas, but since I hadn't the problem with all web services switched off, I don't think my data logger is main problem

**Comment by steepleian** [comment]
There was a problem with sat24.com service which is now working correctly again in Europe. In other locations, if you experience problems, change the setting to 'false' in weewx.conf and the line will be removed automatically from the current conditions display module.
