### ISSUE TITLE
Installer Does Not Respect Different Paths

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#16]
I installed the current version onto my server yesterday.
It did not go well as the installer did not ask for anything but the weewx.conf path.
I use Pop!OS 20.04, Python3, WeeWX 4.1.1, weewx is installed to /home/weewx and my web directory is /home/weewx/public_html

I currently have the Belchertown skin output to and served from /home/weewx/public_html/weather
The url used for that is https://ghammer.net/weather

So, I installed and found that all is under /var/www/html/weewx/weather34
I edited all files to reflect the desired path and restarted the machine.
I get this from the logs, note that some fail looking for the /www path while others fail looking for /home/weewx/public_html paths.

I'm happy to make edits, happy to test changes. I'd just like to get this working on my server without having to reconfigure apache2 as I have other some other websites being served from this machine and URLs have been indexed/published/linked for years.

I do have CumulusMX and CumulusMX HWS running well on a test server, but WeeWX is my PWS software.

[logs.txt](https://github.com/steepleian/weewx-Weather34/files/5188981/logs.txt)

**Comment by balloonhotair** [comment]
So couple of things. The installer does not ask for the path of the weewx.conf, are you referring to the install conf?
Next you do not state which conf you used but assume it was setup.py based on the path you are talking about.
To put the install in a different location just make a copy of setup.conf (if that is what you used) with a different name in the directory where setup.conf exists and edit the copy and change the path weather34 to the path you want it to be. Then run the installer again and your new conf file will show up in the list to choose from. Also after making the changes do a diff of the two files to make sure your changes were what was expected.

**Comment by gary-hammer** [comment]
Thanks, off to give this a try.

**Comment by balloonhotair** [comment]
Without seeing the changes to the conf file that was made my guess on the output posted you put a path that is webserver based and not file system based. This is not a complete path     public_html/weather    probably missing /var/www/..... in front of it. All the paths in the config are full paths that can be validated with a ls -l command. Hope this helps.

**Comment by balloonhotair** [comment]
Correction /var/www  should be /home/weewx

**Comment by gary-hammer** [comment]
Today, I installed WeeWX and the Ecowitt driver on my test machine and configured fresh.
Works a treat installed this way. Impossible for me to get this installed to run in my existing folder structure.
Minor edits to the weewx.conf before the install, mainly changing the HTML_ROOT to be /var/www/html

Now, off to the actual server and see what I will need change for apache to server /var/www/html/weewx/weather34 as a new site.
