### ISSUE TITLE
Current Conditons - Max Wind problem

### ISSUE THREAD

**Issue by Drealine** [steepleian/weewx-Weather34#16]
Hi @steepleian,

On Current Conditions, max wind is not correct.

**Comment by Russell797** [comment]
To me the value should reflect the max wind gust over the past 10 minutes. Since my archive interval is 10 minutes, calling-    

$weewxapi[40] = "$current.windGust.format(add_label=False, $localize=False)"; 

in file archivedata.php.tmpl  works for me. Then in currentconditionsw34.php:

<?php //weather34 average station data
echo "Average <oorange>Temperature</oorange> last 60 minutes ";if($weather["temp_avg"]>=20){echo "<oorange>" .$weather["temp_avg"]."</oorange>°<valuetext>".$tempunit;} else if($weather["temp_avg"]<=10){echo "<oblue>" .$weather["temp_avg"]."</oblue>°<valuetext>".$tempunit;}else if($weather["temp_avg"]<20){echo "<ogreen>" .$weather["temp_avg"]."</ogreen>°<valuetext>".$tempunit;}echo "</valuetext><br>";
echo  "Max <oblue>Wind Gust</oblue> ";
if ($windunit=='kts'){$windunit="kn";}
if($weather["wind_gust_speed"]>=50){echo "<ored>" .$weather["wind_gust_speed"]."</ored> ".$windunit;}
else if($weather["wind_gust_speed"]>=30){echo "<oorange>" .$weather["wind_gust_speed"]."</oorange><valuetext> ".$windunit;}
else if($weather["wind_gust_speed"]>=0){echo "<ogreen>" .$weather["wind_gust_speed"]."</ogreen><valuetext> ".$windunit;}echo " </valuetext>last 10 minutes ";



If your archive interval is something different then the output value will span that time rather than 10 minutes.

**Comment by steepleian** [comment]
This is the tag that is creating that data: -

$span($time_delta=600).windGust.max.format(add_label=False, $localize=False)

If your preference is to use windSpeed, you can change it in the
archivedata.php.tmpl at line 268

**Comment by Drealine** [comment]
Hm, I tested with values and no, i've a problem with... For example, at 16:10, there is a gust to 18km/h between 16:00 - 16h10 and the website show max wind to 2km/h. Why ?

**Comment by Russell797** [comment]
I confirm that: 
$span($time_delta=600).windGust.max.format(add_label=False, $localize=False)

produces an incorrect value. There is something different about how weewx handles wind. The usual time interval options just don't work. I think I have tried them all.

**Comment by steepleian** [comment]
Interesting reading here which may explain strange readings: -

https://github.com/weewx/weewx/wiki/windgust

“When is a gust not a gust, that is the question” to misquote Shakespeare
:-)

$span($time_delta=600).windSpeed.max.format(add_label=False,
$localize=False) might be a better option depending on your hardware types.

**Comment by Drealine** [comment]
I've tested with windGust.max but still the same issue.
What is the best solution ?

**Comment by Drealine** [comment]
Possible that is the system metric ?
When I converted to m/s to km/h, it seems good. I'm French so my standard unit is km/h.

**Comment by steepleian** [comment]
What unit system is set in the Weather34RealTime section of weewx.conf. It should be METRICWX which uses m/s That is the skin base default. If you changed it, set back. All the skin conversions are based on this setting.

**Comment by Drealine** [comment]
> What unit system is set in the Weather34RealTime section of weewx.conf. It should be METRICWX which uses m/s That is the skin base default. If you changed it, set back. All the skin conversions are based on this setting.

It is METRICWX but my sql table is in METRIC.

**Comment by Drealine** [comment]
All others values like wind max gust on the top website is correct. It is just the value on current condition.

**Comment by Russell797** [comment]
One would expect these two statements to give the same result given I use a 10 minute archive cycle time, but they do not. 

$span($time_delta=600).windSpeed.max.format(add_label=False,
$localize=False)

"$current.windGust.format(add_label=False, $localize=False)";)
This one produces the correct value.

**Comment by Russell797** [comment]
Yes,  the problem is not converting from m/s for the field in question in current conditions module.

**Comment by Drealine** [comment]
Yes. I put an if function with *3.6 and the value it 's correct. You can fix this issue.

**Comment by steepleian** [comment]
The values generated in archivedata.php are METRICWX which uses m/s as the wind speed unit. All conversions are carried out in the skin itself, depending on the user settings in settings1.php.
I can apply your function as a temporary fix until discover the underlying cause. Can you share your function and where it is applied please.
Thank you

**Comment by steepleian** [comment]
Drealine,
The skin is database schema agnostic, mine for example is US units. It is this section in weewx.conf determines what units are emitted: -
[[Weather34Report]]
        skin = Weather34
        HTML_ROOT = /var/www/html/weewx/weather34/
        [[[Units]]]
            [[[[Groups]]]]
                group_altitude = meter
                group_degree_day = degree_C_day
                group_pressure = hPa
                group_rain = mm
                group_rainrate = mm_per_hour
                group_speed = meter_per_second
                group_speed2 = meter_per_second2
                group_temperature = degree_C

These values must not be changed as the skin conversions expect to receive speed data as m/s

**Comment by Drealine** [comment]
On currentconditionsw34.php : 

`<div class="darkskynexthours">
<?php //weather34 average station data
echo $lang['Average']; echo "<oorange>"; echo " "; echo $lang['Temperature']; echo "</oorange> "; echo $lang['Last60Min']; echo " "; if($weather["temp_avg"]>=20)$
echo  "Max <oblue>"; echo $lang['WindSpeed']; echo "</oblue> "; echo $lang['Last10Min']; echo " ";
if ($windunit=='kts'){$windunit="kn";}
**if ($windunit=='km/h'){$weather["wind_gust_10min"] = $weather["wind_gust_10min"] * 3.6;}**
if($weather["wind_gust_10min"]>=50){echo "<ored>" .$weather["wind_gust_10min"]."</ored> ".$windunit;}
else if($weather["wind_gust_10min"]>=30){echo "<oorange>" .$weather["wind_gust_10min"]."</oorange><valuetext> ".$windunit;}
else if($weather["wind_gust_10min"]>=0){echo "<ogreen>" .$weather["wind_gust_10min"]."</ogreen><valuetext> ".$windunit;}echo " </valuetext>";
echo  " <br>"; echo $lang['Average']; echo " ";echo "<oblue>"; echo $lang['WindSpeed']; echo " </oblue>"; echo $lang['Last60Min']; echo " "; ;if($weather["wind_s$
else if($weather["wind_speed_avg"]>=0){echo "<ogreen>" .$weather["wind_speed_avg"]."</ogreen><valuetext> ".$windunit;}
echo "</valuetext>";
if($weather["wind_direction_avg"]>0){echo "<br>"; echo $lang['Average']; echo " "; echo $lang['Direction']; echo " <oorange>"; if($weather["wind_direction_avg"]<$
else if($weather["wind_direction_avg"]<=168.75){echo $lang['SSE'];}else if($weather["wind_direction_avg"]<=191.25){echo $lang['South'];}else if($weather["wind_di$
echo " </oorange><oblue> ".$weather["wind_direction_avg"]."</oblue>°";}
echo "</oorange><br><oblue>"; echo $lang['Rainfall_CC']; echo "</oblue> "; echo $lang['ForTheLastHour']; echo "<oblue> " .$weather["rain_lasthour"]."</oblue><val$
?></valuetext></div></div></div>`

**Comment by Drealine** [comment]
For info, change group speed make an issue with other value.

**Comment by steepleian** [comment]
Thanks to Drealine and Russell797 for their input. The final fix: -

if ($windunit=='kn'){$weather["wind_gust_10min"] = number_format(1.94384*$weather["wind_gust_10min"], 1);}

if ($windunit=='km/h'){$weather["wind_gust_10min"] = number_format(3.6*$weather["wind_gust_10min"], 1);}

if ($windunit=='mph'){$weather["wind_gust_10min"] = number_format(2.236936*$weather["wind_gust_10min"], 1);}
