### ISSUE TITLE
Installation Guide typo

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#17]
I believe where it says:
"Enter packaged.conf if your WeeWX was installed by MacOS method"

You mean 
"Enter macos.conf if your WeeWX was installed by MacOS method"
?

**Comment by steepleian** [comment]
Yep that’s a typo. Thanks for spotting. Are you installing on a Mac?

**Comment by chrisale** [comment]
No problem. Yes I am. MacOS X 10.15 Catalina

**Comment by steepleian** [comment]
Install guide has been corrected.
