### ISSUE TITLE
Forcecast 

### ISSUE THREAD

**Issue by jakesie1309** [steepleian/weewx-Weather34#17]
Hi there

Excellent work on a awesome skin. So firstly, thank you so much for the hard work.
I have weird issues whereby the forecast for darksky or wunderunderground is not coming through.

had a look at my weewx.conf and copy the url in chrome to test. all working fine. looking at the developer options i can see 404 error (Failed to load resource: the server responded with a status of 404 (Not Found))

no idea what i a missing or did wrong. check my services.txt to compare with weewx.conf and using the same units.

See attached image

![Capture](https://user-images.githubusercontent.com/46168037/107870286-6cd9ca80-6e9f-11eb-9c9a-f939768c8081.PNG)

**Comment by steepleian** [comment]
Thank you for your comments. Its very much a team effort.

Can you paste the contents of your services.txt file and the [Weather34WebServices] section from weewx.conf please. Make sure that your personal api keys are not shown by blanking them with xxxxxxxx for your own protection. If you do not wish to post them in public you can use my email address steepleian@gmail.com instead.

Also for context which versions of the skin and WeeWX are you running and whether Python2.7 or Python3

Thank you
Ian

**Comment by jakesie1309** [comment]
Hi Ian

Well say thank you to the team for the awesome work. 
My apologies found the issues, missed what services i should enable on my .conf file. After enabling the services all started to work 100%.

Thank you again for the quick response and keep up the good work team.
