### ISSUE TITLE
Daily F.Cast Snow Given in Metric

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#17]
While the 3 day forecast is shown according to my settings, the popup daily forecast has snow in cm.
Rain is shown as in.
![d-snow](https://user-images.githubusercontent.com/12861605/102341211-81fcb080-3f65-11eb-8acb-c22543d4a92d.png)

**Comment by balloonhotair** [comment]
Ian is offline for a week so when he gets back online he will look into this, but suspect the wrong units are being used in the forecast module

**Comment by gary-hammer** [comment]
Nothing pressing as all else is working.
I was unable to correct the Greenhouse text though.

Perhaps I'll just wait on a few more fixes and improvements, then install
fresh.

**Comment by balloonhotair** [comment]
I did the exact steps I sent since I wanted Indoor instead of Greenhouse also. Make sure you clear the browser cache. Doing just the normal reload does not get the updated lang file.

**Comment by balloonhotair** [comment]
Took a look at the wu forecast and there was no units for snow that were not metric. Go figure it is a UK template. :-) So here is a version with inches. I cannot test wu feeds so I think I got it right but you never know. If you want try it just keep the original.

[outlookwu.php.txt](https://github.com/steepleian/weewx-Weather34/files/5704748/outlookwu.php.txt)

**Comment by gary-hammer** [comment]
As you thought, that corrected the issue.
