### ISSUE TITLE
current year W/m2 in Solar Almanac missing

### ISSUE THREAD

**Issue by Gyvate108** [steepleian/weewx-Weather34#18]
the current year 2021 highest number of the Solar radiation in the solar almanac is strangely missing while the respective date is shown - see picture
sometimes - not clear when, it reappears, but most of the time not
picture below with wattage shown was taken after the one with the missing wattage - meanwhile again no number shown
![Solar Almanac yearly solar missing_20210220](https://user-images.githubusercontent.com/76403541/108720704-714a5700-7521-11eb-83f1-163cd23e2814.JPG)
![Solar Almanac yearly solar mssing_20210218](https://user-images.githubusercontent.com/76403541/108720713-74ddde00-7521-11eb-92ce-88af7c340152.JPG)

**Comment by Gyvate108** [comment]
![Solar Almanac yearly solar missing_20210219](https://user-images.githubusercontent.com/76403541/108721519-5d532500-7522-11eb-839c-33cae4ec769a.JPG) 
that was the intermediate re-appeasrance

**Comment by balloonhotair** [comment]
Fixed changes submitted in both branches.

**Comment by steepleian** [comment]
Resolved
