### ISSUE TITLE
Earthquake reports does not work

### ISSUE THREAD

**Issue by misko903** [steepleian/weewx-Weather34#19]
in weewx.conf:

    eq_url = https://earthquake-report.com/feeds/recent-eq?json
    eq_interval = 3600

the URL is not right. Probably because of changed API? What is the right one?

**Comment by balloonhotair** [comment]
The site has been down since 12/02 just gives a 503 error message. The url is correct but it looks like the site has gone offline.

**Comment by steepleian** [comment]
There is no information available as to what has happened to the eartquake-report.com service. This has been deactivated in the next release of weewx-weather34. You can do the same for this edition by removing 'eq' from the web services code string in weewx.conf

**Comment by misko903** [comment]
thank you for answer!
miso


št 31. 12. 2020 o 0:10 Ian Millard <notifications@github.com> napísal(a):

**Comment by misko903** [comment]
and what about this?
https://earthquake.usgs.gov/fdsnws/event/1/
miso


št 31. 12. 2020 o 0:19 miso <misko0903@gmail.com> napísal(a):

**Comment by steepleian** [comment]
Does that service provide Worldwide information or just the United States. If it the World, do you have a working URL for the global service?

**Comment by misko903** [comment]
yes, it does.
see example here:
https://earthquake.usgs.gov/earthquakes/eventpage/us6000d497
This Croatian Earthquake was yesterday.

This service is implemented in Belchertown skin.

miso


št 31. 12. 2020 o 0:40 Ian Millard <notifications@github.com> napísal(a):

> Does that service provide Worldwide information or just the United States.
> If it the World, do you have a working URL for the global service?
>

**Comment by steepleian** [comment]
Ok thanks, I will look into it for future releases.
Ian
