### ISSUE TITLE
weewx-Weather34 easyW34skinSetup runs Other PHP Run, index.php Does Not

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#19]
Attaching archivedata.php as requested. Output from wee_debug attached as well.

I have an identical test server and installed weewx and this template there a few days ago. Working well.
So, today I installed to my online server.
Does not run.
I have checked and double checked the install, the permissions, etc. I'm probably blind to whatever the issue is by now.

I can run any php from the folder the template is installed in, except for the index.php.
The easyW34skinSetup.php runs and writes the settings file.
WeeWX is creating the w34realtime.txt

I get 500 error when I try the site. weather.ghammer.net or weather.ghammer.net/index.php
Apache error logs show nothing.
Apache access logs only show that a 500 happened.
I have monitored the syslog with no hints.
I do see this, but chalk it up to the can't serve the index.php issue.
`: weewx[60438] ERROR user.weather34: Failed getting web service data. URL: http://10.10.100.110/weewx/weather34/eualert.php?country=&region= Header: ["'User-Agent'", "'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3'"], Error: HTTP Error 404: Not Found
`

You can use these URLs that are served from the same folder to get info on the system/software installed.

https://weather.ghammer.net/check-fetch-times.php

This one is very detailed on the entire apache and PHP environment.
https://weather.ghammer.net/php_test.php

https://weather.ghammer.net/test.php

Then there is the setup page, just showing that it works.

https://weather.ghammer.net/easyW34skinSetup.php

[archivedata.zip](https://github.com/steepleian/weewx-Weather34/files/5212698/archivedata.zip)
[wee_debug_gh.txt](https://github.com/steepleian/weewx-Weather34/files/5212721/wee_debug_gh.txt)

**Comment by steepleian** [comment]
Go to your archivedata.php.tmpl file and comment out lines 55, 56, 57.

Wait for the archive cycle and see what happens.

**Comment by balloonhotair** [comment]
Answer above is only part correct.
Go to to archivedata.php.tmpl in the skin directory for Weather34.
Find these lines
$weewxapi[74] = "$month.lightning_strike_count.sum.format(add_label=False, $localize=False)";	
$weewxapi[75] = "$year.lightning_strike_count.sum.format(add_label=False, $localize=False)";	
$weewxapi[76] = "$day.lightning_strike_count.sum.format(add_label=False, $localize=False)";	
$weewxapi[77] = "$year.lightning_distance.lasttime.format(format_string="%Y-%m-%d %H:%M:%S")";

change them to
$weewxapi[74] =  "N/A";	
$weewxapi[75] = "N/A";	
$weewxapi[76] = "N/A";	
$weewxapi[77] = "N/A";
Thanks

**Comment by gary-hammer** [comment]
> Go to your archivedata.php.tmpl file and comment out lines 55, 56, 57.

I have the file open for editing.  For me, I see these as lines 55.56.57 and think they are not what you want.
`          #end if
           #if $almanac.moon_phase.lower() == "New".lower()
           #set $moonphase = "0"`


I did make the other requested changes for lightning.

**Comment by gary-hammer** [comment]
Making the lightning edits has the website up and running.
Making the question, why does the instance on my test server run?

Thanks for the quick fix!

**Comment by gary-hammer** [comment]
Where can I disable the EU alert as I am not in the EU?
ERROR user.weather34: Failed getting web service data. URL: http://10.10.100.110/weewx/weather34/eualert.php

**Comment by balloonhotair** [comment]
Your instance on your test machine have the lightning fields in the database.

**Comment by gary-hammer** [comment]
Ahhh, yes, this was an old WeeWX upgraded along the way.
The test is a shiny new install.

I'll have to see about upgrading to the new extended database

**Comment by balloonhotair** [comment]
Hi,
In there files settings1.php in directory weather34 find the line
$services = "ds.me.eq.ki.wu.aq.al";
and change it to
$services = "ds.me.eq.ki.wu";

**Comment by gary-hammer** [comment]
Thanks, that did it.
Closing this issue now.
