### ISSUE TITLE
kPa support

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#19]
Hi all,

Wview 4.2 added support for barometer display in kiloPascals (kPa).  Any chance such support could be added into the skin?

Cheers
Chris

**Comment by steepleian** [comment]
Chris,
Jerry already added that support some time ago. Just select from the units
section in the menu.
Ian

**Comment by chrisale** [comment]
I *thought* he had but then I couldn't find mention of it anywhere in the skin or in the menu on the website... now I see that for some reason the skin is on the 3.0.0 version not the 4.1.0 as I thought.  Doh! My bad. Carry on.

**Comment by steepleian** [comment]
Support for kPa was introduced from version 4.0.0 onwards
