### ISSUE TITLE
Issue from latest issue of wind in current conditions

### ISSUE THREAD

**Issue by Drealine** [steepleian/weewx-Weather34#19]
Hi @steepleian,

I would like to open this issue from the latest commit.
Using the `$windunit` make an issue when a user want to use another metric option. 

The best is to use this parameter : `$weather["wind_units"]`

Also for rain, temperature.

**Comment by steepleian** [comment]
Hi,
I am not sure I understand what you mean by ‘use another metric option’

**Comment by Drealine** [comment]
Sorry. I talk about the unit section. When I choose another unit, it not change the unit on Current Condition. So I test with $weather[] and it work.

**Comment by steepleian** [comment]
Did you try the last update I made earlier today? I modified your
suggestion to incorporate all units and it works fine with current
conditions on my web page.

**Comment by Drealine** [comment]
If you go on my website : weather2.drealine.com and change the unit, on current condition, it doesn't change the unit. But if I use `$weather["wind_units"]` instead of `$windunit`, it work.

**Comment by steepleian** [comment]
Hi,

I just tried your site and it worked for me on all unit types.

**Comment by Drealine** [comment]
![image](https://user-images.githubusercontent.com/61891683/80536287-6f1b7880-89a2-11ea-8616-d1822a3c2634.png)

If you check here, the unit not change.

**Comment by Drealine** [comment]
Oh sorry. It work again but in last hour no. It possible that is cookie or cache ?

**Comment by steepleian** [comment]
I have been checking mine since I made the change and it has updated
correctly at every archive cycle. Have been cycling through the different
units and conversions are correct. Have you tried running your syslog tail
to see what might be happening?

**Comment by Drealine** [comment]
Hm I'm not found problems on syslog. I close this issue for the moment.
