### ISSUE TITLE
airqualitymodule.php do not produce display data

### ISSUE THREAD

**Issue by europacafe** [steepleian/weewx-Weather34#2]
Just download the latest version now.
I chose airqualitymodule.php to display on last block of gui. Fill in both aircn api key and purpleair stationid; but no data display; it display only the green status (because aqi = 0-->good air quality). Purpleair/cloudbase display AQI value, but not PM2.5.

Note: it is strange that a number of svg files did not copy to weather34/img folder, eg. wulogo, noaa, pwslogo, mesowest, weathercloud, and airrow34iconlink. I have to copy them manually from downloaded zip file to the weather34 folder created by weewx. sw.js also missing from weather34 folder; need manual copying as well; but not functioning.

**Comment by steepleian** [comment]
The airqualitymodule.php only supports Purpleair AQI monitors at the moment. The other AQI feed is in place for future development and will be supported by its own module. Do you have a Purpleair device? I do not have one myself so have to rely on other users to do the testing for me. As far I am aware the Purpleair module works fine. There has been no change to the code for a very long time.

**Comment by europacafe** [comment]
It’s strange. I don’t have purpleair myself, just use the nearby station id. Does https somehow cause the anomaly?

**Comment by steepleian** [comment]
I have never tried from the Purpleair map as there are no monitors close
enough. However I have just tied with a UK based ID and it works fine for
me.

https://claydonsweather.org.uk/weewx/weather34/purpleair.php

**Comment by steepleian** [comment]
This is the api link I used.

https://www.purpleair.com/json?show=8510

**Comment by europacafe** [comment]
I believe it can get purpleair json data, but somehow, it won't displays on the main page. Could you have a look at my site: [https://bthofen.com/weather34](url) It is hard to explain without photo screenshots...thanks.

**Comment by steepleian** [comment]
airqualitymodule.php code updated to display Purpleair data.

**Comment by europacafe** [comment]
Thank you very much. The airquality is working fine now with the updated one.
The website still report these 2 missing files: /css/sub2.svg, and /css/transparent.gif. These two files are not in the source library I downloaded. Are they important?
The pm2.5 value does not display on the airquality/cloudbase page.
Thank you.





Best Regards

Chote
my twitter
my public blog
my Personal Weather Station (full site)
my Personal Weather Station (mini site)
my ebook library (contact me for access)

Visit my Astrophoto gallery at:
full site
mobile site  

    On Tuesday, 4 February 2020, 05:40:15 GMT+7, Ian Millard <notifications@github.com> wrote:  
 
 
The airqualitymodule.php only supports Purpleair AQI monitors at the moment. The other AQI feed is in place for future development and will be supported by its own module. Do you have a Purpleair device? I do not have one myself so have to rely on other users to do the testing for me. As far I am aware the Purpleair module works fine. There has been no change to the code for a very long time.

**Comment by steepleian** [comment]
Hi,

I have checked the functionality of purpleair.php which give the air quality pop up window. I cannot find any reason that it is not working for you. It working perfectly for me at https://claydonsweather.org.uk <https://claydonsweather.org.uk/>

Regards,
Ian

**Comment by europacafe** [comment]
Thank you. I checked your website. It also did not show the PM2.5 value. See my screenshot of your airquality popup page. How about those svg files that was not there. Could I get those files somehow?Sorry to bother you so much.
Rgds,Chote


Best Regards

Chote
my twitter
my public blog
my Personal Weather Station (full site)
my Personal Weather Station (mini site)
my ebook library (contact me for access)

Visit my Astrophoto gallery at:
full site
mobile site  

    On Thursday, 6 February 2020, 06:51:18 GMT+7, Ian Millard <notifications@github.com> wrote:  
 
 Hi,

I have checked the functionality of purpleair.php which give the air quality pop up window. I cannot find any reason that it is not working for you. It working perfectly for me at https://claydonsweather.org.uk <https://claydonsweather.org.uk/>

Regards,
Ian

**Comment by steepleian** [comment]
OK, I now see the confusion.

The module and pop up are only setup to display the Air Quality Index based
on the fine particle (PM2.5) measurement. This is the primary index used by
the World Air Quality Index Project. See here
http://aqicn.org/city/united-kingdom/oxford-st-ebbes/ which shows the
detail of the monitoring station that you see on my web page.

As far as I am concerned, its not broken. If you wish to see something more
specific and additional information, that will mean some development time
to come up with a solution.
Regards,
Ian

**Comment by europacafe** [comment]
OK, I thought the grey circle with wording PM2.5 on the popup display is supposed to display the PM2.5 microgram/cubic meter value. If not, I'm fine with it. Thank you very much for your great work.

**Comment by steepleian** [comment]
Thank you. I will look at adding more information in the future.
Ian
