### ISSUE TITLE
cannot read input file languages/lang.us.php

### ISSUE THREAD

**Issue by lvittori54** [steepleian/weewx-Weather34#2]
Setting up after upgrade and selected US language options.  

After saving settings and trying to save again I received the error message "cannot read input file languages/lang.us.php"  

Went to folder: cd /home/weewx/public_html/weather34/languages

Entered :  sudo cp lang.en.php lang.us.php

I was able to save settings after creating the lang.us.php file.

**Comment by steepleian** [comment]
In the history of Weather34 there was never a lang.us.php file. There is now :-)
