### ISSUE TITLE
Theme colour selector not working

### ISSUE THREAD

**Issue by m90att** [steepleian/weewx-Weather34#2]
Hello, me again (the word 'busses' springs to mind)!

I've noticed that the theme colour selector isn't working.  My theme is dark and selecting light in the sidebar does not change it.  Setting the default in the setup screen to light works once the page is refreshed but then doesn't appear to remember the default as when the page is opened subsequently, it is dark.  I haven't uploaded any files as nothing has changed in the few days since I raised issue #1 so those files are still current.  Screenshots in sequence with URL below...

On loading
![image](https://user-images.githubusercontent.com/56609577/105819289-e58bec00-5faf-11eb-876f-2204abca5123.png)

After selecting Light Theme in sidebar
![image](https://user-images.githubusercontent.com/56609577/105819360-fccad980-5faf-11eb-8a1d-1a7d2e3866cc.png)

Setup page
![image](https://user-images.githubusercontent.com/56609577/105819457-21bf4c80-5fb0-11eb-963b-00c678259be9.png)

Refresh after exiting setup page
![image](https://user-images.githubusercontent.com/56609577/105819538-37347680-5fb0-11eb-94d2-66f12a352bec.png)

Reloading page
![image](https://user-images.githubusercontent.com/56609577/105819586-44e9fc00-5fb0-11eb-9c39-2d5397163d39.png)

**Comment by balloonhotair** [comment]
What happens when you change the theme to light using the left side menu dropdown.

**Comment by balloonhotair** [comment]
If the same issues open settings1.php and remove the line **$theme=**   BUT NOT the line **$theme1=**       Then reload the page and check.

**Comment by m90att** [comment]
Hi, That’s what I meant by ‘sidebar’, sorry.  It doesn’t change. From: balloonhotairSent: 26 January 2021 16:11To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Theme colour selector not working (#2) What happens when you change the theme to light using the left side menu dropdown.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by m90att** [comment]
I couldn’t find settings1.php.  I found settings.php and settings1.default.php in the www folder.  I removed the line from settings1.default.php but it made no difference. From: Matt CSent: 26 January 2021 16:39To: steepleian/weewx-Weather34Subject: RE: [steepleian/weewx-Weather34] Theme colour selector not working (#2) Hi, That’s what I meant by ‘sidebar’, sorry.  It doesn’t change. From: balloonhotairSent: 26 January 2021 16:11To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Theme colour selector not working (#2) What happens when you change the theme to light using the left side menu dropdown.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by balloonhotair** [comment]
There has to be a settings1.php file there for the page to render correctly. The very first time the page loads the settings1.default.php files get copied into settings1.php along with any changes made using w34easysetup.php. So there has to be a settings1.php file otherwise all the php includes would fail and the page would not render correctly. So the issue is larger if you do not have settings1.php file and if this is true then copy settings1.default.php to settings1.php but if the copy tells you the file exist abort the copy.

**Comment by m90att** [comment]
Hmm, ok.  Where should I look for settings1.php?  I’m probably looking in the wrong place. From: balloonhotairSent: 26 January 2021 17:01To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Theme colour selector not working (#2) There has to be a settings1.php file there for the page to render correctly. The very first time the page loads the settings1.default.php files get copied into settings1.php along with any changes made using w34easysetup.php. So there has to be a settings1.php file otherwise all the php includes would fail and the page would not render correctly. So the issue is larger if you do not have settings1.php file and if this is true then copy settings1.default.php to settings1.php but if the copy tells you the file exist abort the copy.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by m90att** [comment]
Found it! Now when I first load the page it shows light (per the setup setting page)I can change it to dark using the sidebar menu optionBUTI cannot then change it back to lightA refresh doesn’t change it back to light So I’m stuck on dark again From: Matt CSent: 26 January 2021 17:17To: steepleian/weewx-Weather34Subject: RE: [steepleian/weewx-Weather34] Theme colour selector not working (#2) Hmm, ok.  Where should I look for settings1.php?  I’m probably looking in the wrong place. From: balloonhotairSent: 26 January 2021 17:01To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Theme colour selector not working (#2) There has to be a settings1.php file there for the page to render correctly. The very first time the page loads the settings1.default.php files get copied into settings1.php along with any changes made using w34easysetup.php. So there has to be a settings1.php file otherwise all the php includes would fail and the page would not render correctly. So the issue is larger if you do not have settings1.php file and if this is true then copy settings1.default.php to settings1.php but if the copy tells you the file exist abort the copy.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by balloonhotair** [comment]
So did you remove the $theme setting from the file you just found?
If so will have to have Ian look at what his install shows since my setup is working just fine.

**Comment by m90att** [comment]
Morning, yes I removed it. From: balloonhotairSent: 26 January 2021 17:32To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Theme colour selector not working (#2) So did you remove the $theme setting from the file you just found?If so will have to have Ian look at what his install shows since my setup is working just fine.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by steepleian** [comment]
Fixed. Replaced index.php and easyW34skinSetup.php files. Theme switching now only takes place from the menu UI Theme button which toggles both page and charts between dark and light. Theme switching has been removed completely from the settings page. The theme default is Dark

**Comment by m90att** [comment]
Do I need to do a full reinstall?  Given issues I saw on the fresh installation if there’s a shortcut that would be great? From: Ian MillardSent: 27 January 2021 11:11To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Theme colour selector not working (#2) Closed #2.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by steepleian** [comment]
You should just be able to replace index.php, settings1_default.php and easyW34skinSetup.php. Then open settings page and hit the save button at the bottom. This should clear out any vestage of $theme and %theme1 from settings1.php. Toggle the UI Theme button in the menu a few times refreshing the screen on each toggle. Check that the charts are also syncronised to the theme.

**Comment by m90att** [comment]
Thank you From: Ian MillardSent: 27 January 2021 13:50To: steepleian/weewx-Weather34Cc: m90att; AuthorSubject: Re: [steepleian/weewx-Weather34] Theme colour selector not working (#2) You should just be able to replace index.php, settings1_default.php and easyW34skinSetup.php. Then open settings page and hit the save button at the bottom. This should clear out any vestage of $theme and %theme1 from settings1.php. Toggle the UI Theme button in the menu a few times refreshing the screen on each toggle. Check that the charts are also syncronised to the theme.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
