### ISSUE TITLE
Hold last values on NULL

### ISSUE THREAD

**Issue by techfixpros** [steepleian/weewx-Weather34#2]
WeeWx 3.9.2
WX-UB40-IHVN-03 Latest
WX-HWS 0.2
CRT 0.18
Acurite 4n1

Every few loops the temperature and some other values are NULL. This is both in the w34 and crt files. When this happens the temperature on the HWS page goes to 0, and the trends adjust accordingly. When a valid value is updated in a later loop the temperature and trends update properly.

Is it possible to have HWS hold the last value if a new value is NULL, and only update on non-null values?

**Comment by steepleian** [comment]
Hi John,

Are you still running the CRT extension? If so I think that may be your
problem. The generation of weather34 specific data is now built into the
skin itself so CRT is no longer required. Delete it by running sudo
./wee_extension —uninstall crt (see instructions in the skin installation
guide).

If you require CRT data for other purposes, don’t worry because you can tap
into the w34realtime.txt file to provide the same information.

Ian

**Comment by steepleian** [comment]
I will also add some code this evening to take care of missing loop data
gaps.

**Comment by steepleian** [comment]
Code added but not yet tested

**Comment by techfixpros** [comment]
I can test if needed. Removing CRT did not fix the issue.

**Comment by steepleian** [comment]
Ok. I have updated the Git. Download again and perform another install.
Many thanks

**Comment by techfixpros** [comment]
It is still happening. Have confirmed the new version is running:

WX-UB40-IHVN-04 WeeWX-3.9.2 Accurite
&
WX-HWS            04        Weather34 skin

And have cleared browser cache.

**Comment by steepleian** [comment]
I am taking another look at this by splitting the live data feed. Will let
you have an advanced copy to try when it is finished.

**Comment by tongboy** [comment]
I have a similar setup using an SDR with acurite.  The last change you added to the repo started holding the last values and only updating when they change.  Thanks for this!

**Comment by steepleian** [comment]
Hi John,

Can you try another update now please. The latest change has fixed the
problem for many.

Thanks,
Ian

**Comment by steepleian** [comment]
Issue has now been resolved with the last update WX-UB40-IHVN-07

**Comment by techfixpros** [comment]
That looks to have fixed it. Thanks you.
