### ISSUE TITLE
Error 500 after install

### ISSUE THREAD

**Issue by vajdj** [steepleian/weewx-Weather34#20]
I installed a fresh copy of weewx 4.2.0 into /home/weewx.  It is running just fine (http://<host>/weewx).  I then added weather34 to the mix, let things run for a bit and then tried to access the weather34 directory (http://<host>/weewx/weather34).  I got back an error 500.  I've been looking at the logs with no success in trying to figure it out.  There's nothing in the apache2 logs that gives me even the slightest help.

This is running on the latest Raspbian (10).  

I think this could be related to the error in the syslog from cheetah.  Any help will be appreciated.  I've include the syslog cycles, the wee_debug output and the weather34/skins.conf.  

[syslog.txt](https://github.com/steepleian/weewx-Weather34/files/5752450/syslog.txt)

[skin.conf.txt](https://github.com/steepleian/weewx-Weather34/files/5752455/skin.conf.txt)

[weewx.debug.txt](https://github.com/steepleian/weewx-Weather34/files/5752449/weewx.debug.txt)

**Comment by balloonhotair** [comment]
The 500 error is due to the NameMapper error. Not sure if Ian has tested the template against weewx 4.2 just 4.1.

**Comment by balloonhotair** [comment]
What version of Cheetah are you using? Need version 3.

**Comment by vajdj** [comment]
python3-cheetah 3.1.0-3

installed using apt-get

**Comment by balloonhotair** [comment]
So no idea on this and since you are the only one reporting this it must be something with your setup. The only thing I can think of trying is a total shot in the dark and have you comment out some lines in the file archiveddata.php.tmpl in the ..../Weather34/serverdata directory. Note in Cheetah a comment is 2#. Make sure you only edit the lines list below that have 2#
 ##set $mlsc = $month.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        ##if $mlsc == "$month.lightning_strike_count.sum.format(add_label=False, $localize=False)" 
           #set $mlsc = "N/A"
        ##end if
        ##set $ylsc = $year.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        ##if $ylsc == "$year.lightning_strike_count.sum.format(add_label=False, $localize=False)" 
           #set $ylsc = "N/A"
        ##end if
        ##set $dysc = $day.lightning_strike_count.sum.format(add_label=False, $localize=False) 
        ##if $dysc == "$day.lightning_strike_count.sum.format(add_label=False, $localize=False)" 
           #set $dysc = "N/A"
        ##end if
        ##set $ldlt = $year.lightning_distance.lasttime
        ##if $ldlt == "$year.lightning_distance.lasttime" 
           #set $ldlt = "N/A"
        ##end if

**Comment by steepleian** [comment]
Have you seen this in the WeeWX documentation: -

http://weewx.com/docs/usersguide.htm#Cheetah.NameMapper.NotFound_errors

**Comment by vajdj** [comment]
Commenting out the lines shown above got rid of the errors.   Now I just get a blank page when I go to the weewx/weather34 page. (console debug on the browser shows error 500).  I was able to load weewx/weather34/easyW34skinSetup.py and do the settings. But weewx/weather34 is still blank.

The other thing I've noticed is that if I reboot /var/www/html/weewx is empty at startup.  weewx copies over all of its files, but weather34 does not copy over all of its files.  I have to another install for the files to be copied over.  Which I believe means I loose the settings since they are stored in /var/www/html/weewx/weather34

**Comment by balloonhotair** [comment]
Yea I just report that to Ian, there seem to be some left over code in skin.conf that for some reason effects your install but not others. So open skin.conf and set the  following config item to nothing should look just like  copy_once =

**Comment by balloonhotair** [comment]
So there are still php errors with the archivedata.php file. If you can post that file here we can look at it. It is located in the .../weewx/weather34/serverdata directory in the www part of the install.

**Comment by vajdj** [comment]
Well, I found the why the change to  archiveddata.php.tmpl was needed.  Turns out when I upgraded the system to have 4.x, the database was not reconfigured.  That information was not on the weewx website 

[http://www.weewx.com/docs/upgrading.htm#From_V3.9_or_earlier](http://www.weewx.com/docs/upgrading.htm#From_V3.9_or_earlier)

After going through the wee_database --reconfigure and --rebuild-daily, the error went away.

I tried the change to copy_once in the skin.conf.  It didn't make any difference.  

Here's the syslog after a restart and skin.conf modified.  The archivedata and a syslog.  

[archivedata.php.txt](https://github.com/steepleian/weewx-Weather34/files/5755800/archivedata.php.txt)
[skin.conf.txt](https://github.com/steepleian/weewx-Weather34/files/5755801/skin.conf.txt)
[syslog.txt](https://github.com/steepleian/weewx-Weather34/files/5755802/syslog.txt)

**Comment by balloonhotair** [comment]
Well that is progress.
1) Now the coping of the files should be gone.
2) Syslog show the following dir is missing /var/www/html/weewx/weather34/serverdata/     Please check to see if the serverdata directory is there and the path exists

**Comment by vajdj** [comment]
Found the problem for files not being copied at reboot.  When the isntaller ran, it copied all the files to /var/www/html/weex/weather34.  It should have copied them to /etc/weewx/skins/Weather34. Here's what I did to deal with this problem

I rebooted the PI.  I noted that `/var/www/html/weewx` is empty.

Next I ran:

`sudo python3 w34_installer.py` (selected option 1 - installed package).

I then copied all of `/var/www/html/weewx/weather34` to `/etc/weewx/skins/Weather34`.

I deleted all files in `/var/www/html/weewx`.

I started weewx and after a few minutes, `/var/www/html/weewx/weather34` was populated.  

That was verified via this log entry:
```
Dec 30 17:17:00 wx weewx[1473] INFO weewx.cheetahgenerator: Generated 1 files for report Weather34Report in 1.86 seconds
Dec 30 17:17:00 wx weewx[1473] INFO weewx.reportengine: Copied 555 files to /var/www/html/weewx/weather34/
```
So that points to maybe an issue with the installer or me not using it correctly.

Now if we can figure out why I get the 500 when loading `weewx/weather34`, we should be good.

**Comment by balloonhotair** [comment]
So it looks like you are choosing the wrong option for what you are installing, since the installer is use by a ton of people without and reports of issues. Since you are doing manual copies of files means you are not installing all the parts of the template. The installer also creates directories and sets permissions of all the files.   Need to know what package you are choosing since it looks like you should be choosing the package.conf. Right now the best bet is to get a install to work without making any changes to what the installer produces otherwise I feel it is a waste of time trying to make a bad install work.

**Comment by steepleian** [comment]
Just to concur with Jerry's comments, it looks as though you are mixing up your install methods. To be clear, the customised installer gives you three options. If you installed WeeWX using a packed installer e.g. Debian, Ubuntu, Mint, RaspberryPi OS, Redhat, Centos, Fedora, SUSE, OpenSUSE you should select the 'Packaged' option. For a WeeWX MacOS install, select the 'MacOS' option. Finally for a WeeWX setup.py install select the 'Setup.py' option. All the files are copied into the correct location for your type of setup instantly. There should be no time lag waiting for the next archive interval waiting for the weather34 folder to be populated.
Ian

**Comment by vajdj** [comment]
First thanks for working through this with me.  

After the last comment I decided to punt.  I created a clean install in /home/weewx using the setup.py method and run from there.  Here are the exact steps I took.

### Install WeeWx fresh

Logged in as pi
```
sudo mkdir /home/weewx
cd ~
mkdir weewx
cd weewx
wget http://weewx.com/downloads/weewx-4.2.0.tar.gz
tar xzvf weewx-4.2.0.tar.gz
cd weewx-4.2.0
python3 ./setup.py build
sudo python3 ./setup.py install
sudo vi /home/weewx/weewx.conf
```
Attached is the weewx.conf (as weewx.conf.pre34.txt)
[weewx.conf.pre34.txt](https://github.com/steepleian/weewx-Weather34/files/5756143/weewx.conf.pre34.txt)

` sudo python3 /home/weewx/bin/weewxd --daemon --pidfile=/var/run/weewx.pid /home/weewx/weewx.conf`

After a few runs (and the web page loads)

```sudo kill `cat /var/run/weewx.pid` ```

The syslog for this run is attached as syslog.pre34.txt
[syslog.pre34.txt](https://github.com/steepleian/weewx-Weather34/files/5756147/syslog.pre34.txt)

### Now install W34

Created services.txt (attached) using https://steepleian.github.io/weewx-Weather34

`cd ~/weewx`
The following failed.  It was taken from https://github.com/steepleian/weewx-Weather34/blob/main/INSTALLATION_GUIDE.md

`wget https://github.com/steepleian/weewx-Weather34/edit/master/weewx-Weather34-master.zip`

So the following was done:
```
sudo git clone https://github.com/steepleian/weewx-Weather34.git
sudo cp ../services.txt weewx-Weather34/
sudo python3 w34_installer.py
```

Here's services.txt

[services.txt](https://github.com/steepleian/weewx-Weather34/files/5756164/services.txt)

This is the output:
```
!!! THIS INSTALL IS USING PYTHON VERSION 3.7.3 IS THIS CORRECT? (Yes/No)Yes

Install will continue with Python Version 3.7.3
1 -> packaged.conf
2 -> setup_py.conf
3 -> macos.conf
Enter the NUMBER of the installer config file 2
Installer Config file setup_py.conf was chosen.
Updating weewx config
Done! Will Need To Restart Weewx For Changes To Be Active
```
Now start things up again.  weewx.conf at this point is attached as weewx.conf.post34.txt
[weewx.conf.post34.txt](https://github.com/steepleian/weewx-Weather34/files/5756150/weewx.conf.post34.txt)

`sudo python3 /home/weewx/bin/weewxd --daemon --pidfile=/var/run/weewx.pid /home/weewx/weewx.conf`

At this point I still get blank screen (HTTP 500) when I access weewx/weather34 from the browser
and `/var/www/html/weewx/weather34` is populated

Here's the syslog for that run (syslog.post34.prereboot.txt)
[syslog.post34.prereboot.txt](https://github.com/steepleian/weewx-Weather34/files/5756153/syslog.post34.prereboot.txt)

Reboot the machine

`sudo reboot`

Now /var/www/html/weewx is empty

`sudo python3 /home/weewx/bin/weewxd --daemon --pidfile=/var/run/weewx.pid /home/weewx/weewx.conf`

After this run, there is only a few files in /var/www/html/weewx/weather34.  

```
$ ls -al /var/www/html/weewx/weather34/
total 0
drwxr-xr-x 4 root root   80 Dec 30 19:42 .
drwxrwxrwt 6 root root 1500 Dec 30 19:44 ..
drwxr-xr-x 2 root root   80 Dec 30 19:44 serverdata
drwxr-xr-x 3 root root   60 Dec 30 19:42 w34highcharts
$ ls -aRl /var/www/html/weewx/weather34/
/var/www/html/weewx/weather34/:
total 0
drwxr-xr-x 4 root root   80 Dec 30 19:42 .
drwxrwxrwt 6 root root 1500 Dec 30 19:44 ..
drwxr-xr-x 2 root root   80 Dec 30 19:44 serverdata
drwxr-xr-x 3 root root   60 Dec 30 19:42 w34highcharts

/var/www/html/weewx/weather34/serverdata:
total 12
drwxr-xr-x 2 root root   80 Dec 30 19:44 .
drwxr-xr-x 4 root root   80 Dec 30 19:42 ..
-rw-r--r-- 1 root root 4804 Dec 30 19:44 archivedata.php
-rw-r--r-- 1 root root  283 Dec 30 19:44 w34realtime.txt

/var/www/html/weewx/weather34/w34highcharts:
total 0
drwxr-xr-x 3 root root  60 Dec 30 19:42 .
drwxr-xr-x 4 root root  80 Dec 30 19:42 ..
drwxr-xr-x 2 root root 180 Dec 30 19:44 json

/var/www/html/weewx/weather34/w34highcharts/json:
total 4384
drwxr-xr-x 2 root root     180 Dec 30 19:44 .
drwxr-xr-x 3 root root      60 Dec 30 19:42 ..
-rw-r--r-- 1 root root 1255362 Dec 30 19:44 bar_rain_week.json
-rw-r--r-- 1 root root  890140 Dec 30 19:44 indoor_derived_week.json
-rw-r--r-- 1 root root  784224 Dec 30 19:44 solar_week.json
-rw-r--r-- 1 root root  533665 Dec 30 19:44 temp_week.json
-rw-r--r-- 1 root root    9281 Dec 30 19:44 wind_rose_week.json
-rw-r--r-- 1 root root  517754 Dec 30 19:44 wind_week.json
-rw-r--r-- 1 root root  479882 Dec 30 19:42 year.json
```
So it doesn't properly populate the directory.  Where is it suppose to copy the files from?

Here's the syslog from that run (syslog.post34.postreboot.txt)

[syslog.post34.postreboot.txt](https://github.com/steepleian/weewx-Weather34/files/5756156/syslog.post34.postreboot.txt)

So what did I do wrong?

**Comment by balloonhotair** [comment]
Not following this statement.
**So it doesn't properly populate the directory. Where is it suppose to copy the files from?**

It looks like you have files in serverdata now.  Can you post archivedata.php again. 500 errors are due to PHP errors. Is there anything in /var/log/apache2/error.log?

Everything looks correct above.

**Comment by balloonhotair** [comment]
Also post another syslog

**Comment by balloonhotair** [comment]
One more item both weewx and your web server are the same machine? Correct?

**Comment by vajdj** [comment]
**Re: Not following this statement. So it doesn't properly populate the directory. Where is it suppose to copy the files from?**

What I'm saying is that after a reboot /var/www/html/weewx/weather34 is empty before weewx runs.  Before the reboot and after the w34_installer.py  is executed during install, there are large number of php, json, etc files.  After the reboot AND running the weewx, the only files in /var/www/html/weewx/weather34 are the the ones I listed above.

What I was also asking is after w34_installer.py runs, where does is the installer suppose  put the files that the copy_once in the skin.conf will use to populate /var/www/html/weewx/weather34 when the configure engine runs?

**Re: One more item both weewx and your web server are the same machine? Correct?**

That is correct.  The webserver and weewx are on the same machine.

**Re: Can you post archivedata.php again. 500 errors are due to PHP errors. Is there anything in /var/log/apache2/error.log?**

There's nothing in the apache2/error.log corresponding to the 500 errors.  There are some notices about apache2 catching a sigterm, but that appears to be around the time of  system reboot.

Here's the archivedata.php:
[archivedata.php.txt](https://github.com/steepleian/weewx-Weather34/files/5756315/archivedata.php.txt)

Here's the syslog you asked for:
[syslog.2146.txt](https://github.com/steepleian/weewx-Weather34/files/5756310/syslog.2146.txt)

**Additional Observations** 

After the reboot and allowing weewx to run, when I go to weewx/weather34 in the browser I'm given a directory listing showing the following:
```
  | Name | Last modified | Size | Description
-- | -- | -- | -- | --

  | Parent Directory |   | - |  
  | serverdata/ | 2020-12-30 21:37 | - |  
  | w34highcharts/ | 2020-12-30 21:37 | - |  
```
That's probably because index.php is gone since the reboot deleted it and the copygenerator can not find the files to copy into /var/www/html/weewx/weather34  

I notice that the ~/weewx/weewx-Weather34/setup_py.conf (as well as others) configure so the files in ~/weewx/weewx-Weather34/www directory are copied to /var/www/html/weewx/weather34.  Shouldn't they be copied into /home/weewx where the copygenerator can get at them when it runs for the first time and the copy_once is executed?

**Comment by balloonhotair** [comment]
So the installer know where to put all the files based on info it gets from one of the installer.conf files. The template no longer uses copy_once.
So this is starting to make sense a little. so do the following.
1) Stop weewx.
2) Run the template installer again just like you did before.  Now you should have a complete install of the template. 
3) Go to the skin.conf and remove all the files from the copy_once config entry.
4) Restart weewx.
The copy_once is not used with the installer so for some reason it got into the install and has not effected anyone until you. :-)

**Comment by vajdj** [comment]
Ok, that is done.  Still getting a 500 loading the main page.

I also figured out why /var/www/html/weewx was empty at reboot.  I had forgotten over a year ago I set things up so /var/www/html/weewx to be backed by a tmpfs. It had more than enough space.  that was done as a recommendation by weewx to reduce the write frequency to the SD card and extend its life.  A copy once that works would have allowed that mechanism to continue to work.  

But I have backed that out and the /var/www/html/weewx is now backed by the SD card.  Still fighting the 500.  I'm guessing it's something in the PHP.  Just need to figure out what it is.

**Comment by balloonhotair** [comment]
Please post the three files in the serverdata directory, since these files make up what is displayed on the index.php page.
Also are there any errors in the syslog?  If so please post them here. Also post your settings1.php file .

**Comment by vajdj** [comment]
No errors in syslog.

There were 4 files in serverdata.  but placeholder.txt appears empty

[settings1.php.txt](https://github.com/steepleian/weewx-Weather34/files/5756610/settings1.php.txt)
[weewxserverinfo.txt](https://github.com/steepleian/weewx-Weather34/files/5756611/weewxserverinfo.txt)
[w34realtime.txt](https://github.com/steepleian/weewx-Weather34/files/5756612/w34realtime.txt)
[placeholder.txt](https://github.com/steepleian/weewx-Weather34/files/5756613/placeholder.txt)
[archivedata.php.txt](https://github.com/steepleian/weewx-Weather34/files/5756614/archivedata.php.txt)

**Comment by balloonhotair** [comment]
In your settings1.php file find this line

$autotheme = 'auto_1';

and add this line right under it

$theme = 'dark';

**Comment by vajdj** [comment]
That change did not produce anything different.

I then went the `192.168.1.30/weewx/weather34/easyW34skinSetup.php` and logged in.

The apache error log popped up with this message

`[Thu Dec 31 08:59:17.613378 2020] [php7:notice] [pid 4690] [client 192.168.1.50:63316] PHP Notice:  Undefined variable: theme1 in /var/www/html/weewx/weather34/easyW34skinSetup.php on line 940, referer: http://192.168.1.30/weewx/weather34/easyW34skinSetup.php`

I filled in the settings and there's still no change.  500 on the main page

FYI:  the login screen for the setup reported the following PHP version: 7.3.25-1+0~20201130.73+debian10~1.gbp042074

**Comment by balloonhotair** [comment]
Please verify that there is a $theme and $theme1 variable in settings1.php and they are set to 'dark';

**Comment by vajdj** [comment]
There is now.  Still 500 when accessing weewx/weather34.  Nothing in the apache error log

```
$autotheme = 'auto_1';
$theme = 'dark';
$theme1 = 'dark';
$since = '2012';
```

**Comment by balloonhotair** [comment]
So running out of ideas.   What happens if you replace index.php in the url with temperature.php. Do you get a 500 error of text showing temperature values.

**Comment by balloonhotair** [comment]
Please check and verify that all the dependencies for PHP are installed as stated in the install docs.

**Comment by balloonhotair** [comment]
Something else to try. If you are running apache2 server edit the file php.ini and add the following lines.
display_errors = on
display_startup_errors = on
error_reporting = E_ALL
You will find an error section in the ini and just add them there. Then restart you apache2 server and try to load the page. When it fails look in the apache2/error.log and see what errors there are.
The php.ini file on my machine is located at /etc/php/7.0/apache2

**Comment by vajdj** [comment]
Thank you.  I'll give it a try tomorrow or the next day.  I'm distracted with something from work that is more presssing.

**Comment by gary-hammer** [comment]
@balloonhotair 
This is the sequence of errors I had when I first installed.
You and Ian did eventually correct the errors. Perhaps look at my name under closed tickets to save you troubleshooting the same things.

**Comment by vajdj** [comment]
Well, progress.  Turns out apache was using PHP 7.3 and installed modules were PHP 7.4.  Once I changed apache over to PHP7.4 using a2enmod, I get a display.  I've checked all the PHP modules listed in the install and they are all 7.4.  

But, something is not right with the webservices.  Forecast from WU, AQ and METAR are not working.  I have the tokens and the like listed in weewx.conf, and syslog shows they are installed, but no and I see the word offline beside METAR and offline listed for the AQ module and nothing in the for forecast.  Here's an image.

![Screen Shot 2021-01-04 at 13 55 47](https://user-images.githubusercontent.com/59487710/103569092-b264aa00-4e94-11eb-9cc0-5592ee7c8b3d.png)

**Comment by balloonhotair** [comment]
Need to see the following
1) Is there a jsondata directory and if so what files are in it/
2) Current syslog from when weewx startup to current time.
3) The webservices section of the weewx.conf

**Comment by steepleian** [comment]
Can you post the web services section of weewx.conf. Remove keys first for
your own safety.
Ian

**Comment by vajdj** [comment]
```
ls -1 weather34/jsondata/
aq.txt
ki.txt
me.txt
place.holder
wu.txt
```

web services section from weewx.conf (redacted tokens and exact positions):

```
[Weather34WebServices]
    aq_url = https://api.waqi.info/feed/geo:38.xxxxxx;-78.xxxxx/?token=xxxxxxxxxxxxxxxxxxxxxx
    aq_interval = 3600
    aq_filename = /var/www/html/weewx/weather34/jsondata/aqi.txt
    ds_url = https://api.forecast.io/forecast//38.066490,-78.4338?lang=en&units=
    ds_interval = 3600
    ds_filename = /var/www/html/weewx/weather34/jsondata/darksky.txt
    wu_url = https://api.weather.com/v3/wx/forecast/daily/5day?geocode=38.xxxxxx,-78.xxxxx&language=en&format=json&units=e&apiKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    wu_interval = 3600
    wu_filename = /var/www/html/weewx/weather34/jsondata/wuforecast.txt
    eq_url = https://earthquake-report.com/feeds/recent-eq?json
    eq_interval = 3600
    eq_filename = /var/www/html/weewx/weather34/jsondata/eqnotification.txt
    ki_url = https://services.swpc.noaa.gov/products/geospace/planetary-k-index-dst.json
    ki_interval = 43200
    ki_filename = /var/www/html/weewx/weather34/jsondata/kindex.txt
    me_url = https://api.checkwx.com/metar/KCHO/decoded
    me_header = X-API-Key:xxxxxxxxxxxxxxxxxxxxx
    me_interval = 3600
    me_filename = /var/www/html/weewx/weather34/jsondata/metar34.txt
    pu_url = https://www.purpleair.com/json?show=
    pu_interval = 3600
    pu_filename = /var/www/html/weewx/weather34/jsondata/purpleair.txt
    al_url = http://192.168.1.30/weewx/weather34/eualert.php?country=&region=
    al_interval = 3600
    al_filename = /var/www/html/weewx/weather34/jsondata/meteoalarm.txt
    services = me.wu.eq.ki.aq
```

syslog:
[syslog.txt](https://github.com/steepleian/weewx-Weather34/files/5766382/syslog.txt)

**Comment by steepleian** [comment]
Ok, take another if weather34.py from the repository. The one you currently
have is intended for a future release.

**Comment by vajdj** [comment]
OK, it's all up and running.  Thank you so much for the help and patience.  Couple of questions.

1.  Is there an alternative to Dark Sky for hourly forecasts.  From what I can tell Dark Sky is no longer handing out new API keys and will be shutting down.  I don't expect one, but thought I might ask.
2. Is there a way to populate the airqualitymodule with data from the jsondata/aqi.txt.  As far as I can tell, the data right now needs to come from the database which means I think would mean I need to purchase a module.  Is there a panel I can use that will use the data in jsondata/aqi.txt.
3. I see that the current conditions panel needs sat24 working for full feature which appears not to work for the americas (based on what I saw in another issue).  Is there a way to have the panel not include always present sun and clear conditions as shown in the attached image.  I do have Weather34CloudCover enable set to false in weewx.conf

![Screen Shot 2021-01-05 at 09 24 55](https://user-images.githubusercontent.com/59487710/103657593-13918980-4f38-11eb-9d03-f3673c7baaab.png)

**Comment by steepleian** [comment]
Hi,
Glad is working now.
In answer to your questions.
1. There are other services which provide hourly detail but not to the
level of detail of DarkSky. The closest I have found are Aeris Weather and
a Norwegian service and I playing around with those.

2. Yes there is a very simple way of getting the data into the database by
using FilePile, a plugin that Tom Keffar produced. Search on GitHub.

3. The current conditions are a combination of your local Metar and your
real time data. Check that your Metar is working correctly.
Ian

**Comment by vajdj** [comment]
Thanks, I'll check out FilePile.  

I believe METAR is working.  Below is the panel for the current conditions, the popup for the nearby METAR and the metar34.txt contents

![Screen Shot 2021-01-05 at 11 24 17](https://user-images.githubusercontent.com/59487710/103671616-25c7f380-4f49-11eb-915d-70b58e7d73a1.png)

![Screen Shot 2021-01-05 at 11 24 05](https://user-images.githubusercontent.com/59487710/103671634-2b253e00-4f49-11eb-8ded-8101bcf359a2.png)

[metar34.txt](https://github.com/steepleian/weewx-Weather34/files/5771403/metar34.txt)

**Comment by steepleian** [comment]
OK I will see if I can replicate that.

**Comment by steepleian** [comment]
Can you try this version of the current conditions module.

Thanks,
Ian

**Comment by vajdj** [comment]
Is there a missing attachment?

**Comment by steepleian** [comment]
Looks like was removed. I will zip and resend.

**Comment by steepleian** [comment]
Here is a zipped version. Hopefully it won’t get stripped out this time

**Comment by steepleian** [comment]
[currentconditions34.php.zip.txt](https://github.com/steepleian/weewx-Weather34/files/5772906/currentconditions34.php.zip.txt)
Third time lucky :-)

**Comment by vajdj** [comment]
I assume the file is suppose to be currentconditionsw34.php and not currentcurrentconditions34.php (missing w in the name).  I put the file in as currentconditionsw34.php and the conditions are correct, however it lost the rest of the information.  Here's a screen capture of the module output.  I also noticed that the file is considerably smaller than then the original 9K vs 15K for the original.

![msedge_7gi6Or7KNn](https://user-images.githubusercontent.com/59487710/103769699-c58d8c00-4ff2-11eb-832a-390a4c71a59c.png)

**Comment by steepleian** [comment]
Yes that was a cut down version to establish that the icon/graphic part was working correctly. So now can you please try this version.
Tanks Ian
[currentconditionsw34.php.zip](https://github.com/steepleian/weewx-Weather34/files/5778646/currentconditionsw34.php.zip)

**Comment by vajdj** [comment]
Looking good.  Just one thing.  The cloud base is being displayed in meters.  Previously it was in feet (which is my preference as a pilot in the US).  Looks like the criteria in the PHP to determine its units changed.  What am I missing in my settings to bring it back to feet.

Thanks

![Screen Shot 2021-01-07 at 08 59 01](https://user-images.githubusercontent.com/59487710/103902612-c690ed00-50c8-11eb-86af-2b8bccb1edc6.png)

**Comment by vajdj** [comment]
Nevermind.  I cycled the units in the upper right corner and now its in feet.  So looks like its all working.  Feel free to close out.  

And again, thanks for all the help.  It really is appreciated.  I now have a nice display for my weather station.

**Comment by steepleian** [comment]
Cloud base conversion corrected by recycle refresh
