### ISSUE TITLE
automatic tile update frequency/interval in v.4.1.0

### ISSUE THREAD

**Issue by Gyvate108** [steepleian/weewx-Weather34#20]
in my opinion the Solar current values and the lightning and solar clock values on their tiles are not automatically updated in a reasonable interval - or can I change this by some setting.
see https://www.wxforum.net/index.php?topic=40083.msg425716#msg425716
![weewx-w34-4 1 0-tile update](https://user-images.githubusercontent.com/76403541/108835050-343c9e00-75cf-11eb-8ad0-f62e1ee0f62a.JPG)

**Comment by steepleian** [comment]
The updates are controlled by this file: -

https://github.com/steepleian/weewx-Weather34/blob/main/www/updater.php

**Comment by Gyvate108** [comment]
OK - and what exactly do I have to do to make the solar tile ("module") get updated e.g. every 60 seconds ?
Or any other one ?  That's not obvious to me ...

**Comment by steepleian** [comment]
It is probably easier to change the variable settings here: -
https://github.com/steepleian/weewx-Weather34/blob/main/www/settings.php

![image](https://user-images.githubusercontent.com/18438654/108843554-bda19f80-75d2-11eb-8cf1-0de2c9313a6c.png)

**Comment by Gyvate108** [comment]
Thanks - I had already figured out that it would have to be those global variables $xxxxRefresh, but hadn't figured out yet, in which script they were to be found. The tiles are now refreshing in an interval that is convenient for me (and which corresponds to the timings I was used to in my classic W34 installation).
