### ISSUE TITLE
Getting no data

### ISSUE THREAD

**Issue by mflage** [steepleian/weewx-Weather34#20]
Hi!

I'm not entirely sure I've installed this correctly, but I issued the installer script and after installation I had a subfolder under /var/www/html/weewx called weather34 (this was not clear in any of the documentation - it seemed like this would overwrite/replace the original weewx somehow...?). After restarting weewx I can also see that the w34realtime.txt is updating and I'm getting new data in there. I have pointed my php-enabled web server to that docroot and I am able to load up the page and also perform the configuration of the settings, but I'm getting no data when loading the frontend. All values are at 0. 0 degrees, 0 wind, 0 rain, 0 everything.

How do I debug this? I ran the diag.php script and everything checked out there (it would be nice if the diag.php script also checked the logical stuff - like if data is being read and parsed successfully).

Oh, and btw., there's a typo in the documentation. It says "Browse to http://your/path/to/weewx/weather34/easywxsetup.php ", but the correct scriptname is easyW34skinSetup.php, not easywxsetup.php . 

--
Marius

**Comment by steepleian** [comment]
Hi Marius,

I am sorry you have a problem. First of all the skin install follows the
normal WeeWX convention and becomes a subfolder of weewx so it sounds as
though that part is correct.

Some questions, what method of install did you select when prompted by the
install process and is your web page public facing so I can make a visual
check? What device are you running on and what operating system are you
running.

If you prefer to impart this information just to me, please use my private
email steepleian@gmail.com

Ian

Thanks,
Ian

**Comment by mflage** [comment]
Hi Ian,

thank you for your swift response!

I used the distributed one, the one based on the debian installation of WeeWX. I'm running off a Pi4. The way I expose the web page is through a nginx container with php fastcgi off another container. I realize this is not a standard installation, but it *should* still work? I have pointed to the relative path inside the docker container for the w43realtime.txt and so on.

Unfortunately the page is not currently public - I am looking to make it public once I have gotten all this up and running. But it looks like this:

![image](https://user-images.githubusercontent.com/837316/80862618-a9bd3380-8c76-11ea-9ab0-a69960bf52bf.png)

**Comment by steepleian** [comment]
Hi Marius,
Given your setup I would hazard a guess at permissions and ownership being
the issue. The quickest way to check this would be to change ownership and
permission to www-data on everything. I am afraid I am not an  Nginx user.
I tried it but found it rather fiddly to setup. I use Apache on all my
servers. The one that runs the public facing one is on a Pi4. I am also
running a Pi3 and Pi2 on my internal network, all serving WeeWX with Apache
without issue.

Just one further question, when did you download the skin as there have
been a couple of small updates in the past week.

Ian

**Comment by mflage** [comment]
Hi again,

I also attempted with running Apache and got the same response. Basically no data.

The only non-200 in the logs are these two:

```
192.168.99.93 - - [03/May/2020:08:50:34 +0000] "GET /css/transparent.gif HTTP/1.1" 404 490 "http://10.9.0.201:8082/css/main.dark.css?version=1588371546" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
192.168.99.93 - - [03/May/2020:08:50:34 +0000] "GET /css/sub2.svg HTTP/1.1" 404 490 "http://10.9.0.201:8082/css/main.dark.css?version=1588371546" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
```

I see there's also another issue mentioning the same: #21 but I don't know if that submitter has the same problem with no data..?

**Comment by steepleian** [comment]
Hi Marius,
That is something left over from the original code I inherited. I get the
same thing but appears to have no critical effect. It appears that it was
used to correct an issue with IE10 browser. The other user’s main problem
is to do with the complexities of installing on a MAC.

Forgive me if I am asking an obvious question but do you have all the
associated PHP libraries as outlined in the installation guide?

Can you also check that you have the very latest archivedata.php.tmpl
installed. Quickest way is hit the raw button in the repository, select,
copy and paste to your copy.

**Comment by mflage** [comment]
I see archivedata.php.tmpl in the source code from git and I also found it in the skins directory of /etc/weewx . Could it be some inheritance issue here? Should the document root of the webserver point to the weewx folder instead of the weewx/weather34 folder?

**Comment by mflage** [comment]
There's definitely something I've missed here. Just for the fun of it I copied /etc/weewx/skins/Weather34/archivedata.php to /var/www/html/weewx/weather34/archivedata.php just to force something to happen, but this generated a error 500 (but nothing showed in error.log..?). After deleting the file it took several refresh of the page to get it to load again - what is going on here?

And also, what is the difference between /etc/weewx/skins/skins/Weather34/ and /etc/weewx/skins/Weather34/ ..? It seems highly confusing to have both, especially since the files aren't identical:

```
# diff -u archivedata.php.tmpl ../../Weather34/archivedata.php.tmpl
--- archivedata.php.tmpl        2020-05-02 00:19:06.000000000 +0200
+++ ../../Weather34/archivedata.php.tmpl        2020-05-02 00:19:06.000000000 +0200
@@ -265,7 +265,7 @@
 $weewxapi[169] = "$yesterday.outHumidity.min.format(add_label=False, $localize=False)";
 $weewxapi[170] = "$yesterday.outHumidity.mintime.format(format_string="%Y%m%d%H%M%S")";
 $weewxapi[200] = "$current.windrun.format(add_label=False, $localize=False)";
-$weewxapi[201] = "$span($time_delta=600).windGust.max.format(add_label=False, $localize=False)";
+$weewxapi[201] = "$span($time_delta=600).windSpeed.max.format(add_label=False, $localize=False)";

     $startcivil = "$almanac(horizon=-6).sun(use_center=1).rise.raw";
     $endcivil = "$almanac(horizon=-6).sun(use_center=1).set.raw";
@@ -277,7 +277,7 @@
        $alltimemaxrainrate = "$alltime.rainRate.max.format(add_label=False, $localize=False)";
        $alltimemaxrainratetime = "$alltime.rainRate.maxtime.format(format_string="%Y%m%d%H%M%S")";

-    $pm25 = "$span($hour_delta=24).pm2_5.avg.format(add_label=False, $localize=False)";
+

        $yesterdaymaxwind = "$yesterday.windSpeed.max.format(add_label=False, $localize=False)";
        $yesterdaymaxwindtime = "$yesterday.windSpeed.maxtime.format(format_string="%Y%m%d%H%M%S")";
```

**Comment by steepleian** [comment]
Hi Marius,

You are going horribly wrong. Unfortunately I can’t do much at the moment
as my neighbour has just had a stroke.

I will try and catchup tomorrow if that’s ok with you. Hope you understand
my priorities at the moment.

Thanks
Ian

**Comment by balloonhotair** [comment]
Hi Marius,
I maybe able to help here while Ian is away. First you should not have a ....skins/skins.... directory.
Not sure how you got this but their should only be a /etc/weewx/skins/Weather34 directory. For now I rename the /etc/weewx/skins/skins/.... to /etc/weewx/bad_skins/skins....
Thanks Jerry

**Comment by mflage** [comment]
> Hi Marius,
> I maybe able to help here while Ian is away. First you should not have a ....skins/skins.... directory.
> Not sure how you got this but their should only be a /etc/weewx/skins/Weather34 directory. For now I rename the /etc/weewx/skins/skins/.... to /etc/weewx/bad_skins/skins....
> Thanks Jerry

Hehe, I have no idea either. But this is not something I've done, so I suspect this has happened with the installer. I've moved the offenting skins folder out of the way, but to no avail. I'm still not getting any date. But what I DO see is that the archive data is there, I can see the weekly, monthly and yearly stats, but not the realtime.

**Comment by balloonhotair** [comment]
Hi Marius,
Ok this is a start. In the directory /var/www/html/weewx/weather34 do you have a file called realtime.txt? If so what does ls -l realtime.txt output.
Thanks Jerry

**Comment by steepleian** [comment]
Hi Jerry,
In his version it will be w34realtime.txt

**Comment by mflage** [comment]
> Hi Marius,
> Ok this is a start. In the directory /var/www/html/weewx/weather34 do you have a file called realtime.txt? If so what does ls -l realtime.txt output.
> Thanks Jerry

Hi, and thanks for contributing :)

I believe we've been over this before, but here it is again:

```
$ ls -l w34realtime.txt
-rwxr-xr-x 1 www-data www-data 252 May  4 20:05 w34realtime.txt
```

**Comment by balloonhotair** [comment]
Hi Marius,
This shows that the file is being updated and has a size. and correct privs and ownership. Now need to know what is in the file. Please cat the file and post the contents.
Thanks Jerry

**Comment by mflage** [comment]
`04/05/20 20:45:25 4.5 71 -0.3 2.9 1.8 336 0.0 0.6 1010.2 NNW 1 m/s C mb mm 63.6 1.6 1.0 32.6 0.4 22.3 26 3.0 0.7 6.7 11:35 1.2 01:40 4.0 14:55 7.2 20:25 1010.2 20:40 1003.1 00:45 3.9.2 0 5.4 4.5 4.5 NULL 0.0 NULL 315 0.0 0 1 0 NW 604 m 1.2 17.9 NULL 0`

I believe the solution has to be related to the script w34CombinedData.php:

```php
//weewx - api December 2019

        include('archivedata.php');
```

This attempts to include "archivedata.php", but this file is nowhere to be found. The closest to this is the file archivedata.php.tmpl inside the skins folder for Weather34, but shouldn't this be copied into the main folder or otherwise be included? I don't see how that php code can be able to include archivedata.php since the file is not there.

**Comment by balloonhotair** [comment]
Hi Marius,
Cheetah engine uses the tmpl file to create the archivedata.php file in your weather34 directory and then w34Combine... brings all the data together. (realtime and archivedata). So now I know you have realtime data so now to look at the Cheetah part. So to do that first I need to know  is weewx running as root? Second need to see the skins.conf file in the skins/Weather34 directory. Once I have this info we can see that to do next.
Thanks Jerry

**Comment by balloonhotair** [comment]
Hi Marius,
Also please verify there are no Cheetah or weewx errors in the syslog.
Thanks jerry

**Comment by mflage** [comment]
Aha!

```
May  5 00:10:23 raspberrypi weewx[30223]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.cheetahgenerator.Extras', 'user.stats.MyStats', 'user.lastrain.lastRainTags']
May  5 00:10:23 raspberrypi weewx[30223]: manager: Daily summary version is 2.0
May  5 00:10:23 raspberrypi weewx[30223]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
May  5 00:10:23 raspberrypi weewx[30223]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Weather34/archivedata.php.tmpl
May  5 00:10:23 raspberrypi weewx[30223]: cheetahgenerator: **** Reason: cannot find 'sun' while searching for 'almanac.sun.set.raw'
May  5 00:10:23 raspberrypi weewx[30223]: ****  Traceback (most recent call last):
May  5 00:10:23 raspberrypi weewx[30223]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
May  5 00:10:23 raspberrypi weewx[30223]: ****      fd.write(str(compiled_template))
May  5 00:10:23 raspberrypi weewx[30223]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1045, in __str__
May  5 00:10:23 raspberrypi weewx[30223]: ****      rc = getattr(self, mainMethName)()
May  5 00:10:23 raspberrypi weewx[30223]: ****    File "_etc_weewx_skins_Weather34_archivedata_php_tmpl.py", line 2747, in respond
May  5 00:10:23 raspberrypi weewx[30223]: ****  NotFound: cannot find 'sun' while searching for 'almanac.sun.set.raw'
May  5 00:10:23 raspberrypi weewx[30223]: cheetahgenerator: Generated 0 files for report Weather34Report in 0.01 seconds
```

Do I need to use some cloud services to get this skin to work?

**Comment by steepleian** [comment]
Marius,
It looks like you have not installed py ephem, or have the wrong version
running. It cannot find the

almanac.sun.set.raw tag and the generation of archivedata.php fails to complete.

Checkout the instructions for the Debian install depending on whether you
are running Python2 or Python3

**Comment by steepleian** [comment]
Hi Marius,

Following from last night.

It’s sudo apt install python3-ephem if you are using Python3 with WeeWX
4.0.0 only.

If you are using Python2 with WeeWX 4.0.0 or earlier sudo apt install
python-ephem should work fine. If not try the installation guide version.
Let me know which works for you and I will update the guidelines
accordingly.

Thanks
Ian

**Comment by mflage** [comment]
Yes! That did the trick. I had installed that module for python 3, but not for python 2 (which is the default system python). After that everything works as expected :) A tip in the documentation could be to do 'env python' or something to get the correct version you have running. I had to also install pip for version 2, as I mainly was focusing on python 3 in the Pi.

I think I should provide something back to this project now, so I have started fixing the translation for the Norwegian language and also adding some more language strings to some parts of the UI that is not currently translated. I have forked the repo, so I will probably come with a PR in a bit. Thanks! :)

**Comment by steepleian** [comment]
Marius,
That's great news. It is often a very simple solution but difficult to
find. Thank you for your perseverance and thank you for your offer to
update the Norwegian translation. I also have a volunteer doing the same
for French. The one thing to remember is to try and keep the size of the
words and phrases to a similar length as the English using acceptable
abbreviations if necessary. I will create a branch for you from which to
work with. I will update the installation guide now that we know exactly
what WeeWX 4 requirements are. Can you confirm that sudo apt install
python-ephem worked for you.
Thanks,
Ian

**Comment by mflage** [comment]
I installed through pip, so: `sudo python2 -m pip install pyephem`
