### ISSUE TITLE
Timeout on remote server after initial install

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#21]
Now that I've tried to update to the new version I have come across a problem.
The setup all seems to go fine, the remote stuff was all working before so nothing has changed as far as server settings.
Note that while I am updating, I've started from scratch.  Clean remote and weewx side of all previous weather34 files.
However, when I go to the website (weather34/index.php) to do the initial web setup it stalls and the web server timesout.

The log on the web server end isn't terribly helpful but here it is:

2021-02-24 16:59:43 | Error | my.ip.address.now | 500 | GET /weather34/ HTTP/1.0 |   |   | 1.73 K | Apache SSL/TLS access
-- | -- | -- | -- | -- | -- | -- | -- | --
2021-02-24 17:00:03 | Access | my.ip.address.now | 200 | GET /favicon.ico HTTP/1.0 |   |   | 1.56 K | Apache SSL/TLS access
2021-02-24 17:00:03 | Warning | my.ip.address.now |   | mod_fcgid: read data timeout in 20 seconds, referer: https://www.alberniweather.ca/ |   |   |   | Apache error
2021-02-24 17:00:03 | Error | my.ip.address.now |   | End of script output before headers: index.php, referer: https://www.alberniweather.ca/ |   |   |   | Apache error
2021-02-24 17:00:03 | Error | my.ip.address.now |   | 17716#0: *2404480 upstream timed out (110: Connection timed out) while reading response header from upstream

**Comment by balloonhotair** [comment]
What does the syslog show?
What does the browser log show?
All need to see your weewx config without any personal stuff.

**Comment by balloonhotair** [comment]
You are getting a php error.
So will also need to see archivedata.php in the serverdata directory.
There are a number of php files that are loaded by index. We will need to load then one by one in the browser url and see what errors we get in the apache log. I send the files once I know the rest of the system is ok.

**Comment by chrisale** [comment]
I can't access the syslog on the web server. Syslog on the weewx local side is normal.
No browser log entries are generated.
weewx.conf is at default values. I've included the services.txt file I generated from the web tool.
I'll turn on verbose logging on the server so that maybe I can get more information out of php and post anything I find.
archivedata.php appears normal.

[archivedata.php.txt](https://github.com/steepleian/weewx-Weather34/files/6039771/archivedata.php.txt)
[services.txt](https://github.com/steepleian/weewx-Weather34/files/6039759/services.txt)

**Comment by balloonhotair** [comment]
Before we start looking at each file check your settings1.php and see if the following two lines exist. If they do not add them at the bottom of the file.
$theme = isset($theme) ? $theme : "dark";
$theme1 = $theme;

Here are the files.
webserver_ip_address.php
common.php
w34CombinedData.php
settings1.php
settings.php

**Comment by chrisale** [comment]
Discovered the issue.  The weewxserverinfo.txt file had the local network IP address of the weewx server rather than the public IP address of my home router.  I never gave weather34 or weewx my local network IP address so it has generated this from somewhere else.
The only place I inserted an IP address during setup was in the "Local Web Server IP Address" field of the services.txt generator page. I gave it my public IP address of my home router.

**Comment by balloonhotair** [comment]
The address is created by weather34.py at startup if the field weewxserver_address is blank in weewx config.

**Comment by chrisale** [comment]
To test, I've changed the weewxserver_address field multiple times in weewx.conf and it is not updating the address in the weewxserverinfo.txt file (on the local weewx machine)

**Comment by chrisale** [comment]
I think I see what is happening now:
#1: The weewxserverinfo.txt file generated on the local weewx machine in the public_html directory is not being updated if weewx.conf is updated for some reason after initial install. So the regular weewx rsync process continues to upload that file to the server because:
#2: HTML_ROOT under [Weather34RealTime] was not set.  Should be set to remote server weather34 html_root path.

Thank you for the help as always!

**Comment by balloonhotair** [comment]
Yep there is a lot of moving parts when doing remote.

**Comment by chrisale** [comment]
Thanks to your help, and thanks to all your work, there are a lot less moving parts!  I've created a tutorial that documents the whole process here:
https://www.chrisalemany.ca/2021/02/24/installing-the-weather34-skin-on-weewx-with-remote-web-server-2021-edition/

I've also included a section on uninstalling the skin if people need to wipe it out and start over.
