### ISSUE TITLE
File Not Found: sub2.svg and transparent.gif

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#21]
While inspecting the javascript console I noticed these two 404 errors when loading the main page.  Both files are reported to be expected in the css directory.  They are not present in the distribution that I can find.

![Screen Shot 2020-05-02 at 12 23 33](https://user-images.githubusercontent.com/1987081/80876556-f0f3f600-8c6f-11ea-8bab-218a4a6264a7.png)
 (image attached)

**Comment by steepleian** [comment]
Chris,
I think this is a hangover from the original code which is no longer used. I have tracked back over several versions and there is no sign. I will try to unravel those two CSS files (no easy task, just take a look) and remove the offending calls.

**Comment by steepleian** [comment]
Update,
They are actually calls to the browser to overcome overrun issues when viewers are using legacy IE10 browser. So I will not remove from the CSS. It should not cause an issue.
