### ISSUE TITLE
Webservices filenames.

### ISSUE THREAD

**Issue by dabrovnijk** [steepleian/weewx-Weather34#21]
In the file: "advisory.php" $json='jsondata/wuforecast.txt';
In the file: "weewx.conf": wu_filename = /var/www/html/weewx/weather34/jsondata/wuforecast.txt
In the file: weewx.conf": services = aq.wu.ki.me.al

Listing the files in the jsondata directory:
**ls** /var/www/html/weewx/weather34/jsondata
al.txt  aq.txt  ki.txt  me.txt  place.holder  wu.txt  

I have to do:
**ln** -s wu.txt wuforecast.txt

And then the wu webservice is working. 

**ls** /var/www/html/weewx/weather34/jsondata
al.txt  aq.txt  ki.txt  me.txt  place.holder  wu.txt  _wuforecast.txt_

I have also made the same for meteoalarm and got it to work by creating a symlink al.txt to meteoalarm.txt and have yet to create symlinks for the other webservices.

**Comment by steepleian** [comment]
Hello,
An apology from me. An update for the next version was inadvertantly applied to this current version. The file in question weather34.py has now been rolled back to the correct version. You have two options either roll back your own version or wait for a day or two when the new version will be released (it is in the final stages of testing). If you subscribe to this repository you will get immediate nofication when the new version 4.0.0 is released.
Sorry for any confusion and extra work that this may have caused you.
Thank you for using this WeeWX skin.
Ian
