### ISSUE TITLE
Weather34 page not loading due to a 500 error

### ISSUE THREAD

**Issue by m90att** [steepleian/weewx-Weather34#21]
Suddenly I have started seeing an internal server error when trying to access my weather station weather34 page. I have not changed any w34 settings or files. (http://littleworthweather.duckdns.org:8080/weewx/weather34/)

It was working fine.  The standard skin and the Belchertown skin work no problem so the issue affects only w34

The browser error console doesn't show too much...
![image](https://user-images.githubusercontent.com/56609577/93468627-30ea0b80-f8e7-11ea-88fd-f9dc53f96b09.png)

Syslog attached
[syslog.zip](https://github.com/steepleian/weewx-Weather34/files/5238966/syslog.zip)

Apache2 error log attached
[error.log](https://github.com/steepleian/weewx-Weather34/files/5238956/error.log)

Weewx debug attached
[weewxdebug.zip](https://github.com/steepleian/weewx-Weather34/files/5238962/weewxdebug.zip)

**Comment by steepleian** [comment]
Matt,
Can you paste the contents of archivedata.php
Thanks
IM

**Comment by m90att** [comment]
Yes, of course...

`<?php
          
            
          
$theme_switch = "light";
$weewxapi[17] = "0.0";
$weewxapi[18] = "1018.0";
$weewxapi[19] = "0.3";
$weewxapi[20] = "247.5";
$weewxapi[21] = "0.0";
$weewxapi[25] = "15.9";
$weewxapi[26] = "16.0";
$weewxapi[27] = "20200917103940";
$weewxapi[28] = "10.9";  
$weewxapi[29] = "20200917073000";
$weewxapi[30] = "0.1";
$weewxapi[31] = "02:25";    
$weewxapi[32] = "4.4";
$weewxapi[33] = "02:21";
$weewxapi[34] = "1018.4";	
$weewxapi[35] = "09:03";
$weewxapi[36] = "1017.2";
$weewxapi[37] = "03:20";
$weewxapi[40] = "0.0";
$weewxapi[41] = "--";
$weewxapi[44] = "0.0";
$weewxapi[46] = "   N/A";
$weewxapi[47] = "0.0";
$weewxapi[48] = "19.9";
$weewxapi[49] = "20200915153407";
$weewxapi[50] = "6.5";
$weewxapi[51] = "20200915153407";
$weewxapi[52] = "18.0";
$weewxapi[53] = "20200916154256";
$weewxapi[54] = "29.2";
$weewxapi[55] = "20200812173606";
$weewxapi[56] = "-6.3";
$weewxapi[57] = "20200321141726";
$weewxapi[58] = "3.0";
$weewxapi[59] = "92";
$weewxapi[60] = "20200917071901";
$weewxapi[61] = "71";
$weewxapi[62] = "20200917103614";
$weewxapi[63] = "13.0";
$weewxapi[64] = "20200917000001";  
$weewxapi[65] = "9.5";
$weewxapi[66] = "20200917084618";
$weewxapi[67] = "15.7";
$weewxapi[68] = "73";
$weewxapi[69] = "10.9";
$weewxapi[70] = "20.9";
$weewxapi[71] = "60";
$weewxapi[72] = "0.0";
$weewxapi[73] = "0.0";
$weewxapi[74] = "$month.lightning_strike_count.sum.format(add_label=False, $localize=False)";	
$weewxapi[75] = "$year.lightning_strike_count.sum.format(add_label=False, $localize=False)";	
$weewxapi[76] = "$day.lightning_strike_count.sum.format(add_label=False, $localize=False)";	
$weewxapi[77] = "$year.lightning_distance.lasttime.format(format_string="%Y-%m-%d %H:%M:%S")";
$weewxapi[78] = "N/A";	
$weewxapi[79] = "N/A";
$weewxapi[80] = "194";
$weewxapi[81] = "63946";
$weewxapi[82] = "25.1";
$weewxapi[83] = "20200916140905";
$weewxapi[84] = "14.6";
$weewxapi[85] = "20200916072906";
$weewxapi[86] = "28.3";
$weewxapi[87] = "20200915151907";
$weewxapi[88] = "7.5";
$weewxapi[89] = "20200910072909";
$weewxapi[90] = "36.2";
$weewxapi[91] = "20200811163007";
$weewxapi[92] = "-2.9";
$weewxapi[93] = "20200206080313";
$weewxapi[94] = "8.9";
$weewxapi[95] = "20200916175106";
$weewxapi[96] = "8.9";
$weewxapi[97] = "20200916175106";
$weewxapi[98] = "21.2";
$weewxapi[99] = "20200209072043";
$weewxapi[100] = "0.0";
$weewxapi[101] = "1.2";
$weewxapi[102] = "20200903113556";
$weewxapi[103] = "30.0";
$weewxapi[104] = "20200725135948";
$weewxapi[105] = "194";
$weewxapi[106] = "20200917103908";
$weewxapi[107] = "600";
$weewxapi[108] = "20200916135906";
$weewxapi[109] = "885";
$weewxapi[110] = "20200901145556";
$weewxapi[111] = "603391";
$weewxapi[112] = "20200615123107";
$weewxapi[113] = "20200917095316";
$weewxapi[114] = "6.0";
$weewxapi[115] = "20200916111906";
$weewxapi[116] = "11.0";
$weewxapi[117] = "20200901122256"; 
$weewxapi[118] = "19.0";
$weewxapi[119] = "20200702122727";
$weewxapi[120] = "13.0";
$weewxapi[121] = "20200916235239";
$weewxapi[122] = "20200917104000";
$weewxapi[123] = "15.1";
$weewxapi[124] = "20200903113456";
$weewxapi[125] = "36.2";
$weewxapi[126] = "20200811163007";
$weewxapi[127] = "-4.3";
$weewxapi[128] = "20190131074657";
$weewxapi[129] = "29.2";
$weewxapi[130] = "20200812173606";
$weewxapi[131] = "-6.3";
$weewxapi[132] = "20200321141726";
$weewxapi[133] = "21.2";
$weewxapi[134] = "20200209072043";
$weewxapi[135] = "1017.7";
$weewxapi[136] = "20200916234319";
$weewxapi[137] = "1009.2";
$weewxapi[138] = "20200916004906";
$weewxapi[139] = "1020.8";	
$weewxapi[140] = "20200905110902";
$weewxapi[141] = "1003.9";	
$weewxapi[142] = "20200912031408";
$weewxapi[143] = "1046.2";	
$weewxapi[144] = "20200120095726";
$weewxapi[145] = "981.2";	
$weewxapi[146] = "20200229050114";
$weewxapi[147] = "1046.2";		
$weewxapi[148] = "20200120095726";
$weewxapi[149] = "971.3";
$weewxapi[150] = "20191221204336";
$weewxapi[151] = "1014.9";
$weewxapi[152] = "13.0";
$weewxapi[153] = "0";
$weewxapi[154] = "0";
$weewxapi[155] = "12:31";
$weewxapi[156] = "06:15";
$weewxapi[157] = "19:47";
$weewxapi[158] = "0.0";
$weewxapi[159] = "97";
$weewxapi[160] = "20200903123456";
$weewxapi[161] = "38";
$weewxapi[162] = "20200914142407";
$weewxapi[163] = "99";
$weewxapi[164] = "20200115021901";	
$weewxapi[165] = "26";	
$weewxapi[166] = "20200325150225";
$weewxapi[167] = "93";
$weewxapi[168] = "20200916072906";
$weewxapi[169] = "57";	
$weewxapi[170] = "20200916132905";  
$weewxapi[200] = "0.0";
$weewxapi[201] = "1.1";
$weewxapi[202] = "0.0";
$weewxapi[203] = "743";
$weewxapi[204] = "14";
$startcivil = "1600319406.4";
$endcivil = "1600368586.19";
$rain_year_start = "Jan -";
$rain_year_end = "Dec";	
$daymaxrainrate = "0.0";
$daymaxrainratetime = "20200917000001";
$yesterdaymaxrainratetime = "20200916000406";
$alltimemaxrainrate = "39.6";
$alltimemaxrainratetime = "20180531205725";
$yesterdaymaxwind = "0.5";
$yesterdaymaxwindtime = "20200916172500";
$monthmaxwind = "3.3";
$monthmaxwindtime = "20200905141301";
$yearmaxwind = "11.3";
$yearmaxwindtime = "20200209143943";
?>

`

**Comment by balloonhotair** [comment]
Hi,
Change
$weewxapi[74] = "$month.lightning_strike_count.sum.format(add_label=False, $localize=False)";
$weewxapi[75] = "$year.lightning_strike_count.sum.format(add_label=False, $localize=False)";
$weewxapi[76] = "$day.lightning_strike_count.sum.format(add_label=False, $localize=False)";
$weewxapi[77] = "$year.lightning_distance.lasttime.format(format_string="%Y-%m-%d %H:%M:%S")";
to
$weewxapi[74] = "N/A";
$weewxapi[75]= "N/A";
$weewxapi[76]= "N/A";
$weewxapi[77] = "N/A";
This happens when your system is using an older database.

**Comment by m90att** [comment]
Thank you, that would explain it.  I copied my db from my previous installation over.  Didn't realise it would affect w34.  Thanks for your help, all working now.  Please close this issue.

**Comment by m90att** [comment]
closing per previous comment
