### ISSUE TITLE
4.1.1 Solar radiation almanac still not fully working correctly - yesterday max value wrong

### ISSUE THREAD

**Issue by Gyvate108** [steepleian/weewx-Weather34#22]
while the current year value now appears and appears correctly (the number, date and time were correct before), now (or still - difficult to say) the yesterday number is wrong. The recorded time is correct. It either keeps an earlier yesterday number because it is higher than the current highest, or uses the current month (or year number instead).
I observed this over three days now where the numbers should have been: 415, 378, 419 - but they remain 491
![weewx-w34-wrong-yesterday_20210224-1129](https://user-images.githubusercontent.com/76403541/109121899-252d2b80-7748-11eb-84c8-75350491a0dd.JPG)
![weewx-w34-wrong-yesterday_20210224-1143a](https://user-images.githubusercontent.com/76403541/109121916-28c0b280-7748-11eb-99aa-f16f85a063f5.JPG)
(last picture is not a weewx-w34 picture but a reference)

**Comment by Gyvate108** [comment]
Also, the numbers in the bar chart are wrong since the update to 4.1.0 - 23-Feb is wrong (too low -shows 117 where it should be 378) and 24-Feb is completely missing (on 25-Feb it should show already the 24th) - Weewx in the Seasons skin shows the proper values so it can't be due to a faulty data basis.

**Comment by balloonhotair** [comment]
Need to see the following files. Please post them here.
.../weewx/w34weather/w34highcharts/json/solar_week.json
.../weewx/w34weather/w34highcharts/json/year.json

**Comment by balloonhotair** [comment]
The yesterday issue was a typo in the file w34solaralmanac.php which has been corrected in the repository. 
But the bar chart issue still requires the above two files.

**Comment by Gyvate108** [comment]
confirm - it's working now - and the bar chart also shows the proper values now
