### ISSUE TITLE
Weather34 TimesOut if weewx server not online?

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#23]
I just restarted my iMac into Windows to do some other things and went to check my weather website and the weathe34 page returned a timeout.  As soon as I restarted and turned on weewx the weathe34 skin was live again. This is new behaviour as with the previous version of the string, the page had no problem display while the weewx server was down. Thoughts?  Not sure how to troubleshoot this.  All I get from the remote web server is a timeout error in php.

**Comment by balloonhotair** [comment]
Well that is different but with the exception of day plots there is no dependency for the web page template to have a running weewx system. If fact I have that all the time and I just tested stopping weewx and the template displayed just fine with the frozen data. There has to be something unique with your setup. Was the error a 404 or something else?

**Comment by chrisale** [comment]
I've done it multiple times now.  Weather34 is fine if just the weewx process is not running, but as soon as the computer itself is no longer available, the web interface dies. My Windows instance still uses the same IP address as my Mac instance so it must be calling home and not getting a response it likes?

**Comment by balloonhotair** [comment]
One other thing webserver_ip_address.php verifies that the weewx ip address is valid in weewxserverinfo.txt. The code is protected by a try catch and just logs an error to the apache error log if a quick connect fails.  This code has been in place for a while, and the only change to it was to fix a path error. So it now looks like there is a typo in the error message that must be causing the php to throw a 500 error. It is now corrected in both branches

**Comment by chrisale** [comment]
I've updated the code in webserver_ip_address.php. Unfortunately no change in behaviour. Remote web page still times out if the weewx server is offline.

**Comment by chrisale** [comment]
Looks like I didnt fully clear my cache when I re-tested after the patch. Looks like it is failing gracefully again! Reports "offline" when local weewx server is offline.

**Comment by balloonhotair** [comment]
Ok, but just to make sure I added a 2 second timeout to the socket connect. Changes in both branches.
