### ISSUE TITLE
Remove dependency on dark sky?

### ISSUE THREAD

**Issue by sammargh** [steepleian/weewx-Weather34#23]
It'd be nice if there was an option to disable dark sky api polling. Being new to weather stations I've just started signing up for the various APIs and have come to find that Dark Sky is not accepting new users and is being discontinued in 2021.

I was able to modify the code locally to poll a different api to dump into darksky.txt so my logs would stop filling up but it'd be nice to turn this off completely. The skin works fine without dark sky with the exception of hourly forecasting so it's not the end of the world if there isn't a full replacement yet.

**Comment by balloonhotair** [comment]
Hi,
Got to settings1.php in the weather34 directory find the line.
 services = ds.me.eq.ki.al (or something like this)
remove the ds.
 services = me.eq.ki.al
restart weewx

**Comment by steepleian** [comment]
In your weather34 folder you will find a file settings1.php. Around line
135 you will see something like $services = 'ds.me.eq.ki.wu.aq.al.ah.ao.aa';

This is the web services selection string. Just remove ds. from the front
of the string.

Restart WeeWX and DarkSky API will be disabled.

**Comment by steepleian** [comment]
Snap!
