### ISSUE TITLE
Forecast Module CSS

### ISSUE THREAD

**Issue by steepleian** [steepleian/weewx-Weather34#24]
Thank you Jerry!  Also did you see my last question about the Forcast block?

_Originally posted by @sthostetler in https://github.com/steepleian/weewx-Weather34/issues/23#issuecomment-625424209_

**Comment by steepleian** [comment]
Hi,
Yes I did. All the css in the css directory that reside in the weather34 directory within two files for light and dark.
I look at your page on chrome and the forecast section look fine, so what browser are you using?
Thanks jerry

_Originally posted by @balloonhotair in https://github.com/steepleian/weewx-Weather34/issues/23#issuecomment-625427928_

**Comment by steepleian** [comment]
Chrome.  The image for the forecast especially the lighting runs into the text below.

_Originally posted by @sthostetler in https://github.com/steepleian/weewx-Weather34/issues/23#issuecomment-625429390_

**Comment by steepleian** [comment]
Hi,
The css stuff was part of the template that Ian received when he took it up so we do not work in it much but there are entries for lightning dealing with size that should fix the issue. Since there is no lightning in the forecast right now will have to wait until there is to test which css entry needs adjustment.
Thanks Jerry

_Originally posted by @balloonhotair in https://github.com/steepleian/weewx-Weather34/issues/23#issuecomment-625434811_

**Comment by sthostetler** [comment]
If you guys take a look today we have rain in the forecast and it shows the problem.

Thanks

**Comment by sthostetler** [comment]
Also Edge looks good I have not checked it in Firefox.  Internet Explorer shows it all out of order on the forecast..

Thanks

**Comment by steepleian** [comment]
Hi,

Not surprised by IE its a total mess, always go for Edge.

Until we can get to fix it (original CSS is somewhat complicated), if you
go to your settings page and choose the forecast3wu.php option for position
6, it will keep your website tidy for the time being.
