### ISSUE TITLE
weather34 for Weewx Install issue

### ISSUE THREAD

**Issue by stevemckean1066** [steepleian/weewx-Weather34#27]
Hi Team
I have plugged away at this for a day to try and figure it out.
Installed Weewx with Davis VP2 all works fine and outputs to the standard html template
http://www.blue19.com/weewx/

Trouble started when I tried to install the Weather34 template / skin

Did the:

  sudo git clone https://github.com/steepleian/weewx-Weather34.git
  cd weewx-Weather34
  sudo python w34_installer.py

returned:

pi@raspberrypi:~/weewx-Weather34 $ sudo python w34_installer.py
1 -> setup_py.conf
2 -> packaged.conf
3 -> macos.conf
Enter the NUMBER of the installer config file Enter the NUMBER of the installer config file

Pressed 1 got:

Enter the NUMBER of the installer config file 1
0

then tried again and then chose option 2

got this

Enter the NUMBER of the installer config file 2
Installer Config file setup_py.conf was chosen.
can't copy '/home/weewx/weewx.conf': doesn't exist or not a regular file

As far as I know WEEWX installed into default Dir's ...... I installed via 

'Tell your system to trust weewx.com:
wget -qO - http://weewx.com/keys.html | sudo apt-key add -
For Debian10 and later, use python3:
wget -qO - http://weewx.com/apt/weewx-python3.list | sudo tee /etc/apt/sources.list.d/weewx.list"

sudo apt-get update
sudo apt-get install weewx

Where do I start 

Im already running Weather34 so all im really after is realtime file that the VP2 generates at present via Meteo hub (MBrealtimeupload.txt) I want to retire the Meteohub TP_link server and use my pi4 for everything.
http://www.blue19.com/W34

Cheers
in advance
Steve

**Comment by steepleian** [comment]
Hi Steve,

Can you try another git clone. I just updated the installer. It had
reverted to an older copy after a recent merge request. Apologies for that.
I have just tried the update and it worked fine for me.

Thanks,
Ian

**Comment by stevemckean1066** [comment]
Hi Ian

Are you meaning Weewx or The weather 34 skin ?

cheers
steve

⁣Get TypeApp for Android ​

**Comment by steepleian** [comment]
Weather34
