### ISSUE TITLE
Earthquake module does not work

### ISSUE THREAD

**Issue by gleven** [steepleian/weewx-Weather34#27]
I keep getting the following error message when Weewx starts
`ERROR user.weather34: Failed getting web service data. URL: https://www.emsc-csem.org/service/rss/rss.php Header: {'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/534.3'}, Error: can only concatenate str (not "NameError") to str`

I checked my weewx.conf but cannot find anything that i can change in order to fix this.
If i paste the link in a browser, it works fine (https://www.emsc-csem.org/service/rss/rss.php?typ=emsc)

Is there something else i have to check to make this work?

**Comment by steepleian** [comment]
Does your weewx.conf look like this: -

 eq_url = https://www.emsc-csem.org/service/rss/rss.php?typ=emsc
    eq_interval = 1800
    eq_xml_data = True

also do you have eq code in your services code string as example below.

services = wu.ki.me.eq.ds

Have you installed the additional python library (see install instructions extract below}

If you are going to use the optional enhancement to convert RSS XML feeds to json data for Web Services, the following Python library must be installed (this is required if you are going to use the RSS XML earthquake data and/or the UK MetOffice Severe Weather Warning RSS XML streams): -

  sudo pip3 install xmltodict (if using Python3.x) or sudo pip install xmltodict (for users still using Python2.x)

**Comment by gleven** [comment]
Got it.
I was actually missing the xmltodict. Must have skipped it somehow.
Thanks
