### ISSUE TITLE
Cloudbase calculator/display  is messed up

### ISSUE THREAD

**Issue by kc7ngc** [steepleian/weewx-Weather34#3]
Code for conversion and display of cloudbase is not correct.  "cloudbase3" is calculated from degrees C and it measured in meters. 

Code in currentconditionsw34.php has a few errors.
(1) if temp-units is C it shows text for "ft" (but shows meter values)
(2) if temp-units is F is shows text for "m" (but shows feet values)
(3) the > and <  numbers are reversed.  > and < 1999 should be on feet, greater/less than 609 on meters.  As 609 meters ~= 1999 feet.
(4) since cloudbase3 is in meters you multiply it by 3.28084 to get feet. (you would multiple feet by 0.3048 to get meters, so just have math backward on feet conversion)

So original looks like this in currentconditionsw34.php:

`if ($weather['temp_units']=='C' && $weather["cloudbase3"]>=1999){echo "<div class=cloudconvertercircle2000>Clouds<tyellow> ".round($weather["cloudbase3"])."</tyellow><smalltempunit2> ft</tblue><smalltempunit2>" ;}
else if ($weather['temp_units']=='C' && $weather["cloudbase3"]<1999){echo "<div class=cloudconvertercircle>Clouds<tblue> ".round($weather["cloudbase3"])."</tblue><smalltempunit2> ft</tblue><smalltempunit2>" ;}
else if ($weather['temp_units']=='F' && $weather["cloudbase3"]*0.3048>=609){echo "<div class=cloudconvertercircle2000>Clouds<tyellow> ".round($weather["cloudbase3"]*0.3048,0)."</tyellow><smalltempunit2> m<smalltempunit2>" ;}
else if ($weather['temp_units']=='F' && $weather["cloudbase3"]*0.3048<609){echo "<div class=cloudconvertercircle>Clouds<tblue> ".round($weather["cloudbase3"]*0.3048,0)."</tblue><smalltempunit2> m</tblue><smalltempunit2>" ;}
`

fixed:
`if ($weather['temp_units']=='C' && $weather["cloudbase3"]>=609){echo "<div class=cloudconvertercircle2000>Clouds<tyellow> ".round($weather["cloudbase3"])."</tyellow><smalltempunit2> m</tblue><smalltempunit2>" ;}
else if ($weather['temp_units']=='C' && $weather["cloudbase3"]<609){echo "<div class=cloudconvertercircle>Clouds<tblue> ".round($weather["cloudbase3"])."</tblue><smalltempunit2> m</tblue><smalltempunit2>" ;}
else if ($weather['temp_units']=='F' && $weather["cloudbase3"]*3.28084>=1999){echo "<div class=cloudconvertercircle2000>Clouds<tyellow> ".round($weather["cloudbase3"]*3.28084,0)."</tyellow><smalltempunit2> ft<smalltempunit2>" ;}
else if ($weather['temp_units']=='F' && $weather["cloudbase3"]*3.28084<1999){echo "<div class=cloudconvertercircle>Clouds<tblue> ".round($weather["cloudbase3"]*3.28084,0)."</tblue><smalltempunit2> ft</tblue><smalltempunit2>" ;}
`

**Comment by steepleian** [comment]
Fixed
Thanks go to kc7ngc

**Comment by kc7ngc** [comment]
Ok, I am an idiot.   For a couple of reasons, one being that I believe the internet, and the other being I was trying to do math.

My "fix" made things worse because I misunderstood the calculation.   Short version, its not meters its feet.

After talking with a pilot friend this morning about the cloudbase stuff he pointed out that pilots always deal in feet not meters so he thought it was odd that was a function for cloudbase had an output of meters.

So went back to check my sourcing. The forums i was referencing for information have it wrong in numerous places.  Many inconsistencies and users applying incorrect units to the functions.   Which led me to wrong conclusion, which meant my fix was wrong.

Going back to something more definitive I found that the result of the function is actually really in feet as my friend suggested.
https://en.wikipedia.org/wiki/Cloud_base
(Temp-Dew)/2.4444*1000FT = Cloudbase in Feet

So, about the code:

The original cloudbase3 numbers were correct just where showing up at wrong time due to the if/then tests.   The actual problem was that the =="F" and =="C" were reversed on their sections.   So when unit was F was showing results in meters and when unit was C was showing feet.   So a simple swap of C and F was all it took to fix the original code.   All my other mangling was unnecessary.   Guess there is a reason why there is a git blame.   So with that simple change to original code would look like this with F and C swapped.

`if ($weather['temp_units']=='F' && $weather["cloudbase3"]>=1999){echo "<div class=cloudconvertercircle2000>Clouds<tyellow> ".round($weather["cloudbase3"])."</tyellow><smalltempunit2> ft</tblue><smalltempunit2>" ;}
else if ($weather['temp_units']=='F' && $weather["cloudbase3"]<1999){echo "<div class=cloudconvertercircle>Clouds<tblue> ".round($weather["cloudbase3"])."</tblue><smalltempunit2> ft</tblue><smalltempunit2>" ;} 
else if ($weather['temp_units']=='C' && $weather["cloudbase3"]*0.3048>=609){echo "<div class=cloudconvertercircle2000>Clouds<tyellow> ".round($weather["cloudbase3"]*0.3048,0)."</tyellow><smalltempunit2> m<smalltempunit2>" ;} 
else if ($weather['temp_units']=='C' && $weather["cloudbase3"]*0.3048<609){echo "<div class=cloudconvertercircle>Clouds<tblue> ".round($weather["cloudbase3"]*0.3048,0)."</tblue><smalltempunit2> m</tblue><smalltempunit2>" ;}`

My apologies.  In the future will refrain from filing issues late at night or around anything that involves math.
