### ISSUE TITLE
Configure for Remote Server

### ISSUE THREAD

**Issue by gand07** [steepleian/weewx-Weather34#35]
Hi

I'm trying to confugure for upload to remote server and I have a question. In the stanza:
**[Weather34RealTime]**
there is a field called
**weewx_file_transfer =** 

I can't find anything about what to insert here. I have read this excellent [guide](https://www.chrisalemany.ca/2021/02/24/installing-the-weather34-skin-on-weewx-with-remote-web-server-2021-edition/), but can't find any answer

BTW, why not include a link to the guide in the REMOTE_SERVER.md at the Git

Thanks

Rgds
Gert

**Comment by balloonhotair** [comment]
You can leave it blank.

**Comment by chrisale** [comment]
Hi Gert,
Yes, I have it blank. I'll add a mention to it in my guide. Thank you for the complement.
Chris

**Comment by steepleian** [comment]
Links to remote setup guides added to installation instructions
