### ISSUE TITLE
Data is not populating web page

### ISSUE THREAD

**Issue by tjscientist** [steepleian/weewx-Weather34#36]
![image](https://user-images.githubusercontent.com/22815453/112138954-865de880-8ba8-11eb-826c-1f3987bd329b.png)

**Comment by tjscientist** [comment]
![image](https://user-images.githubusercontent.com/22815453/112139182-db016380-8ba8-11eb-958e-75b1a101b8e1.png)

**Comment by tjscientist** [comment]
[weewx.debug.txt](https://github.com/steepleian/weewx-Weather34/files/6189289/weewx.debug.txt)

**Comment by tjscientist** [comment]
[myTail.txt](https://github.com/steepleian/weewx-Weather34/files/6189341/myTail.txt)

**Comment by balloonhotair** [comment]
Please follow the install instructions you have missed this step not what other steps were missed.
  sudo apt install python2-ephem or sudo apt install python3-ephem

**Comment by tjscientist** [comment]
@balloonhotair I thought I did that but as you pointed out, I missed it. Thanks for the help!!!

**Comment by steepleian** [comment]
Can you please also check that your w34realtime.txt file and archivedata.php file are updating regularly and correctly. You ahould find them in the serverdata folder.

**Comment by tjscientist** [comment]
It is currently working now after I installed python-ephem. Thank you.
