### ISSUE TITLE
WebCam LiveCam link not working

### ISSUE THREAD

**Issue by Rayvenhaus** [steepleian/weewx-Weather34#4]
The webcam module shows the snapshot just fine, however, the link to the live feed fails.

Weather Station: https://wendywx.myndworx.com

Webcam:  http://winniecam.myndworx.com:8795/

Snapshot:  https://wendywx.myndworx.com/webcam/lastsnap.jpg

settings1.php relevant settings:
.....
$position12 = 'weather34uvsolar.php';
$positionlastmoduletitle = 'WeatherCam';
$positionlastmodule = 'webcamsmall.php';
$webcamurl = 'https://wendywx.myndworx.com/webcam/lastsnap.jpg';
$videoWeatherCamURL = 'http://winniecam.myndworx.com:8795/';
....

**Comment by balloonhotair** [comment]
Strange mind works and Ian's also works. When I click on the video links above all I see is a snapshot.  I suspect they are not sending a mpg stream since the streaming is done by the browser not the template.

**Comment by steepleian** [comment]
closing
