### ISSUE TITLE
Most Charts in w34Charts missing Avg/Max/etc values in header/title

### ISSUE THREAD

**Issue by kc7ngc** [steepleian/weewx-Weather34#4]
Issue can be seen in an example image a users uploaded when was talking about their configuration issues on wind units.  Max Gust and Avg are missing in the top header.  Labels are there but not the numbers.

![image](https://user-images.githubusercontent.com/58576041/73766063-58121500-472a-11ea-9bf4-5d0464bcf055.png)

Looking at todaywindspeedgust.php file it's trying to show:
   $weather["wind_gust_speed_max"] and $weather['wind_speed_avg30']
Which aren't defined in that file.  They used to be defined in chartlivedata that used to be included at top of the files in the old version.   

Similar issues across the reports in w34charts.   References to $weather variables that are no longer defined so they aren't showing up in popup window header.

I remedied the issue on my local install by putting  `include('../w34CombinedData.php');` back into the today/month/ year chart files which fixes the issue for me but know that isn't the correct fix.

It would appear you reworked the charts to get rid of including the older chartlivedata file in favor of parsing the csv files from chartdata/ directory.     But that left the orphaned references to variables in the chart file window title bar/header area as they are no longer defined.

Since they are generally things like AVG/MAX/MIN etc I assume they could be derived from the data from the csv file that is already being loaded to display the chart without hitting easy button and backtracking to including the combinedata file?

**Comment by steepleian** [comment]
Opted to replace chartlivedata.php with w34CombinedData.php.
Thank you pointing out the omission.
