### ISSUE TITLE
Many Conditions Not Reporting

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#4]
There are several items no longer shown.
Apparent
°F
Humidity
0%  
Indoor Temp 
Heat Index
°F
Windchill
°F

![wx](https://user-images.githubusercontent.com/12861605/97191535-5b987100-177d-11eb-8e06-33398599d718.png)

**Comment by balloonhotair** [comment]
Need to see the apache2 error log and the browser error log.

**Comment by balloonhotair** [comment]
Also did you do a full update including the weewx parts of weather34. The location of the archivedata.php file has moved to a new serverdata directory that resides in weather34 directory. Do you have this directory?

**Comment by gary-hammer** [comment]
I have left answers and the log on my other issue.
