### ISSUE TITLE
error from installer

### ISSUE THREAD

**Issue by gurusonwheels** [steepleian/weewx-Weather34#4]
sudo python w34_installer.py
Traceback (most recent call last):
  File "w34_installer.py", line 2, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj

what next ?

**Comment by gurusonwheels** [comment]
needed to run 
pip install configobj

**Comment by rkrmpg** [comment]
Having the same error. I believe below shows that configobj is installed. Any other suggestions?

`pi@weather:~ $ dpkg -l   | grep -i configobj`
`ii  python3-configobj                    5.0.6-3                             all          simple but powerful config file reader and writer for Python 3`

`pi@weather:~ $ pip list  | grep -i configobj`
`configobj         5.0.6`

`pi@weather:~ $ pip3 list | grep -i configobj`
`configobj         5.0.6`

**Comment by steepleian** [comment]
Try running the install like this: -

*sudo python3 w34_installer.py*

**Comment by rkrmpg** [comment]
I had tried this before my post with the same results. 
I decided to reboot the Pi and then tried it again and it worked. 

Running into a few other issues with being able to get the index.php page to load on my remote hosted server which I am trying sort out.


> Try running the install like this: - *sudo python3 w34_installer.py*
