### ISSUE TITLE
CheetahGenerator Failed Error

### ISSUE THREAD

**Issue by techfixpros** [steepleian/weewx-Weather34#4]
I am receiving the following error every archive period, since updating to v07:

> Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: cheetahgenerator: Generate failed with exception '<type 'exceptions.TypeError'>'
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Weather34/mbcharts/chartdata/result.csv.tmpl
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: cheetahgenerator: **** Reason: unsupported operand type(s) for +: 'float' and 'NoneType'
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: ****  Traceback (most recent call last):
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 332, in generate
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: ****      fd.write(str(compiled_template))
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: ****      rc = getattr(self, mainMethName)()
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: ****    File "_etc_weewx_skins_Weather34_mbcharts_chartdata_result_csv_tmpl.py", line 250, in respond
Nov 28 19:46:47 john-PS583AA-ABA-a1020n weewx[27533]: ****  TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

WeeWx 3.9.2
Weather34 07

**Comment by steepleian** [comment]
Hey John,

That seems to be a WeeWX error message that I am unfamiliar with. I have
made no changes in the latest version that may have caused it. The .csv
files for the charts are generated from the WeeWX database every archive
cycle. So we can get more expertise to look into it can you post on the
WeeWX user group forum.

Thanks
Ian

**Comment by techfixpros** [comment]
I will do that. Thanks.
