### ISSUE TITLE
Realtime file has different units than configured in the skin

### ISSUE THREAD

**Issue by Hyrules** [steepleian/weewx-Weather34#5]
Weewx 4.1.1
Skin just downloaded from github with git and clone.

I have configured the skin using metric units since I live in Canada. I have set the wind to km/h and pressure to hPa but the result in the realtime file is that the wind is in m/s and the pressure is in mb. Is there something i'm missing ? Only the rain is alright.

![image](https://user-images.githubusercontent.com/3161577/89820298-d062f400-db1a-11ea-9f90-cbbdd6c005a4.png)

`10/08/20 15:05:48 28.9 67 22.1 1.5 0.5 223 0.0 0.0 1018.7 SW 0 m/s C mb mm 42.2 -2.0 101.0 442.9 0.7 NULL NULL NULL 2.8 28.9 15:05 19.2 02:00 2.7 10:50 5.2 11:55 1022.6 04:25 1018.7 15:05 4.1.1 0 4.2 32.0 38.3 4.8 0.1 799 183 0.0 0 1 0 NNE 958 m NULL 9.1 777.8 NULL NULL 0 NULL NULL 3.8`

**Comment by steepleian** [comment]
The base units of the system is METRICWX and is set in the weewx.conf file.
The real-time file generates as this. All conversions are carried out in
the file w34CombinedData.php based on what you select in the settings page.

**Comment by Hyrules** [comment]
Thanks for the quick reply. While I was waiting I was browsing through the code of weather34.py and saw the header. I was able to override the values by adding in the [Weather34RealTime] section of the weewx.conf :

```
    wind_units = km_per_hour
    pressure_units = hPa
    cloudbase_units = meter
    rain_units = mm
```

By the way is there any template or way of making some kind of plugins for the skin ? I would like to make a plugin for the alert section to show Environment Canada alerts. Right now it uses Meteoalarm.eu but they are not covering Canada.

**Comment by steepleian** [comment]
As you are probably aware, DarkSky will be closing their public API next
year for existing users. They are no longer accepting new users. If you
happen to have a DarkSky account, there is a text only alert popup window
in the skin.

Go to line 136 in index.php and change the href from meteoalarmalerts.php
to darkskyalerts.php

In the meantime I am converting from DarkSky to Aeris Weather who have an
alerts API which covers Canada. You can get a free subscription from Aeris
in exchange for sharing your weather data, a fair exchange as far as I am
concerned.

This will be added to the development version of the skin in the next week
or two.

Ian

**Comment by Hyrules** [comment]
Don't use dark sky and never has. Thanks for the tip I will see what Aeris Weather does when the next version of the skin is ready.
