### ISSUE TITLE
Temp Conversion

### ISSUE THREAD

**Issue by rrosson** [steepleian/weewx-Weather34#5]
Living in the U.S. and not using metric to measure temperature it looks like the conversion from metric to imperial is missing values or doing something wrong. My WX is accessible at https://weewx.oneinsane.org.

Please let me know if you have any questions

TIA

**Comment by steepleian** [comment]
To permanently set to US customary units you should select settings from the menu and then select your individual default units from the settings form page. I suspect you may not have done this as when I opened your web page, all units were metric wx. The toggle settings for different units in the menu drop down are purely for the convince of visitors to your website to view in their own preferred units.

**Comment by rrosson** [comment]
I have updated the settings to US (non metric) but a few of the values seem to be off.  Would waiting correct these values??

**Comment by steepleian** [comment]
Check the weather34 reports section in weewx.conf. It must be set to
METRICWX. If not stop weewx, edit and restart.

**Comment by rrosson** [comment]
target_unit was set to US. Changed to METRICWX and performed stop and start.  Crossing fingers.    :)

**Comment by steepleian** [comment]
You appear to be offline. Have you restarted WeeWX?

**Comment by rrosson** [comment]
Should be up and running now. I do not know what had happened

**Comment by steepleian** [comment]
Your station is sending data to WU ok but the skin still showing offline
condition. What is the default WeeWX skin indicating?

**Comment by rrosson** [comment]
It was showing stale data as well.  I think I have it online now but it still seems to show measurements in metric.

Many thanks for taking the time to go back and forth in helping me try to resolve this.

**Comment by steepleian** [comment]
It’s defaulting to US customary as fa as I can see

**Comment by rrosson** [comment]
I reset the weewx database because it was crashing on conversion. It has been running steady for almost 40 minutes. Will look in on it later to see if issue is resolved and if forecast populates.

Again, many thanks for taking the time.

**Comment by steepleian** [comment]
All looking good now including forecast. I will close the issue now. Any more problems, just let me know.
Ian
