### ISSUE TITLE
CRC check failure

### ISSUE THREAD

**Issue by MauroSwiss88** [steepleian/weewx-Weather34#59]
Hi Ian, Hi Jerry

I'm opening this issue thread just to ask you if the skin itself (with his relative drivers) may indirect cause failures on my data logger every then minutes. I have a Davis Vantage Pro2 and I get this in the log:

Apr 26 10:15:09 raspberrypi weewx[15755] ERROR weewx.drivers.vantage: LOOP try #1; error: LOOP buffer failed CRC check
Apr 26 10:15:09 raspberrypi weewx[15755] ERROR weewx.drivers.vantage: LOOP try #2; error: LOOP buffer failed CRC check
Apr 26 10:15:09 raspberrypi weewx[15755] ERROR weewx.drivers.vantage: LOOP try #3; error: LOOP buffer failed CRC check
Apr 26 10:15:09 raspberrypi weewx[15755] ERROR weewx.drivers.vantage: LOOP try #4; error: LOOP buffer failed CRC check
Apr 26 10:15:09 raspberrypi weewx[15755] ERROR weewx.drivers.vantage: LOOP max tries (4) exceeded.
Apr 26 10:15:09 raspberrypi weewx[15755] INFO weewx.engine: Main loop exiting. Shutting engine down.
Apr 26 10:15:09 raspberrypi weewx[15755] INFO weewx.engine: Shutting down StdReport thread
Apr 26 10:15:29 raspberrypi weewx[15755] ERROR weewx.engine: Unable to shut down StdReport thread
Apr 26 10:15:29 raspberrypi weewx[15755] DEBUG weewx.restx: Shut down PWSWeather thread.
Apr 26 10:15:29 raspberrypi weewx[15755] DEBUG weewx.restx: Shut down Wunderground-PWS thread.
Apr 26 10:15:29 raspberrypi weewx[15755] DEBUG weewx.restx: Shut down StationRegistry thread.
Apr 26 10:15:29 raspberrypi weewx[15755] CRITICAL __main__: Caught WeeWxIOError: Max tries exceeded while getting LOOP data.

Tom, the developer of Weewx, told me it could be not a problem of the data logger, but of environment and skin.

Greetings

Mauro

**Comment by steepleian** [comment]
Hi Mauro,

I cannot see how weather34 would affect the problems you are experiencing.
I see that Tom Keffer has a similar opinion to me. You can always check by
disabling weather34 in weewx.conf and see if the problem persists. Also
check your w34realtime.txt file and the /tmp/weather34/RetainedLoopValues.txt
file.

Ian

**Comment by MauroSwiss88** [comment]
The only "strange" thing I see is that in my w34realtime.txt file the last collect date is from yesterday, but the skin was working today too. RetainedLoopValues.txt is working correctly and has today as last received data.

It seems that by by disabling weather34 and w34highcharts in weewx.conf I got no errors (followed the syslog 15 minutes), but I disabled also the StandardReport that is in use for an external source. May this cause incompatibility?


Mauro

**Comment by steepleian** [comment]
Can you send me the link to those two files please? You also need to have the StandardReport running. Are you able to check your database to see what is going in?

**Comment by MauroSwiss88** [comment]
My database collects the data without problems and the strange is that the environment is running without leaks by disabling the StandardReport. Also the Cloud Covering is working well without 0%.

**Comment by steepleian** [comment]
Ok re-enable weather34 and see what happens.

**Comment by MauroSwiss88** [comment]
If I enable weather34 and disable StandardReport I am not getting errors.
If I enable both I get the CRC Errors mentioned above.

So the problem is definitely the StandardReport

This is what is running on the Standard:

https://www.meteopineto.it/Caput/index.html

I can show you my files of the folder that I'm updating via FTP


EDIT: I'm getting the CRC Errors again, but no one if I disable every skin.

EDIT EDIT: Enabled Weather34 again, disabled Standard and FTP. No CRC Errors

So, I think there's definitely something between the skin configurations

**Comment by Leosirth** [comment]
Hi Mauro,

Checking the weewx code here:

https://github.com/weewx/weewx/blob/a3cf8c8fed0cfe005c85fbead68e120359b42405/bin/weewx/drivers/vantage.py#L571

I don't see any interference with the skin implementation.
Can you try to keep all the skins disabled for a while to see if this issue occurs?
Looks like the data gets corrupted in same way from time to time, and the correlation to the standard skin could just be a coincidence.

How is your raspberry connected to davis?
Please have a look also on you cables and your connection.

Best regards,

**Comment by MauroSwiss88** [comment]
Hi,
I’ve already tried to keep all the skins disabled and  there were no issues. Now I’m running the only Weather34 skin and it‘s working fine too. 

My RPi is connected to Davis by a 3rd party USB logger. I’ve contacted the manufacturer and spoke with Tom Keffer too. Both are most sure that the logger itself isn’t the problem.

I have some problems between python2.7 and python3.7.3. This may cause memory leaks. Also my RPi isn’t the newest one with 512 MB RAM. I’

**Comment by balloonhotair** [comment]
So, if you are using python 2.7 and the standard report there is a memory leak reported with using Cheetah and inc files which are used by the standard skin. This issue has been well discussed on the forums. Since your pi only has 512 MB it can be running out of memory.  One way to be sure there is to use the weather34 ml service since that logs in the syslog memory usage each time an archive record is created. Only work arounds are to migrate to python 3.7 with all software versions or do not run standard report or any skin that uses inc files. Weather34 skin does not use inc files.

**Comment by MauroSwiss88** [comment]
Hi Jerry,

Yes, yesterday evening I was talking with Ian about it. I’ve installed WeeWX with the python3 command line, but my RPi still gives me the 2.7 version as default by running the python —version command line.

**Comment by Leosirth** [comment]
Here you can find some ways to make python3 the default:

https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux

**Comment by steepleian** [comment]
Closing as concluded that this is not a Weather34 (or any other skin) issue.
