### ISSUE TITLE
Wind Gust Problem

### ISSUE THREAD

**Issue by Russell797** [steepleian/weewx-Weather34#6]
"wind_gust_speed" is returning the same value as "wind_speed_avg" ( Cheetah - $current.windGust = $current.windSpeed )

In both currentconditionsw34.php and windspeeddirection.php

Max Wind Speed last 10 minutes is fixed at 4.9 mph - never changes

**Comment by steepleian** [comment]
The following files have been updated to fix the problem: -
skins/Weather34/archivedata.php.tmpl
www/w34CombinedData.php
www/currentconditionsw34.php
