### ISSUE TITLE
Installation with "services.txt"

### ISSUE THREAD

**Issue by Byllyy** [steepleian/weewx-Weather34#6]
Hello and thanks for the great work. I'm trying to install from the command line.
The "Services.txt" file is required for this. Where can i find it?
Many Thanks

**Comment by steepleian** [comment]
Hello,

Check the instructions. The first stage is to run the online pre install
process, there is a link in the install instructions. This generates the
services.txt file. Save this and then copy to the the weewx-Weather34
install folder on your device.

Ian
