### ISSUE TITLE
Closed issue still happening

### ISSUE THREAD

**Issue by invidia191** [steepleian/weewx-Weather34#61]
https://github.com/steepleian/weewx-Weather34/issues/8

Still the same problem.

**Comment by steepleian** [comment]
Sorry for the delay in replying. I am away from home at the moment with
limited access for troubleshooting this persistent problem you have.
Hopefully will be back next week. In the meantime, if you can paste your
recent logs here I can see them on my return.
Ian

**Comment by invidia191** [comment]
May  6 00:00:36 raspberrypi weewx[1666] INFO weewx.manager: Added record 2021-05-06 00:00:00 CEST (1620252000) to database 'weewx.sdb'
May  6 00:00:36 raspberrypi weewx[1666] INFO weewx.manager: Added record 2021-05-06 00:00:00 CEST (1620252000) to daily summary in 'weewx.sdb'
May  6 00:00:37 raspberrypi weewx[1666] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 0.95 seconds
May  6 00:00:41 raspberrypi weewx[1666] INFO weewx.imagegenerator: Generated 60 images for report SeasonsReport in 4.63 seconds
May  6 00:00:41 raspberrypi weewx[1666] INFO weewx.reportengine: Copied 0 files to /home/weewx/public_html
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/Weather34/serverdata/archivedata.php.tmpl
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'format' while searching for 'format'
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 326, in generate
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_Weather34_serverdata_archivedata_php_tmpl.py", line 2503, in respond
May  6 00:00:41 raspberrypi weewx[1666] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'format' while searching for 'format'
May  6 00:00:41 raspberrypi weewx[1666] INFO weewx.cheetahgenerator: Generated 0 files for report Weather34Report in 0.02 seconds
May  6 00:00:41 raspberrypi weewx[1666] INFO weewx.reportengine: Copied 0 files to /home/weewx/public_html/weather34/
May  6 00:00:42 raspberrypi weewx[1666] INFO weewx.cheetahgenerator: Generated 6 files for report w34Highcharts in 1.09 seconds
May  6 00:00:42 raspberrypi weewx[1666] INFO weewx.reportengine: Copied 0 files to /home/weewx/public_html/weather34/w34highcharts

**Comment by steepleian** [comment]
We have not been able to replicate this issue at all. However an update has been made to archivedata.php.html that may assist you.
Ian

**Comment by steepleian** [comment]
Closing as no further feedback
