### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by Jmknet** [steepleian/weewx-Weather34#63]
Hi!
Got this error and can´t get my head around it, any one that can hekp me out?

● weewx.service - LSB: weewx weather system
   Loaded: loaded (/etc/init.d/weewx; generated)
   Active: active (running) since Sun 2021-06-13 13:59:06 CEST; 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18306 ExecStart=/etc/init.d/weewx start (code=exited, status=0/SUCCESS)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/weewx.service
           └─18322 python3 /usr/share/weewx/weewxd --daemon --pidfile=/var/run/weewx.pid /etc/weewx/weewx.conf

jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO weewx.restx: CWOP: Posting not enabled.
jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO weewx.restx: WOW: Posting not enabled.
jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO weewx.restx: AWEKAS: Posting not enabled.
jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO __main__: Starting up weewx version 4.5.1
jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO weewx.manager: Starting backfill of daily summaries
jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO weewx.manager: Daily summaries up to date
jun 13 13:59:07 jokkmokk.net python3[18322]: weewx[18322] INFO weewx.engine: Starting main packet loop.
jun 13 13:59:08 jokkmokk.net python3[18322]: weewx[18322] INFO user.weather34: Web Service: wu is running
jun 13 13:59:08 jokkmokk.net python3[18322]: weewx[18322] INFO user.weather34: Web Service: eq is running
root@jokkmokk:/home/pi# service weewx status

● weewx.service - LSB: weewx weather system
   Loaded: loaded (/etc/init.d/weewx; generated)
   Active: active (exited) since Sun 2021-06-13 13:59:06 CEST; 28s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18306 ExecStart=/etc/init.d/weewx start (code=exited, status=0/SUCCESS)

jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 210, in run
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****      callback(event)
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****    File "/usr/share/weewx/user/weather34.py", line 817, in handle_new_loop
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****      self.handle_data(event.packet)
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****    File "/usr/share/weewx/user/weather34.py", line 856, in handle_data
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****      weeutil.weeutil.log_traceback('crt: **** ')
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****  AttributeError: module 'weeutil.weeutil' has no attribute 'log_traceback'
jun 13 13:59:12 jokkmokk.net python3[18322]: weewx[18322] CRITICAL __main__:     ****  Exiting.

**Comment by steepleian** [comment]
Can you run this from the command line and report the result

sudo python —version

**Comment by Jmknet** [comment]
Hi!


***@***.***:/home/pi# python --version
Python 3.8.5


Den sön 13 juni 2021 17:42Ian Millard ***@***.***> skrev:

> Can you run this from the command line and report the result
>
> sudo python —version
>

**Comment by steepleian** [comment]
Had things been running ok before the critical errors occurred? If so, have
you made any recent changes?

If you look in the GitHub repository you will find a trouble shooting
process described. Can you run through that process and paste the various
outputs back here.
Thank you

**Comment by Jmknet** [comment]
Hi!

Only updating like "apt-get dist-upgrade" and after that it stop working
[weewx.debug.zip](https://github.com/steepleian/weewx-Weather34/files/6644284/weewx.debug.zip)

**Comment by steepleian** [comment]
I have not seen errors exactly like that before. Not sure why an upgrade
would have caused anything to break. I keep my test server upgraded all the
time, just to check if there are likely to be potential issues that users
need to be aware of.

**Comment by steepleian** [comment]
Just looking at your seasons skin page. The last update to the home page
was 4 June. Was that when you first hit the problem? Can I suggest that you
disable the Weather34 skin then restart and see if you can get Seasons skin
to work properly in the first instance.

**Comment by balloonhotair** [comment]
Need to know what version of weewx is being run for starters. Also I am sure this is not a weather34.py issue based on what is above since the line number is in in an exception from calling a weewx.  If I had to guess it would be the weewx install has been corrupted.

**Comment by balloonhotair** [comment]
Ok so it is version 4.5.1 so need to see if the log_traceback has been removed from the weewx in this version.

**Comment by balloonhotair** [comment]
Restart weewx with debug=2 in the config to see what the true error was that caused the exception(suspect bad data in the loop packet). Also looks like log_traceback in no longer a function in weewx 4.5 so it can be removed from weather43.py since it really not needed in exception handing anyway.
But the real problem is in the loop data that weewx is processing.

**Comment by steepleian** [comment]
Closing as no recent comments
