### ISSUE TITLE
NOAA and MesoWest Links Incorrect for HAM User

### ISSUE THREAD

**Issue by techfixpros** [steepleian/weewx-Weather34#64]
WeeWx 4.5.1 .deb
weewx-Weather34 W34-HC-IMJD-4.1.3

I changed my CWOP/FindU id earlier this year after having run under a EW**** id for several years. CWOP/FindU remapped my old id to my Ham callsign, and changed NOAA and MesoWest from EW**** to E**** in Feburary this year.

The "Display CWOP Link" and "Display FindU Link" both have my callsign, and the Extra > CWOP, FindU, and MADIS links all work properly. The NOAA and MesoWest links will use my callsign by default, but that fails. Changing the url to have my old E**** id will load correctly.

Please allow for a custom entry, i.e.  'yes':'no':'custom' for NOAA and MesoWest in easyW34skinSetup.php.

For now I have replaced $linkCWOPID with a $linkNOAAID and $linkMesoWestID at their respective places in menu.php for both NOAA and MesoWest links and it is working properly. Working on extending easyW34skinSetup.php and menu.php with custom conditions for $linkNOAAID and $linkMesoWestID entries, and rolling out a pull request.

**Comment by techfixpros** [comment]
Work so far:
easyW34skinSetup.php
>  
    $linkNOAA = "'. $_POST["linkNOAA"]. '";
    $linkNOAAID = "'. $_POST["linkNOAAID"]. '";
    $linkMADIS = "'. $_POST["linkMADIS"]. '";
    $linkMesoWest = "'. $_POST["linkMesoWest"]. '";
    $linkMesoWestID = "'. $_POST["linkMesoWestID"]. '";
    ---
    
    <div class="stationvalue">Display NOAA Link&nbsp;</div>
    <?php echo $rightchevron.$downchevron;?>
    <label name="linkNOAA"></label>
    <select id="linkNOAA" name="linkNOAA" class="choose1">
        <option><?php echo ($linkNOAA?$linkNOAA:'no');?></option>
        <option><?php echo ($linkNOAA=='no'||empty($linkNOAA)?'yes':'no':'custom');?></option>
    </select>
    
    <br/>
    <div class="stationvalue">Custom NOAA ID&nbsp;&nbsp;</div>
    <?php echo $rightchevron;?>
    <label name="linkNOAAID"></label>
    <input name="linkNOAAID" type="text" id="linkNOAAID" value="<?php echo $linkNOAAID;?>" class="choose">
    <span style="color:#777;">(<orange><b>FW0000</b></orange>)</span>
    <br/>
    ---
    
    <div class="stationvalue">Display MesoWest Link</div>
    <?php echo $rightchevron.$downchevron;?>
    <label name="linkMesoWest"></label>
    <select id="linkMesoWest" name="linkMesoWest" class="choose1">
        <option><?php echo ($linkMesoWest?$linkMesoWest:'no');?></option>
        <option><?php echo ($linkMesoWest=='no'||empty($linkMesoWest)?'yes':'no':'custom');?></option>
    </select>
    <br/>
    
    <br/>
    <div class="stationvalue">Custom NOAA ID&nbsp;&nbsp;</div>
    <?php echo $rightchevron;?>
    <label name="linkMesoWestID"></label>
    <input name="linkMesoWestID" type="text" id="linkMesoWestID" value="<?php echo $linkMesoWestID;?>" class="choose">
    <span style="color:#777;">(<orange><b>FW0000</b></orange>)</span>
    <br/>

settings1.default.php

> 
    $linkNOAA = 'no';
    $linkNOAAID = '';
    $linkMADIS = 'no';
    $linkMADISID = "";

**Comment by techfixpros** [comment]
menu.php

>
          <?php if ($linkNOAA == 'yes' && !empty($linkCWOPID))
    { ?>
            <li>
              <a href="https://www.wrh.noaa.gov/mesowest/getobext.php?wfo=lox&sid=<?php echo $linkCWOPID; ?>" title="<?php echo $linkCWOPID; ?> on NOAA Meso West" target="_blank">
                <img class="menuimg" src="img/noaa.svg" style="max-width:30px" alt=""/>
                <?php echo $linkCWOPID; ?> on NOAA
              </a>
            </li>
          <?php
    } ?>
         <?php if ($linkNOAA == 'custom' && !empty($linkNOAAID))
    { ?>
            <li>
              <a href="https://www.wrh.noaa.gov/mesowest/getobext.php?wfo=lox&sid=<?php echo $linkNOAAID; ?>" title="<?php echo $linkNOAAID; ?> on NOAA Meso West" target="_blank">
                <img class="menuimg" src="img/noaa.svg" style="max-width:30px" alt=""/>
                <?php echo $linkNOAAID; ?> on NOAA
              </a>
            </li>
          <?php
    } ?>
    ---
          <?php if ($linkMesoWest == 'yes' && !empty($linkCWOPID))
    { ?>
            <li>
              <a href="https://mesowest.utah.edu/cgi-bin/droman/meso_base.cgi?stn=<?php echo $linkCWOPID; ?>" title="<?php echo $linkCWOPID; ?> on Meso West" target="_blank">
                <img class="menuimg" src="img/mesowest.svg" alt=""/>
                <?php echo $linkCWOPID; ?> on Meso West
              </a>
            </li>
          <?php
    } ?>
          <?php if ($linkMesoWest == 'custom' && !empty(linkMesoWestID))
    { ?>
            <li>
              <a href="https://mesowest.utah.edu/cgi-bin/droman/meso_base.cgi?stn=<?php echo $linkMesoWestID; ?>" title="<?php echo $linkMesoWestID; ?> on Meso West" target="_blank">
                <img class="menuimg" src="img/mesowest.svg" alt=""/>
                <?php echo $linkMesoWestID; ?> on Meso West
              </a>
            </li>
          <?php
    } ?>

**Comment by steepleian** [comment]
Hi John,

Thanks for this. Can you please make a PR to the development branch so that I can verify and merge.

Thank you
Ian

**Comment by techfixpros** [comment]
Done, thank you.

[#65](https://github.com/steepleian/weewx-Weather34/pull/65)

**Comment by steepleian** [comment]
I have updated the Development branch manually as there was a conflict with your PR
