### ISSUE TITLE
No data displaying/rendering issues

### ISSUE THREAD

**Issue by meisnick** [steepleian/weewx-Weather34#66]
Running on RasPi 3 B+ fully updated 07/22/2021
weewx 4.5.1 package install
GW1000 station
W34-HC-IMJD-4.1.3
Apache/2.4.38 (Raspbian)

Followed weewx recipe for [install and GW1000](https://github.com/weewx/weewx/wiki/gw1000-recipe)

After setup services seem to be working, some errors listed below from syslog. WU upload and forcast look correct but icon positions and some page rendering seems off. Verified in Chrome, incognito, and Firefox render the same. 

I included the output from syslog and some raw weewx output below

pi@raspberrypi:~ $ sudo tail -f /var/log/syslog
Jul 22 04:46:54 raspberrypi weewx[1519] INFO user.weather34: Web Service: me is running
Jul 22 04:46:55 raspberrypi weewx[1519] INFO user.weather34: Web Service: wu is running
Jul 22 04:46:55 raspberrypi weewx[1519] INFO user.weather34: Web Service: eq is running
Jul 22 04:46:56 raspberrypi weewx[1519] ERROR user.weather34: Failed getting web service data. URL: https://www.emsccsem.org/service/rss/rss.php?typ=emsc Header: {'User-Agent': 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/534.3'}, Error: coercing to Unicode: need string or buffer, exceptions.NameError found
Jul 22 04:46:56 raspberrypi weewx[1519] INFO user.weather34: Web Service: ki is running
Jul 22 04:47:04 raspberrypi weewx[1519] INFO user.interceptor: using 'totalrainin' for rain_total
Jul 22 04:47:04 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:47:04 raspberrypi weewx[1519] INFO user.interceptor: skipping rain measurement of 7.642: no last rain
Jul 22 04:48:05 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:49:06 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:50:07 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:50:45 raspberrypi systemd[1]: Starting Cleanup of Temporary Directories...
Jul 22 04:50:45 raspberrypi systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Jul 22 04:50:45 raspberrypi systemd[1]: Started Cleanup of Temporary Directories.
Jul 22 04:51:08 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:51:08 raspberrypi weewx[1519] INFO weewx.manager: Added record 2021-07-22 04:50:00 CDT (1626947400) to database 'weewx.sdb'
Jul 22 04:51:08 raspberrypi weewx[1519] INFO weewx.manager: Added record 2021-07-22 04:50:00 CDT (1626947400) to daily summary in 'weewx.sdb'
Jul 22 04:51:09 raspberrypi weewx[1519] INFO weewx.restx: Wunderground-PWS: Published record 2021-07-22 04:50:00 CDT (1626947400)
Jul 22 04:51:12 raspberrypi weewx[1519] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 3.78 seconds
Jul 22 04:51:13 raspberrypi weewx[1519] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 1.00 seconds
Jul 22 04:51:13 raspberrypi weewx[1519] INFO weewx.reportengine: Copied 5 files to /var/www/html/weewx
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Weather34/serverdata/archivedata.php.tmpl
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Weather34_serverdata_archivedata_php_tmpl.py", line 2431, in respond
Jul 22 04:51:14 raspberrypi weewx[1519] ERROR weewx.cheetahgenerator: ****  NotFound: cannot find 'sun' while searching for 'almanac.sun.set.raw'
Jul 22 04:51:14 raspberrypi weewx[1519] INFO weewx.cheetahgenerator: Generated 0 files for report Weather34Report in 0.84 seconds
Jul 22 04:51:14 raspberrypi weewx[1519] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/
Jul 22 04:51:15 raspberrypi weewx[1519] INFO weewx.cheetahgenerator: Generated 7 files for report w34Highcharts in 0.57 seconds
Jul 22 04:51:15 raspberrypi weewx[1519] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/w34highcharts
Jul 22 04:51:19 raspberrypi weewx[1519] ERROR weewx.restx: StationRegistry: Failed to publish record 2021-07-22 04:50:00 CDT (1626947400): Failed upload after 3 tries
Jul 22 04:52:09 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:53:10 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:54:11 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
Jul 22 04:55:12 raspberrypi weewx[1519] INFO user.interceptor: unrecognized parameter wh68batt=1.30
^C
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $ cat /etc/debian_version
10.10
pi@raspberrypi:~ $ apache2 -v
Server version: Apache/2.4.38 (Raspbian)
Server built:   2021-06-10T10:13:06

pi@raspberrypi:~ $ weewxd /etc/weewx/weewx.conf
LOOP:   2021-07-22 05:13:29 CDT (1626948809) altimeter: 30.2720068483, appTemp: 59.1486211746, barometer: 30.2713935075, cloudbase: 1443.04250432, dateTime: 1626948809, dewpoint: 54.990612981, heatindex: 57.337, humidex: 62.4084288291, inDewpoint: 56.3994208118, inHumidity: 64.0, inTemp: 69.1, outHumidity: 91.0, outTemp: 57.6, pressure: 29.353, radiation: 0.0, rain: None, rainRate: 0.0, usUnits: 1, UV: 0.0, windchill: 57.6, windGust: 0.0, windSpeed: 0.0
LOOP:   2021-07-22 05:14:30 CDT (1626948870) altimeter: 30.2720068483, appTemp: 59.1486211746, barometer: 30.2713935075, cloudbase: 1443.04250432, dateTime: 1626948870, dewpoint: 54.990612981, heatindex: 57.337, humidex: 62.4084288291, inDewpoint: 56.5886416457, inHumidity: 64.0, inTemp: 69.3, outHumidity: 91.0, outTemp: 57.6, pressure: 29.353, radiation: 0.0, rain: 0.0, rainRate: 0.0, usUnits: 1, UV: 0.0, windchill: 57.6, windGust: 0.0, windSpeed: 0.0
LOOP:   2021-07-22 05:15:31 CDT (1626948931) altimeter: 30.2750828103, appTemp: 59.1486211746, barometer: 30.2744873711, cloudbase: 1443.04250432, dateTime: 1626948931, dewpoint: 54.990612981, heatindex: 57.337, humidex: 62.4084288291, inDewpoint: 56.5886416457, inHumidity: 64.0, inTemp: 69.3, outHumidity: 91.0, outTemp: 57.6, pressure: 29.356, radiation: 0.0, rain: 0.0, rainRate: 0.0, usUnits: 1, UV: 0.0, windchill: 57.6, windGust: 0.0, windSpeed: 0.0
REC:    2021-07-22 05:15:00 CDT (1626948900) altimeter: 30.2720068483, appTemp: 59.1486211746, barometer: 30.2713935075, cloudbase: 1443.04250432, dateTime: 1626948900, dewpoint: 54.990612981, ET: 0.0, heatindex: 57.337, humidex: 62.4084288291, inDewpoint: 56.4940312287, inHumidity: 64.0, inTemp: 69.2, interval: 5, maxSolarRad: None, outHumidity: 91.0, outTemp: 57.6, pressure: 29.353, radiation: 0.0, rain: 0.0, rainRate: 0.0, usUnits: 1, UV: 0.0, windchill: 57.6, windDir: None, windGust: 0.0, windGustDir: None, windrun: 0.0, windSpeed: 0.0
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
    self.run()
  File "/usr/share/weewx/weewx/reportengine.py", line 429, in run
    ncopy += weeutil.weeutil.deep_copy_path(path, html_dest_dir)
  File "/usr/share/weewx/weeutil/weeutil.py", line 1501, in deep_copy_path
    shutil.copy(path, d)
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: u'/var/www/html/weewx/seasons.css'
LOOP:   2021-07-22 05:16:32 CDT (1626948992) altimeter: 30.2689308847, appTemp: 59.2801088271, barometer: 30.2681194023, cloudbase: 1443.30334358, dateTime: 1626948992, dewpoint: 55.0894652883, heatindex: 57.447, humidex: 62.5624076362, inDewpoint: 56.5886416457, inHumidity: 64.0, inTemp: 69.3, outHumidity: 91.0, outTemp: 57.7, pressure: 29.35, radiation: 0.0, rain: 0.0, rainRate: 0.0, usUnits: 1, UV: 0.0, windchill: 57.7, windGust: 0.0, windSpeed: 0.0
^CTraceback (most recent call last):
  File "/usr/share/weewx/weewxd", line 264, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 157, in main
    engine.run()
  File "/usr/share/weewx/weewx/engine.py", line 208, in run
    for packet in self.console.genLoopPackets():
  File "/usr/share/weewx/user/interceptor.py", line 2548, in genLoopPackets
    data = self._device.get_queue().get(True, self._queue_timeout)
  File "/usr/lib/python2.7/Queue.py", line 177, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

![2021-07-22 04_58_43-Weather Station](https://user-images.githubusercontent.com/87807548/126622612-0f54177f-0597-479b-8370-201059b0d71f.png)

![2021-07-22 05_09_27-Weather Station 2](https://user-images.githubusercontent.com/87807548/126623290-594bd5ba-aed7-4372-aae1-21d5cf51967e.png)

**Comment by steepleian** [comment]
There seems to be quite a few things to sort out here so will take them step by step.

First of all do you have pyephem installed and if so is it the correct version for Python 2.7 (which you appear to be using). Check the install instructions regarding the various dependencies carefully. Make sure you are not mixing Python 2.7 and Python 3.

**Comment by meisnick** [comment]
Python versioning was the issue. I set up a second raspberry pi and completely removed python3 and then installed and I have data. Fresh install of Raspbian seem unable to use Python3. 

![2021-07-22 14_54_41-Weather Station3](https://user-images.githubusercontent.com/87807548/126701460-87e6c069-4097-474a-91d9-a4df8639d327.png)

Some of the icons in the forecast seem to be missing when I follow the urls of the blank spaces 

/weather34/css/aqi/daywarm.svg
/weather34/css/aqi/nightwarm.svg

![2021-07-22 14_57_39-Weather Station4](https://user-images.githubusercontent.com/87807548/126702384-4b766556-7d33-46d1-985d-6d844444a816.png)

**Comment by steepleian** [comment]
OK I am glad that my first instinct was correct concerning the Python version. By the way way, which version of Raspberry OS are you using? If you are using the current Buster, there should be no issues with Python3.

I will have a look at those image paths, css/aqi is definitely incorrect. I am not a WU user, but I have switched my own website to WU forecast to check and everything is OK for me. https://claydonsweather.org.uk if you want to check.

**Comment by meisnick** [comment]
Linux raspberrypi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
Raspbian GNU/Linux 10 (buster)"

I attempted [explicitly defining python3](https://www.fosslinux.com/39384/switching-between-python-2-and-3-versions-on-ubuntu-20-04.htm) only and it resulted in the previous error. Unsure if its raspbian using 2/3 interchangeably when setting up. Raspbian default python 2.7 worked correctly when python3 was removed completely from the install. 

Let me know if you find anything on those image paths. Thanks!

**Comment by steepleian** [comment]
I have checked the file outlookwu.php which is the one that produces the WeatherUnderground daily forecast. The one in the current main branch of the repository works correctly on my system. Can I suggest that you take a fresh copy of outlookwu.php. Then go to the settings in the menu, open scroll to the bottom and save. Then restart WeeWX. The reason for saving the settings page even though you have made no changes is to make sure that the settings1.php is correctly structured.

**Comment by meisnick** [comment]
I took a copy and compared and main branch vs what was running on my pi was the same. I looked for that svg referenced and it looks like it does not exist anywhere. Judging by the directory its in looks like it's supposed to trigger a little face picture.

I was able to suss out what looks to be the correct svg from a Google search  

https://singaporeweather.info/aqi/daywarm.svg
https://singaporeweather.info/aqi/nightwarm.svg


//high temp icon
	if ($wuskydaynight=='D'){
	if( $tempunit=='F' && $wuskydayTempHigh>=82){echo "<img src='css/aqi/daywarm.svg' width='40px' class='tempalerticon'> " ;}
	else if( $tempunit=='C' && $wuskydayTempHigh>=28){echo "<img src='css/aqi/daywarm.svg' width='40px' class='tempalerticon'> " ;}
	}
	if ($wuskydaynight=='N'){							
	if( $tempunit=='F' && $wuskydayTempHigh>=71){echo "<img src='css/aqi/nightwarm.svg' width='40px' class='tempalerticon'> " ;}
	if( $tempunit=='C' && $wuskydayTempHigh>=22){echo "<img src='css/aqi/nightwarm.svg' width='40px' class='tempalerticon'> " ;}
	}

**Comment by steepleian** [comment]
OK, I inherited this code from the original designer a couple or so years ago. Although much of the code has been changed/updated/enhanced since that time, I had not noticed that those two files did not exist (as previously mentioned I do not use WU forecast API myself). I have now added these two files: -

https://github.com/steepleian/weewx-Weather34/blob/main/www/css/aqi/daywarm.svg
https://github.com/steepleian/weewx-Weather34/blob/main/www/css/aqi/nightwarm.svg

You should place them in your /weather34/css/aqi/ folder. Hopefully this will resolve the issue.

Thank you for raising the issue. I maintain the weewx_Weather34 template purely as a hobby and I am always grateful to users raising issues which improve and enhance the template.

Just one other thing I would like to mention, not related to this issue. I notice from your syslog that you are using the interceptor driver for a GW1000 device. Are you aware that there is now a dedicated driver for the GW1000 device which is rock solid?
It is much easier to setup up with the added benefit that can also be configured to run as a service. The driver was written by one of the WeeWX core development team who has been given NDA access to the GW1000 API by the manufacture. If you are interested, you can find it here: -

https://github.com/gjr80/weewx-gw1000

**Comment by meisnick** [comment]
Looks great

![2021-07-23 18_46_12-Weather 5](https://user-images.githubusercontent.com/87807548/126850738-1da5108a-dfd8-416d-8319-0f0783b4242a.png)

I was able to get the GW1000 driver running as well over interceptor looks much more feature rich. 

Thanks for maintaining the project!
