### ISSUE TITLE
Cannot connect to WeeWX server port 25252

### ISSUE THREAD

**Issue by Damien0505** [steepleian/weewx-Weather34#67]
Hi all, hoping someone maybe able to assist.

Recently upgraded WeeWX and installed the updated weewx-Weather34 (Many thanks Ian!)

Have set up on a remote webserver (https://weather.damienbeeby.com)

I am receiving the following in the nginx/error.log on the remote (web) server:
_FastCGI sent in stderr: "PHP message: Cannot connect to weewx server at 10.0.0.20:25252" while reading response header from upstream, client: 158.140.214.50, server: weather.damienbeeby.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "weather.damienbeeby.com"
_

Firewall ports are all good, locally and remote as well as port forwarding.

netstat -ln on the WeeWX server does **not** any process listening on port 25252.

Relative config from weewx.conf:
_[Weather34RealTime]
    unit_system = METRICWX
    exclude_fields = rain
    cache_enable = True
    cache_stale_time = 900
    weewx_port = 25252
    webserver_address = weather.damienbeeby.com
    weewxserver_address = 158.140.214.50
    weewx_file_transfer =
    HTML_ROOT = /usr/share/nginx/html/weewx/weather34

[Weather34WebServer]
    enable = true

[Weather34CloudCover]
    enable = True
    db_field = signal8
    cc_interval = 300
    cc1_url = https://api.sat24.com/crop?type=visual5hdcomplete&lat=-37.650504&lon=145.512739&width=300&height=300&zoom=1.00&continent=oce
    cc2_url = https://api.sat24.com/crop?type=infraPolair&lat=-37.650504&lon=145.512739&width=300&height=300&zoom=1.00&continent=oce
_

Any assistance or suggestions would be warmly welcomed, please let me know if I can provide any further details.

Details:

- Remote Server: Centos 7; NginX 1.20.1; PHP 7.3.29 (https://weather.damienbeeby.com)
- WeeWX Server:  Fedora 32; WeeWX   4.2.0-1.el8; Apache/2.4.46; PHP 7.4.19

Kind regards,
Damien

**Comment by balloonhotair** [comment]
This is normal since for security the port 25252 is only used for local lan connections and looks like your webserver and weewx server are on different subnets.

**Comment by balloonhotair** [comment]
Some additional info. If you want to stop the error messages remove the entry after weewxserver_address in your weewx config file in the weather34Realtinme section.
Also the only way to get data to a remote webserver is to have rsync setup between the weewx server and your webserver.  Make sure the user running weewx has write privs to your webserver so this means you need to have ssh keys setup correctly.

**Comment by steepleian** [comment]
One of our users, Chris, has created a comprehensive guide for installing on a remote skin. You can find it here: -

https://www.chrisalemany.ca/2021/02/24/installing-the-weather34-skin-on-weewx-with-remote-web-server-2021-edition/
