### ISSUE TITLE
Cloud cover not displaying

### ISSUE THREAD

**Issue by Damien0505** [steepleian/weewx-Weather34#68]
Hi all, hoping someone maybe able to assist.

Recently upgraded WeeWX and installed the updated weewx-Weather34 (Many thanks Ian!)
All working fine with the exception of the Cloud Cover chart.  
Have since set up on a remote webserver (https://weather.damienbeeby.com) and all is still working fine with the exception of the Cloud Cover chart.

Had a look through previous and current issues, no reference to this.

The only error I can find related to this is appearing in the browser when trying to view the chart:
( I also have an issue where the remote server cannot connect to port 25252 on the WeeWX server, raised in issue #67 )

_Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at reinflate_time (plots.js:600)
    at Array.create_cloudcover_chart (plots.js:1581)
    at setup_plots (plots.js:1812)
    at Object.<anonymous> (plots.js:1843)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Object.e.<computed> (jquery.min.js:2)
    at i (jquery.min.js:2)
    at Object.add [as done] (jquery.min.js:2)
    at Object.<anonymous> (jquery.min.js:2)_

Any assistance or suggestions would be warmly welcomed, please let me know if I can provide any further details.

Details:

Remote Server: Centos 7; NginX 1.20.1; PHP 7.3.29 (https://weather.damienbeeby.com)
WeeWX Server: Fedora 32; WeeWX 4.2.0-1.el8; Apache/2.4.46; PHP 7.4.19
Kind regards,
Damien

**Comment by steepleian** [comment]
Hi Damian,
I am afraid that the required satellite images are not yet available for
Australia. The service was due to be worldwide by now but only North
America and Europe appear to be implemented so far. I will put a bit in the
repository to this effect in the repository.
Ian

**Comment by Damien0505** [comment]
Hi Ian,

Many thanks for your speedy reply!  Glad to know it wasn't something I mucked up!

Cheers!
(I'll let you close the issue when you see fit.)

**Comment by steepleian** [comment]
Updated the readme to reflect the current status of sat24
