### ISSUE TITLE
conversion inconsistent with kpa and kph

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#69]
Hi all,

My barometer is displaying max and min and graphs correctly in kPa, but the display is displaying kPa unit but hPa value.

Also there seems to be an issue with the conversion of kph for the gust values. I am seeing proper numbers for normal wind and for the graphs, but display of gusts is way high.

**Comment by balloonhotair** [comment]
So the conversions are done in two places. The graphs(javascript) are done in convert_units.js and everything else is done in w34CombinedData.php. So based on above looks like there are errors in the w34CombinedData.php file.
