### ISSUE TITLE
Wind Barb Chart

### ISSUE THREAD

**Issue by MauroSwiss88** [steepleian/weewx-Weather34#7]
Hi!
I was wondering why the Wind Barb chart always shows a wrong icon and text in correlation to the actual wind speed. See on the example: Strong gale for 19 Km/h with wrong icon. 

How can I correct this?

Thank you in advance for support.

![Schermata 2020-11-06 alle 19 54 09](https://user-images.githubusercontent.com/64233475/98404074-3acbf780-206a-11eb-9d78-d131ebb86a2d.png)

**Comment by balloonhotair** [comment]
Change formula to calculate Beaufort Scale. You can either replace part of line 1017 in plots.js or get the plots.js from the repo. Plots.js resides in ...w34highcharts/scripts directory.
Here is the line, it is quite long but the part that changed is highlighted.
                                                else {spd = this.points[1].y;bn = this.points[0].series.beaufortName[**Math.round(Math.pow(Math.pow((convert_wind(units.wind, "mph", spd)/1.8702),0.33),2))**];tooltip = '<span style="font-size: 10px">' + Highcharts.dateFormat('%e %B %Y %H:%M',new Date(this.points[0].x)) + '</span><br/>' + '<span style="color: ' + this.points[1].series.color+'">' + getTranslation("WindBarb") + ": " + spd + " " + units.wind + " (" + bn + ')</span><br/><span style="color: '+ this.points[0].series.color + '">' + getTranslation("Wind Direction") + ": " + (this.points[0].point.options.direction == null ? getTranslation("Calm") : this.points[0].point.options.direction + '\xB0') + '</span><br/>';}

**Comment by MauroSwiss88** [comment]
Hi balloonhotair,
thank you for the answer.
I changed the formula in the plots.js and got this result:

![Schermata 2020-11-07 alle 12 18 00](https://user-images.githubusercontent.com/64233475/98439646-7bbc1e80-20f3-11eb-8464-4d94456832c0.png)

The text in correlation to the wind speed Is now correct, but still with the wrong barb icon (strong breeze instead gentle breeze). Another question: how can I change the text into Italian? 

Best regards,

Mauro

**Comment by balloonhotair** [comment]
To do Italian you have to add the Italian to the translations file in languages/lang.it.php. 
Once done post the file here and it can be added to the repo.
The barb is wrong since highcharts only does mph so the following code should trick highcharts.
The bold part is what is different and resides at line 1004 in plots.js
wb[j]  = [ws[i][0], ws[i][1] > 0 || !hide_zero_wind_barb ? **convert_wind(units.wind, "mph", ws[i][1])** : null, wd[i][1]];

**Comment by MauroSwiss88** [comment]
Hi balloonhotair,
thank you for answer.

This is the situation with the last commit:
![Schermata 2020-11-07 alle 18 09 39](https://user-images.githubusercontent.com/64233475/98447451-27319700-2125-11eb-878a-9f68e9c5fb2a.png)

The barb icon is now closer to show the right Beaufort value, but still not at all (Icon is on gentle breeze instead light breeze).

For the translations I still have a paragraph for the Beaufort scale:

![Schermata 2020-11-07 alle 18 12 21](https://user-images.githubusercontent.com/64233475/98447530-c22a7100-2125-11eb-86bf-d487ceeae6bf.png)


It's not enough?

Greetings and thank you so much for your efforts.

Mauro

**Comment by balloonhotair** [comment]
Best if you sent text for the translations that way it is easy to copy and paste and prevent any typos.

There is rounding errors going on so you can try the following.

wb[j] = [ws[i][0], ws[i][1] > 0 || !hide_zero_wind_barb ? **Math.round(convert_wind(units.wind, "mph", ws[i][1]))** : null, wd[i][1]];

**Comment by MauroSwiss88** [comment]
By trying this last commit, the whole plots.js crashes and no graph works on the website.

What do you mean with typos? Should I sent the text to you?

Greetings

**Comment by balloonhotair** [comment]
Post a text file to this issue for translations not an image.
There was no submitted change to the code for the Math.round as it was a test to see if it worked.
Are you talking about a previous change?

**Comment by balloonhotair** [comment]
I do not have any errors on my end, so you need to post the browser javascript console , errors section. On Chrome you can get the console using Inspect tool .

**Comment by MauroSwiss88** [comment]
It's not easy for me to post everything on text form because my web server is running on a Raspberry and it's pretty difficult to paste and post something by watching it on a little terminal screen.

What I meant before is that I modified the plots.js with your last suggest on the line (not the commit, sorry) and I don't get the highcharts to load. I don't know how the Inspect Tool works. 

For the translations I don't need to copy the whole file because it's the original one from the repository.

Greetings
Mauro

**Comment by MauroSwiss88** [comment]
So, now it worked with the change to the code for the Math.round, but the icons still show one higher Beaufort scale than the reported speed.

**Comment by balloonhotair** [comment]
So Highcharts wind barbs input units are m/s but the display is knots, very strange way of thinking.
As before change this line in plots.js
wb[j]  = [ws[i][0], ws[i][1] > 0 || !hide_zero_wind_barb ? **convert_wind(units.wind, "mph", ws[i][1])*0.44704** : null, wd[i][1]];

**Comment by balloonhotair** [comment]
wb[j]  = [ws[i][0], ws[i][1] > 0 || !hide_zero_wind_barb ? convert_wind(units.wind, "mph", ws[i][1])*0.44704 : null, wd[i][1]];

**Comment by MauroSwiss88** [comment]
Good morning,
this is the result with the last change. It seems to be better than before, but "light breeze" seems to have the same wind barb as "gentle breeze". Do you agree or do I just get confused?

![Schermata 2020-11-08 alle 09 57 45](https://user-images.githubusercontent.com/64233475/98460951-ef6c3300-21a8-11eb-8df7-35ad48ccb8b9.png)

**Comment by balloonhotair** [comment]
The wind force scale and the highcharts wind barbs are different calculations of wind. So there is overlap. The barbs are scale as half barb for 5 knots and a full barb at 10 knots, while the force scale is a range that does not match the wind barbs.  Looking at your data above the wind speed is not above 10 knots so it is all half a barb.
Also please drag and drop your lang.it.php file into this issue so the repro can get your Italian changes.

**Comment by MauroSwiss88** [comment]
I've observed the icons during these hours and they same to be right now! Thank you so much for help and support.

This is my lang.it.php file for the missing wind translations (I could not drag and drop, sorry) :

`<?php
/* 
-----------------
Language Translation File for HOMEWEATHERSTATION Template
Language: Italian
Translated by: Antonio Angelotti - meteopomarico.it - 23.04.2017
Developed By: Lightmaster/Brian Underdown/Erik M Madsen
October/November 2016
Revised: 2019
-----------------
*/
# -----------------------------------------------------
# Day / Months do not edit
# -----------------------------------------------------
$day        = date("l");
$day2       = date("l", time() + 86400);
$daynum     = date("j");
$monthtrans = date("F");
$year       = date("Y");
# -----------------------------------------------------
# -----------------------------------------------------
setlocale(LC_TIME, "it_IT.UTF-8");
$lang                           = array();
// Menu
$lang['Settings']               = 'Impostazioni';
$lang['Layout']                 = 'Cambia Tema';
$lang['Lighttheme']             = 'Tema Light';
$lang['Darktheme']              = 'Tema Dark';
$lang['Nonmetric']              = 'US (F) ';
$lang['Metric']                 = 'Metrico (C)';
$lang['UKmetric']               = 'UK (MPH - Metrico) ';
$lang['Scandinavia']            = 'Scandinavia(M/S)';
$lang['Worldwideearthquakes']   = 'Terremoti Mondo';
$lang['Toggle']                 = 'Schermo intero';
$lang['Contactinfo']            = 'Stazione & Informazioni';
$lang['Templateinfo']           = 'Contributori';
$lang['language']               = 'Seleziona la lingua';
$lang['Weatherstationinfo']     = 'Info Stazione Meteo';
$lang['Webdesigninfo']          = 'Info Template';
$lang['Contact']                = 'Contatti';
//days
$lang['Monday']                 = 'Monday';
$lang['Tuesday']                = 'Tuesday';
$lang['Wednesday']              = 'Wednesday';
$lang['Thursday']               = 'Thursday';
$lang['Friday']                 = 'Friday ';
$lang['Saturday']               = 'Saturday';
$lang['Sunday']                 = 'Sunday';
//months
$lang['January']                = 'January';
$lang['Febuary']                = 'Febuary';
$lang['March']                  = 'March';
$lang['April']                  = 'April';
$lang['May']                    = 'May';
$lang['June']                   = 'June';
$lang['July']                   = 'July';
$lang['August']                 = 'August';
$lang['September']              = 'September';
$lang['October']                = 'October';
$lang['November']               = 'November';
$lang['December']               = 'December';
//temperature
$lang['Temperature']            = 'Temperatura';
$lang['Feelslike']              = 'Percepita';
$lang['Humidity']               = 'Umidità';
$lang['Dewpoint']               = 'Punto di rugiada';
$lang['Trend']                  = 'trend ';
$lang['Heatindex']              = 'Indice di calore';
$lang['Windchill']              = 'Percepita ';
$lang['Tempfactors']            = 'Fattore Temp';
$lang['Nocautions']             = 'Nessuna Cautela';
$lang['Wetbulb']                = 'Wet Bulb';
$lang['dry']                    = '& Dry';
$lang['verydry']                = '& Very Dry';
//new feature temperature feels
$lang['FreezingCold']           = 'Freddo Glaciale';
$lang['FeelingVeryCold']        = 'Si Sente molto freddo';
$lang['FeelingCold']            = 'Si Sente Freddo';
$lang['FeelingCool']            = 'Si Sente Fresco';
$lang['FeelingComfortable']     = 'Si Sente a proprio agio ';
$lang['FeelingWarm']            = 'Si Sente Caldo';
$lang['FeelingHot']             = 'Si Sente molto Caldo';
$lang['FeelingUncomfortable']   = 'Si Sente a Disagio';
$lang['FeelingVeryHot']         = 'Si Sente molto Caldo';
$lang['FeelingExtremelyHot']    = 'Si Sente Estremamente Caldo';
//wind
$lang['Windspeed']              = 'Velocità vento';
$lang['Gust']                   = 'Raffica';
$lang['Direction']              = 'Direzione';
$lang['Gusting']                = 'Raffica';
$lang['Blowing']                = 'Soffia';
$lang['Wind']                   = 'Velocità';
$lang['Wind Run']               = 'Velocità Run';
// Wind phrases for Beaufort scale for windspeed area
$lang['Calm']                   = 'Calma';
$lang['Lightair']               = 'Bava di Vento';
$lang['Lightbreeze']            = 'Brezza Leggera';
$lang['Gentelbreeze']           = 'Brezza tesa';
$lang['Moderatebreeze']         = 'Vento moderato';
$lang['Freshbreeze']            = 'Vento teso';
$lang['Strongbreeze']           = 'Vento fresco';
$lang['Neargale']               = 'Vicino a burrasca';
$lang['Galeforce']              = 'Gale Burrasca';
$lang['Stronggale']             = 'Burrasca forte';
$lang['Storm']                  = 'Tempesta';
$lang['Violentstorm']           = 'Tempesta violenta';
$lang['Hurricane']              = 'Uragano';
// Wind phrases from Beaufort scale for current conditions area
$lang['CalmConditions']         = 'Condizioni di Calma';
$lang['LightBreezeattimes']     = 'Bava di Vento ';
$lang['MildBreezeattimes']      = 'Brezza Leggera ';
$lang['ModerateBreezeattimes']  = 'Brezza Tesa';
$lang['FreshBreezeattimes']     = 'Vento Moderato';
$lang['StrongBreezeattimes']    = 'Vento Teso';
$lang['NearGaleattimes']        = 'Vento Fresco';
$lang['GaleForceattimes']       = 'Vento Forte';
$lang['StrongGaleattimes']      = 'Burrasca';
$lang['StormConditions']        = 'Tempesta';
$lang['ViolentStormConditions'] = 'Tempesta Violenta';
$lang['HurricaneConditions']    = 'Uragano';
$lang['Avg']                    = '<span2> Avg: </span2>';
//wind direction compass
$lang['Northdir']               = 'Da <span>Nord<br></span>';
$lang['NNEdir']                 = 'Nord Nord <br><span>Est</span>';
$lang['NEdir']                  = 'Nord <span> Est<br></span>';
$lang['ENEdir']                 = 'Est Nord<br><span>Est</span>';
$lang['Eastdir']                = "Da <span> Est<br></span>";
$lang['ESEdir']                 = 'Est Sud<br><span>Est</span>';
$lang['SEdir']                  = 'Sud <span> Est</span>';
$lang['SSEdir']                 = 'Sud Sud<br><span>Est</span>';
$lang['Southdir']               = 'Da <span> Sud</span>';
$lang['SSWdir']                 = 'Sud Sud<br><span>Ovest</span>';
$lang['SWdir']                  = 'Sud <span> Ovest</span>';
$lang['WSWdir']                 = 'Ovest Sud<br><span>Ovest</span>';
$lang['Westdir']                = 'Da <span> Ovest</span>';
$lang['WNWdir']                 = 'Ovest Nord<br><span>Ovest</span>';
$lang['NWdir']                  = 'Nord <span> Ovest</span>';
$lang['NWNdir']                 = 'Nord Nord<br><span>Ovest</span>';
//wind direction avg
$lang['North']                  = 'Nord';
$lang['NNE']                    = 'NNE';
$lang['NE']                     = 'NE';
$lang['ENE']                    = 'ENE';
$lang['East']                   = 'Est ';
$lang['ESE']                    = 'ESE';
$lang['SE']                     = 'SE';
$lang['SSE']                    = 'SSE';
$lang['South']                  = 'Sud';
$lang['SSW']                    = 'SSO';
$lang['SW']                     = 'SO';
$lang['WSW']                    = 'OSO';
$lang['West']                   = 'Ovest';
$lang['WNW']                    = 'ONO';
$lang['NW']                     = 'NO';
$lang['NWN']                    = 'NNO';
//rain
$lang['raintoday']              = 'Precipitazioni Oggi';
$lang['Rate']                   = 'Tasso';
$lang['Rainfall']               = 'Precipitazioni';
$lang['Precip']                 = 'precip'; // must be short name do not use full precipitation !!!! ///
$lang['Rain']                   = 'Pioggia';
$lang['Heavyrain']              = 'Pioggia forte';
$lang['Flooding']               = 'Possibili Inondazioni';
$lang['Rainbow']                = 'Rainbow';
$lang['Windy']                  = 'Windy';
//sun -moon-daylight-darkness
$lang['Sun']                    = 'Sole';
$lang['Moon']                   = 'Luna';
$lang['Sunrise']                = 'Alba';
$lang['Sunset']                 = 'Tramonto';
$lang['Moonrise']               = 'Sorgere della luna ';
$lang['Moonset']                = 'Tramonto Luna';
$lang['Night']                  = 'Notte ';
$lang['Day']                    = 'Giorno';
$lang['Nextnewmoon']            = 'Luna nuova';
$lang['Nextfullmoon']           = 'Luna Piena';
$lang['Luminance']              = 'Luminanza';
$lang['Moonphase']              = 'Fase Lunare';
$lang['Estimated']              = 'Stimato';
$lang['Daylight']               = 'Luce';
$lang['Darkness']               = 'Oscurità';
$lang['Daysold']                = 'Vecchia';
$lang['Belowhorizon']           = 'sotto<br>orizzonte';
$lang['Mintill']                = '<br>min fino';
$lang['Till']                   = 'a ';
$lang['Minago']                 = ' min fa';
$lang['Hrs']                    = ' ore';
$lang['Min']                    = ' min';
$lang['TotalDarkness']          = 'Ore notte';
$lang['TotalDaylight']          = 'Ore giorno';
$lang['Below']                  = '&egrave; sotto orizzonte';
$lang['Newmoon']                = 'Luna Nuova';
$lang['Waxingcrescent']         = 'Luna Crescente';
$lang['Firstquarter']           = 'Primo Quarto';
$lang['Waxinggibbous']          = 'Gibbosa Crescente';
$lang['Fullmoon']               = 'Luna Piena';
$lang['Waninggibbous']          = 'Gibbosa Calante';
$lang['Lastquarter']            = 'Ultimo Quarto';
$lang['Waningcrescent']         = 'Luna Calante';
//trends
$lang['Falling']                = 'Diminuz';
$lang['Rising']                 = 'Aumento';
$lang['Steady']                 = 'Costante';
$lang['Rapidly']                = 'Rapidamente';
$lang['Temp']                   = 'Temp';
//Solar-UV
//uv
$lang['Nocaution']              = 'Nessuna <color>cautela</color> necessaria';
$lang['Wearsunglasses']         = 'Indossare <color>occhiali da sole</color> in giornate luminose';
$lang['Stayinshade']            = 'Rimani all ombra vicino mezzogiorno quando il <color>sole</color> è più forte';
$lang['Reducetime']             = 'Ridurre il tempo al <color>sole</color> tra le 10am-4pm ';
$lang['Minimize']               = 'Ridurre al minimo esposizione al <color>sole</color> tra le 10am-4pm ';
$lang['Trytoavoid']             = 'Cercate di evitare esposizione al <color>sole</color> tra le 10am-4pm ';
//solar
$lang['Poor']                   = 'Scarsa<color> <br>Radiazione</color>';
$lang['Low']                    = 'Bassa<br><color>Radiazione</color>';
$lang['Moderate']               = 'Moderata <br><color>Radiazione</color>';
$lang['Good']                   = 'Forte <br><color>Radiazione</color>';
$lang['Solarradiation']         = 'Radiazione solare';
//current sky
$lang['Currentsky']             = 'Condizioni Attuali';
$lang['Currently']              = 'Attualmente';
$lang['Cloudcover']             = 'Coperto dalle Nuvole';
//Notifications
$lang['Nocurrentalert']         = 'Nessuna allerta';
$lang['Windalert']              = 'Raffiche di vento';
$lang['Tempalert']              = 'Alta temperatura';
$lang['Heatindexalert']         = 'Allerta Indice di calore';
$lang['Windchillalert']         = 'Allerta Temperatura';
$lang['Dewpointalert']          = 'disagio Umidità';
$lang['Dewpointcolderalert']    = 'Allerta Punto di rugiada';
$lang['Feelslikecolderalert']   = 'Si sente più freddo';
$lang['Feelslikewarmeralert']   = 'Si sente più caldo';
$lang['Rainratealert']          = 'per/hr<span> Precipitazione ';
//Earthquake Notifications
$lang['Regional']               = 'Terremoti Regionali';
$lang['Significant']            = 'Significativi';
$lang['Nosignificant']          = 'Nessun Terremoto Significativo';
//Main page
$lang['Barometer']              = 'Barometro';
$lang['UVSOLAR']                = 'UV | <span style="color:#f26c4f">Dati Solari</span>';
$lang['Earthquake']             = 'Dati Terremoto';
$lang['Daynight']               = 'Info Giorno & Notte';
$lang['SunPosition']            = 'Sun Position';
$lang['Location']               = 'Posizione ';
$lang['Hardware']               = 'Hardware';
$lang['Rainfalltoday']          = 'Pioggia Giornaliera';
$lang['Windspeed']              = 'Vento';
$lang['Winddirection']          = 'La direzione del vento';
$lang['Measured']               = 'Giorno Misurato';
$lang['Forecast']               = 'Previsione';
$lang['Forecastahead']          = 'Previsione 10 Giorni';
$lang['Forecastsummary']        = 'Previsione Sommaria';
$lang['WindGust']               = 'Raffica';
$lang['Hourlyforecast']         = 'Previsione Oraria';
$lang['Significantearthquake']  = 'Terremoto Significativi';
$lang['Regionalearthquake']     = 'Terremoto Regionali';
$lang['Average']                = 'Media';
$lang['Notifications']          = 'Notifiche di Allerta';
$lang['Indoor']                 = 'Interno';
$lang['Today']                  = 'Oggi';
$lang['Tonight']                = 'Notte';
$lang['Tomorrow']               = 'Domani';
$lang['Tomorrownight']          = 'Domani notte';
$lang['Updated']                = 'Aggiornato';
$lang['Meteor']                 = 'Info Sciame meteorico';
$lang['Firerisk']               = 'Rischio Incendio';
$lang['Localtime']              = 'Ora Locale';
$lang['Nometeor']               = 'Nessun Sciame meteorico';
$lang['LiveWebCam']             = 'WebCam';
$lang['Online']                 = 'Online';
$lang['Offline']                = 'Offline';
$lang['Weatherstation']         = 'Weather Station';
$lang['Cloudbase']              = 'Cloudbase';
$lang['uvalert']                = 'Caution High UVINDEX';
$lang['Max']                    = 'Max';
$lang['Min']                    = 'Min';
//earthquake TOP MODULE 10 July 2017
$lang['MicroE']                  = 'Micro Earthquake';
$lang['MinorE']                  = 'Minor Earthquake';
$lang['LightE']                  = 'Light Earthquake';
$lang['ModerateE']               = 'Moderate Earthquake';
$lang['StrongE']                 = 'Strong Earthquake';
$lang['MajorE']                  = 'Major Earthquake';
$lang['GreatE']                  = 'Great Earthquake';
$lang['RegionalE']              = 'Regional';
$lang['Conditions']             = 'Condizioni';
$lang['Cloudbase Height']       = 'Altezza Nuvole';
$lang['Station']                = 'Stazione';
$lang['Detailed Forecast']      = 'Dettagli Previsione';
$lang['Summary Outlook']        = 'Riepilogo Previsione';
//Air Quality
$lang['Hazordous']              = 'Hazardous Conditions';
$lang['VeryUnhealthy']          = 'Very Unhealthy';
$lang['Unhealthy']              = 'Unhealthy Air Quality';
$lang['UnhealthyFS']            = 'Unhealthy For Some';
$lang['Moderate']               = 'Moderate Air Quality ';
$lang['Good']                   = 'Good Air Quality ';
#notification additions
$lang['notifyTitle']            = 'Notifiche';
$lang['notifyAlert']             = "Alert";
$lang['notifyLowBatteryAlert']   = "Low Battery Alert";
$lang['notifyConsoleLowBattery'] = "Console's battery is low";
$lang['notifyStationLowBattery'] = "Station's battery is low";
$lang['notifyUVIndex']           = "UV-Index Caution";
$lang['notifyUVExposure']        = "Reduce Sun Exposure";
$lang['notifyHeatExaustion']     = "Heat Exhaustion";
$lang['notifyExtremeWind']       = "Extreme Wind Warning";
$lang['notifyGustUpTo']          = "Gusts up to";
$lang['notifySeekShelter']       = "Seek shelter <notifyred><b>immediately</b></notifyred>";
$lang['notifyHighWindWarning']   = "High Wind Warning";
$lang['notifySustainedAvg']      = "Sustained avg";
$lang['notifyWindAdvisory']      = "Wind Advisory";
$lang['notifyFreezing']          = "Below Freezing";
?>`

**Comment by MauroSwiss88** [comment]
I've seen your update and my translations are ok, but it seems that the WindBarb chart does not take the translations from the lang.it.php file, neither from the lang.en.php

**Comment by balloonhotair** [comment]
Does not work that way. The translations  used are put into a different file than the language ones. To update the translations file the user must go into the easysetup page and save the settings. This will trigger making a new translations file.

**Comment by MauroSwiss88** [comment]
What should I change in the easy setup page?

**Comment by balloonhotair** [comment]
Nothing just do the save/submit.

**Comment by MauroSwiss88** [comment]
If I set the language to "it" in the easy setup page and then save and submit, there are still no translations for the wind barb chart. Maybe I didn't understand you well.

**Comment by balloonhotair** [comment]
Check your apache2 error log after you hit submit on the easysetup page. If there are any errors post them here. Also you need to clear your browser cache for the new translations file to load. My system worked just fine. Very important to clear your browser cache and then reload the page.

**Comment by MauroSwiss88** [comment]
Ok! I will check in the next days. Thank you anyway!

Just a little question for another issue I've noted today (also on Ian's Website): 

Why is the calculated Heat Index different from the temperature itself when there is no Heat Index to calculate under 26.7 C.?


My Website shows this, where Indice di Calore (Heat Index) differences from Temperature :

![Schermata 2020-11-11 alle 19 27 34](https://user-images.githubusercontent.com/64233475/98849772-04202380-2454-11eb-8642-edc29815dc57.png)

The same on Ian's Website:

![Schermata 2020-11-11 alle 19 29 06](https://user-images.githubusercontent.com/64233475/98849909-3d589380-2454-11eb-9ee0-ca4c190387d5.png)


Thank you for your efforts.

**Comment by balloonhotair** [comment]
The template just displays what weewx calculates.

**Comment by MauroSwiss88** [comment]
Yes, I know. Maybe there is something wrong with weewx since they updated the new version.

Thank you balloonhotair! Have a nice evening.

**Comment by MauroSwiss88** [comment]
Hi Jerry,

so, you write that the translations used are put into a different file than the language ones: I still don't find out witch file it is.

To update the translations file the user must go into the easysetup page and save the settings: Done several times, but there are no changes.


Greetings

**Comment by balloonhotair** [comment]
Hi,
Please post the apache2 error log.  
This has been asked a number of times already.

**Comment by MauroSwiss88** [comment]
Sorry Jerry! This is the log I get after saving changes on the setup page:

[Fri Nov 13 18:45:43.342755 2020] [php7:warn] [pid 9456] [client 192.168.178.31:38136] PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/weewx/weather34/eualert.php on line 206
[Fri Nov 13 18:45:43.345111 2020] [php7:warn] [pid 9456] [client 192.168.178.31:38136] PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/weewx/weather34/eualert.php on line 206
[Fri Nov 13 18:45:43.349884 2020] [php7:warn] [pid 9456] [client 192.168.178.31:38136] PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/weewx/weather34/eualert.php on line 206
[Fri Nov 13 18:45:43.352592 2020] [php7:notice] [pid 9456] [client 192.168.178.31:38136] PHP Notice:  Trying to get property 'textContent' of non-object in /var/www/html/weewx/weather34/eualert.php on line 492
[Fri Nov 13 18:45:43.355181 2020] [php7:notice] [pid 9456] [client 192.168.178.31:38136] PHP Notice:  Trying to get property 'textContent' of non-object in /var/www/html/weewx/weather34/eualert.php on line 492
[Fri Nov 13 18:45:43.479435 2020] [php7:notice] [pid 9456] [client 192.168.178.31:38136] PHP Notice:  Undefined property: Period::$from in /var/www/html/weewx/weather34/eualert.php on line 509
[Fri Nov 13 18:45:43.485423 2020] [php7:notice] [pid 9456] [client 192.168.178.31:38136] PHP Notice:  Undefined property: Period::$until in /var/www/html/weewx/weather34/eualert.php on line 510
[Fri Nov 13 18:45:43.492800 2020] [php7:notice] [pid 9456] [client 192.168.178.31:38136] PHP Notice:  Undefined property: Period::$from in /var/www/html/weewx/weather34/eualert.php on line 509
[Fri Nov 13 18:45:43.494599 2020] [php7:notice] [pid 9456] [client 192.168.178.31:38136] PHP Notice:  Undefined property: Period::$until in /var/www/html/weewx/weather34/eualert.php on line 510
[Fri Nov 13 18:45:48.306780 2020] [php7:error] [pid 9457] [client 2.39.170.82:49651] script '/var/www/html/weewx/weather34/weewxcron.php' not found or unable to stat, referer: http://delauretis.ddns.net/

**Comment by balloonhotair** [comment]
So there is a number of errors we need Ian to fix in eualert.php and there are calls to non-existing script.
Also do you have latest copy of ...easysetup script?
When you save in the setup the file translations.js is created/updated in the languages directory. 
This is where all the translations reside.
You must manually clear your browser cache for the changes to take place. Just doing a reload does not work for most browsers.
You should see your update translations in the translations.js. If not then it is a php problem with easysetup script, if you do see them in the file and not on the browser then your browser cache is not getting cleared.

**Comment by MauroSwiss88** [comment]
Yes, I have the latest version of the easyW34skinSetup.php file.
If I open the file translations.js in the languages directory, I see all my translations I've made.

For example: 'Calm': 'Calma',

Then I go to the browser (Chrome), delete the whole cache, open the wind barb chart on my website and the result is this:

![Schermata 2020-11-13 alle 20 04 15](https://user-images.githubusercontent.com/64233475/99111071-bb02d780-25eb-11eb-9942-11b0accdeb72.png)

As you can see, there is still written "(Calm)" on the Gust row, so maybe it is a php problem.

**Comment by balloonhotair** [comment]
Ok that means the translations is working and the is a hard coded Calm string in the code some where that is not going through translations.

**Comment by MauroSwiss88** [comment]
Yes, I think so. Anyway, thank you so much for your help, Jerry. I hope I could be helpful too to find out other issues.

**Comment by balloonhotair** [comment]
Added translation to highcharts  Beaufort wind scale to plots.js.

**Comment by MauroSwiss88** [comment]
Great! It works! 👍 

Thank you so much for your help, Jerry!

PS: Is it normal that my browser always crashes by opening the radial charts? It seems to be a script problem, but it happens only on my website, not on Ian's one.

**Comment by balloonhotair** [comment]
Define what you mean by crash?
What browser are you using?
What os are you using?
Does it happen with windrose charts or just a radial chart?
Is there data for the radial chart?
Does it happen all the time?

**Comment by MauroSwiss88** [comment]
1) With crash I mean that the radial chart won't be populated by any data and the whole browser blocks

2) Safari and Google Chrome, it happens on both

3) MacOS ior iOS

4) Windrose charts works perfectly, only on radial charts

5) Yes, there is data fo the radial charts and it happens all time

Here an example of the crash on Safari and Google Chrome:

![Schermata 2020-11-14 alle 18 14 51](https://user-images.githubusercontent.com/64233475/99152938-63c13d80-26a5-11eb-9306-e411da5dd0a6.png)

![Schermata 2020-11-14 alle 18 16 29](https://user-images.githubusercontent.com/64233475/99152969-9a975380-26a5-11eb-9721-e50540d328b1.png)


But as I mentioned before. It only happens on my website. If I show the radial charts on Ian's website, they work very well.

**Comment by balloonhotair** [comment]
What does the javascript error console show when Chrome is in inspect mode?

**Comment by MauroSwiss88** [comment]
{temp: "C", pressure: "hPa", wind: "km/h", rain: "mm"} "temperatureplot" ["yearly"] false false null false false "plot_div"
plots.js:1802 {temp: "C", pressure: "hPa", wind: "km/h", rain: "mm"} "temperatureplot" ["yearly"] false false "temperatureplot:yearly" false true "plot_div"

Error Code: 6

**Comment by balloonhotair** [comment]
Error code 6 on Chrome is Network failure but that really can mean anything.
Both Ian and I lost our mac machines at about the same time, so we cannot test macs.
There is a hack for a highcharts issue dealing with radial charts only. That is why the question on windrose above.
If you edit plots.js and go to line 184  there about and change
setTimeout(polar_chart_hack,0);
to
setTimeout(polar_chart_hack,1000);
Then clear cache and try and display the radial chart again and see what happens.
If it still is bad then comment out line about 172
 chart.rangeSelector.clickButton(0, true);
and see what happens.

**Comment by MauroSwiss88** [comment]
- By changing line 184 the radial charts got populated, but crashed after five seconds.
- Commented out "chart.rangeSelector.clickButton(0,true);" on line 172: the radial charts got populated and WORKED without crashes. 

Tested on Chrome as well as Safari with my Macbook.

Great job, Jerry! I'm very grateful for your help :-)

**Comment by steepleian** [comment]
The only contribution I can make is that my daughter has no issue with her
Mac Air

**Comment by MauroSwiss88** [comment]
It's good, Ian. The problem is solved! :-)

I don't want to open another issue thread, but I have a further question regarding to the monthly precipitation plot.
Yesterday, I've imported my old weather data since 2016 and rebuilded the daily summaries. Every plot works fine, but on the monthly precipitation I have this:

![Schermata 2020-11-16 alle 09 43 34](https://user-images.githubusercontent.com/64233475/99231752-51541a80-27f1-11eb-80e5-37e49970b45a.png)

The precipitation values are populated well, nothing strange, but they are not from this year.
Is there a possibility to divide them by year?

**Comment by steepleian** [comment]
You appear to be missing the from and to date selection boxes on your
charts. Should be top right under selec
[image: image.png]

**Comment by MauroSwiss88** [comment]
Yes, I know. The from and to date selection is missing in this plot, it doesn't exist.

**Comment by balloonhotair** [comment]
Yep that is the current design since there is no selector that is based on months existing in the code.

**Comment by MauroSwiss88** [comment]
So there is no chance to get the monthly precipitation plot divided to year?

**Comment by balloonhotair** [comment]
Not without a lot of work since highcharts selector is based on timestamps and this plot is based on months (really strings) so a one off selector would have to be written.

**Comment by MauroSwiss88** [comment]
I understand! Well, it was just a question. The actual plot is more than enough and you all do a nice job! 👍 
Thank you Jerry, Thank you Ian!


You can archive this issue! :-)
