### ISSUE TITLE
eeh.. installation guide incorrect.

### ISSUE THREAD

**Issue by jult** [steepleian/weewx-Weather34#70]
oops, never mind.
overlooked having to create services.txt

**Comment by steepleian** [comment]
It's all in the instructions 🙂

**Comment by jult** [comment]
> 
> 
> It's all in the instructions 🙂

Well, it's not in 'INSTALLATION_GUIDE', which I followed.

**Comment by steepleian** [comment]
Excuse me if I misunderstand you but this IS in the install guide from
where I have just cut and pasted from: -


   -

   Go to https://steepleian.github.io/weewx-Weather34 to complete the
   pre-install web services settings which which generates 'services.txt' in
   your default Download folder. IMPORTANT the unit codes that you select for
   the Weather Underground and DarkSky forecast APIs must be identical to
   those that you select in the post-install settings page. Failure to do so
   will possibly produce some bizzare data.
   -

   From the command line: -

     cd [path_to_your_Download_folder]
     sudo git clone https://github.com/steepleian/weewx-Weather34.git
     sudo cp services.txt weewx-Weather34
     cd weewx-Weather34
     sudo python w34_installer.py or sudo python3 w34_installer.py (if
you are running Python3)


         You will be prompted for the config file for your WeeWX install type.
         Select packaged if your WeeWX was installed by Debian, RedHat
or Suse methods [default option]
         or
         Select setup_py. if your WeeWX was installed by setup.py method
         or
         Select macos if your WeeWX was installed by MacOS method

**Comment by jult** [comment]
Yes, it IS, sorry for the confusion. I did see that, and somehow thought I could skip that. No idea why, really. Must be the delta variant, which I seem to have picked up. My sincere apologies.
