### ISSUE TITLE
Cannot complete easyW34skinSetup.php

### ISSUE THREAD

**Issue by k6bpm** [steepleian/weewx-Weather34#73]
Just installed today Aug 29 2021 on RPi4, using Nginx and PHP 8.0. Brand new setup.

After filling out the entire form and trying to submit I get:

Cannot read input file languages/lang..php

I selected "en" and then "us". It didn't pass either to the code.

**Comment by steepleian** [comment]
Brian,
Not absolutely sure why this is happening, but there is a way round this. You will find a file called settings1_default.php, copy this to a new file called settings1.php (which is the file that should be generated the first time you go to the settings page). Make sure that the user and group ownerships of this file are both set to www-data.

You can then go to the settings page once again, make your changes, save and everything then should be OK. 
Ian

**Comment by k6bpm** [comment]
Thanks, that fixed that problem. I appreciate the help!

I have a bigger issue but I will open a new issue so this does thread does not wander.
