### ISSUE TITLE
Black main screen on new install

### ISSUE THREAD

**Issue by k6bpm** [steepleian/weewx-Weather34#74]
This is a new install. Everything up-to-date as of Aug 30, 2021. Running an RPi4, Buster Lite, Nginx, PHP 8.0. WeeWX works fine stand-alone. Got my issue with creating settings1.php resolved.

When I try to load the /weather34/ index.php in my browser I get a blank white page. There is no code (Browser->View Code) inside at all. Totally empty. I don't get any errors or any other indication that something is wrong. It is just a blank page.

I had thought maybe it required settings1.php and it was missing initially, but there now and no change.

Syslog indicates that things are working and w34realtime.txt is being updated. 

Any idea where to look?

Here is a typical syslog snippet:

Aug 30 07:31:18 weewx weewx[493] INFO weewx.cheetahgenerator: Generated 6 files for report w34Highcharts in 0.91 seconds
Aug 30 07:31:18 weewx weewx[493] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/w34highcharts
Aug 30 07:32:15 weewx weewx[493] INFO weewx.manager: Added record 2021-08-30 07:32:00 PDT (1630333920) to database 'weewx.sdb'
Aug 30 07:32:15 weewx weewx[493] INFO weewx.manager: Added record 2021-08-30 07:32:00 PDT (1630333920) to daily summary in 'weewx.sdb'
Aug 30 07:32:16 weewx weewx[493] INFO weewx.restx: Wunderground-PWS: Published record 2021-08-30 07:32:00 PDT (1630333920)
Aug 30 07:32:16 weewx weewx[493] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 0.97 seconds
Aug 30 07:32:17 weewx weewx[493] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.88 seconds
Aug 30 07:32:17 weewx weewx[493] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx
Aug 30 07:32:17 weewx weewx[493] INFO weewx.cheetahgenerator: Generated 1 files for report Weather34Report in 0.16 seconds
Aug 30 07:32:17 weewx weewx[493] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/
Aug 30 07:32:18 weewx weewx[493] INFO weewx.cheetahgenerator: Generated 7 files for report w34Highcharts in 0.94 seconds
Aug 30 07:32:18 weewx weewx[493] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/w34highcharts

**Comment by balloonhotair** [comment]
Need to look at the web server error log on the RPi4 and in the console error log for the local browser.

**Comment by k6bpm** [comment]
Nothing in the error log.

The access log shows  **500** result for ../weather34/index.php  
but a **200** result for ../weather34/easyW34skinSetup.php.

I have no idea why. Permissions are all 755. Owner for all is www-data. easyW34skinSetup.php loads and posts fine.

**Comment by balloonhotair** [comment]
The permissions set at 755 is fine. The 500 error means there probably a php error when displaying the index.php. This usually means one of the pages that index.php loads has an issue.  First item to check are there files in the .../weather34/serverdata directory. There should be three of them and they all should have data in them.

**Comment by k6bpm** [comment]
There are actually 4. All have data. w34realtime.txt and archive data.php are updated on each loop. weewxserverinfo.txt contains one line,  :25252::/usr/share/weewx. I have looked at these but not changed anything from the original install.

-rw-r--r-- 1 root     root     4722 Aug 30 09:02 archivedata.php
-rwxr-xr-x 1 www-data www-data    1 Aug 29 11:03 placeholder.txt
-rw-r--r-- 1 root     root      292 Aug 30 09:02 w34realtime.txt
-rw-r--r-- 1 root     root       25 Aug 30 07:14 weewxserverinfo.txt

**Comment by balloonhotair** [comment]
Well that is a good start. The placeholder.txt file is a dummy file needed so github creates an empty directory. The serverinfo files does not get updated unless weewx is restarted but what you listed is fine. So now will need you to post the archivedata.php and the w34realtime.txt files so I can look at them. If they look ok then the issue maybe in the settings1.php file but to be sure will have to load into the browser one by one each file that index.php includes at load time. But first lets look at the archivedata.php and w34realtime.txt files.

**Comment by k6bpm** [comment]
Ok, I really appreciate your help. I know my way around these machines, but this is not a common one I am used to dealing. with. Files attached.
[archivedata.php.zip](https://github.com/steepleian/weewx-Weather34/files/7078067/archivedata.php.zip)
[w34realtime.txt.zip](https://github.com/steepleian/weewx-Weather34/files/7078068/w34realtime.txt.zip)

**Comment by balloonhotair** [comment]
Did not see any issues with broken data. So now we need to load each include file and see what one breaks. 
Here is a list of the files.
w34CombinedData.php
webserver_ip_address.php
common.php
settings1.php
One of these file should not load in the browser will give an 500 error and the webserver error log should tell you why.

**Comment by k6bpm** [comment]
Ok, it is the webserver_ip_address.php file. It looks like a bad $weewxserver_address. I looked at this but don't know where it gets this value from. There was a item in the web app that creates services.txt that asked for a server address but it was unclear what that meant. FQDN? Public IP? Local IP? Localhost? I used the local IP but don't know where this is saved.

Here's the error:

2021/08/30 09:38:28 [error] 951#951: *315 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key 1 in /var/www/html/weewx/weather34/webserver_ip_address.php on line 8PHP message: PHP Fatal error:  Uncaught TypeError: socket_connect(): Argument #3 ($port) must be of type ?int, string given in /var/www/html/weewx/weather34/webserver_ip_address.php:12
Stack trace:
#0 /var/www/html/weewx/weather34/webserver_ip_address.php(12): socket_connect()
#1 {main}
  thrown in /var/www/html/weewx/weather34/webserver_ip_address.php on line 12" while reading response header from upstream, client: 72.215.188.101, server: greatweather.com, request: "GET /weather34/webserver_ip_address.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "greatweather.com"

**Comment by balloonhotair** [comment]
Is the webserver and the weewx server on the same machine? If they are then the following entries in your weewx.conf in the weather34reatime section should look like this.
 weewx_port = 25252
 webserver_address =
 weewxserver_address =
 weewx_file_transfer =
 HTML_ROOT =
If you answer is no then we have to go down a different path.  The question that was asked when doing your install was to find out if you are using a remote webserver.

**Comment by k6bpm** [comment]
Yes, everything is all on the same machine. My weewx.conf settings look like this:

[Weather34RealTime]
    unit_system = US
    exclude_fields = rain
    cache_enable = True
    cache_stale_time = 900
    weewx_port = 25252
    webserver_address = 
    weewxserver_address = 
    weewx_file_transfer = 
    HTML_ROOT =

**Comment by balloonhotair** [comment]
Ok good just checking. So in the file weewxserverinfo.php add your local ip address for your weewx server to the  line
:25252::/usr/share/weewx
for for example here is mine
192.168.0.21:25252::/usr/share/weewx

**Comment by k6bpm** [comment]
That fixed the exception error but unfortunately index.php is still returning a 500 error. I also tried it on a different computer on a different network to rule out caching issues.

**Comment by k6bpm** [comment]
updater.php is also mentioned in index.php so I checked it as well. (menu.php worked sort of) Here is the error message from updater.php. Maybe there is something here?

2021/08/30 10:50:52 [error] 15016#15016: *20 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $stationName in /var/www/html/weewx/weather34/menu.php on line 11PHP message: PHP Warning:  Undefined variable $units in /var/www/html/weewx/weather34/menu.php on line 18PHP message: PHP Warning:  Undefined variable $lang in /var/www/html/weewx/weather34/menu.php on line 50PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/weewx/weather34/menu.php on line 50PHP message: PHP Warning:  Undefined variable $theme in /var/www/html/weewx/weather34/menu.php on line 62PHP message: PHP Warning:  Undefined variable $theme in /var/www/html/weewx/weather34/menu.php on line 63PHP message: PHP Warning:  Undefined variable $units in /var/www/html/weewx/weather34/menu.php on line 78PHP message: PHP Warning:  Undefined variable $units in /var/www/html/weewx/weather34/menu.php on line 96PHP message: PHP Warning:  Undefined variable $units in /var/www/html/weewx/weather34/menu.php on line 103PHP message: PHP Warning:  Undefined variable $units in /var/www/html/weewx/weather34/menu.php on line 110PHP message: PHP Warning:  Undefined variable $units in /var/www/html/weewx/weather34/menu.php on line 117PHP message: PHP Warning:  Undefined variable $units in /var/www/html/weewx/weather34/menu.php on line 124PHP message: PHP Warning:  Undefined variable $extralinks in /var/www/html/weewx/weather34/menu.php on line 132PHP message: PHP Warning:  Undefined variable $weatherflowoption in /var/www/html/weewx/weather34/menu.php on line 283PHP message: PHP Warning:  Undefined variable $languages in /var/www/html/weewx/weather34/menu.php on line 350" while reading response header from upstream, client: 72.215.188.101, server: greatweather.com, request: "GET /weather34/menu.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "www.greatweather.com"

**Comment by balloonhotair** [comment]
So need you to post your settings1.php file but you need to make a copy of it first and remove any keys,etc that is personal to your setup. Take your time doing this since this is a public forum.

**Comment by k6bpm** [comment]
Sure, here is is, sanitized.
[settings1.php.zip](https://github.com/steepleian/weewx-Weather34/files/7078581/settings1.php.zip)

**Comment by balloonhotair** [comment]
So your settings1.php is missing some entries. Not sure how put add these two lines to just after the php line
$theme = isset($theme) ? $theme : "dark";
$theme1 = $theme;

**Comment by steepleian** [comment]
Probably my fault. I told Brian to copy settings1_default.php to overcome
his original error, however when I tried it and saved from within the
settings page, those two lines were added. Probably need to go back and
examine the original issue.

**Comment by k6bpm** [comment]
Ok, did that but still getting 500 result. No errors in error.log. I rebooted and tried various browsers on different machines/networks. Sorry to be a pain. I would really like this to work. I've been waiting for a nice UI for 20 years ;)

**Comment by balloonhotair** [comment]
So what browser are you using?  How are you clearing the cache on that browser?
So still getting a 500 on the browser but nothing in the error.log?
Need to understand what is going on so the details really count since there are less and less things to check and a 500 error is usually easy to solve using the steps we are doing.

**Comment by balloonhotair** [comment]
Will also need to see an updated settings1.php file just to make sure the changes are what I expected.

**Comment by k6bpm** [comment]
Here you go...
[settings1.php.zip](https://github.com/steepleian/weewx-Weather34/files/7078965/settings1.php.zip)

**Comment by balloonhotair** [comment]
So I ran with your settings1.php file and got no 500 error. So now I need your index.php file so I can test with that unless it is the exactly the one in the release directory and no changes have been made to it of any of its support files.

**Comment by balloonhotair** [comment]
what is the browser being used?

**Comment by balloonhotair** [comment]
Also what version of php is being used?

**Comment by k6bpm** [comment]
I am using PHP 8.0. I have used Safari, Chrome on Mac and Chrome on Windows. 

Nothing has been modified in the weather34 directory except settings1.php. I checked all the sub-dirs too and li looks like only some json data and the /serverdata stuff has been modified.

**Comment by k6bpm** [comment]
Is there anything in weewx.conf that I should check?

**Comment by balloonhotair** [comment]
No you already sent what I needed to see.  
Lets do all our testing with Chrome and Windows.
I am not running version 8 of php so I have asked Ian to see if he has tested with php 8.0.
My version is 7.4 php so version 8.0 had a large number of changes so need to see if we are chasing a php version issue.

**Comment by balloonhotair** [comment]
For a test will we wait for Ian, make a copy of your index.php and then edit it and remove
include_once('updater.php');
It is at the bottom of the file. The updater has cause issues in the past and want to see if it causing issues again. Note if this the source of the 500 error the page will display but there will be no data at all. Just trying to see if the 500 error goes away. Make sure you get the edit correctly otherwise it will cause a 500 error and we will be chasing our tail.

**Comment by k6bpm** [comment]
It's a PHP version issue I'm afraid. I just installed PHP 7.4, changed to php7.4-fpm.sock in Nginx, and it is working now.

**Comment by balloonhotair** [comment]
Yea at least we know we are not chasing rabbits any more. I think the version Ian is working on releasing shortly is php 8.0 compliant. But I may be wrong. If not will make it work with 8.0.

**Comment by steepleian** [comment]
OK, I have just made a clean install of the main branch on my test server with PHP 8.0 and I had no problems. The only difference that I can see is that I use Apache2 as my server. I am wondering if there is a setting that is required with Nginx for PHP 8.0? I admit that I have never used Nginx so cannot speak with any authority.

**Comment by k6bpm** [comment]
Maybe there is another module I need to install. I use Nginx exclusively and recently updated to PHP 8. All my business sites are running it here: https://www.27labs.com but these are running on Ubuntu full blown servers. I'll play around with it and see if I can discover anything. I have both 7.4 and 8.0 installed now so I can switch back and forth. 

I really appreciate all your guys help. This looks great and I finally have a responsive weather station layout.

**Comment by steepleian** [comment]
The main branch was made PHP8 compatible on 8th of February this year. Just had a look at your link, you are obviously into some serious stuff, I am just an enthusiastic amateur, self-taught and gratefully relying heavily on Balloonhotair's expertise when I get into deep-water. I will keep the issue open for now to see if anything materialises with Nginx. All of the users I am in regular contact with are Apache based so it would be useful to get some feedback on alternative webserver applications.
Ian

**Comment by k6bpm** [comment]
You guys have done an incredible job with this. Nginx is lower overhead and IMHO faster. It is also very extensible and I generally add some nice bells and whistles like detecting countries and OS.

**Comment by steepleian** [comment]
Always happy to collaborate if you feel you can make a contribution, I for one are willing to learn more about Nginx. Apache is my comfort zone and maybe I need to get out of that from time to time.

**Comment by steepleian** [comment]
Resolved, PHP compatibility issue with Nginx

**Comment by steepleian** [comment]
Brian,

Just started looking at an all singing and dancing version of current conditions. When you first started to get the cloud coverage working with the default satellite image, did you notice what value you got. Was it Null, N/A, 0 or just a blank?

Thanks,
Ian

**Comment by k6bpm** [comment]
I don’t remember for sure, but I kind of recall it being 0.

— Brian - K6BPM

**Comment by k6bpm** [comment]
I finally got a 1 mph win gust so I know that works too,  and my current conditions just changed and it is right on the money. I can’t wait until we get some actual weather with rain and everything.

— Brian - K6BPM

**Comment by k6bpm** [comment]
I meant to also add something else that occurred to me earlier. One good way to encourage engagement with open source projects is to let users contribute elements of the program regardless of their skill level. One way you could do that would be to provide basically “skins for skins” capabilities. In other words, maybe do something like giving CSS colors names instead of hex values and pull the name=value from an external CSS file. Another thing would be to pull your icons from an optional user-defined path. That way talented and not-so-talented users could design and offer custom color palettes and icon sets. It lets users put their own “touch” on their websites.

One thing that WeeWX was always missing was opportunities for creativity. Honestly, WeeWX with Weather34 should be generating licensing revenue from WX station manufacturers. It is way better than the crap they include and already mobile ready. I don’t think any design moves towards establishing an engaged and contributing community would be wasted time.

— Brian - K6BPM
