### ISSUE TITLE
Current Conditions

### ISSUE THREAD

**Issue by k6bpm** [steepleian/weewx-Weather34#75]
My Current Conditions tile does not seem to be updating anything. The Nearby METAR station is working correctly and I thought "Current Conditions" would use these reports to update its values. Did I miss a setting somewhere?

**Comment by balloonhotair** [comment]
Ian would have the best answer for this, but most of the fields get their data from your weather station. So example rainfall is what your weather station is reporting, same for wind gust etc. Can you post a screen shot of your weather34 display?

**Comment by k6bpm** [comment]
The website is https://www.greatweather.com. It’s the upper right tile. 

I had to track down and change a bunch of unit settings to US but it is looking pretty good now!

**Comment by k6bpm** [comment]
Maybe the current conditions are updating, so I guess my question would be where the sky icon and cloud height comes from? They are definitely not correct. It’s foggy, not clear. The metar icon is showing mist which is about right.

**Comment by balloonhotair** [comment]
First my site is a US site and has been for years so you should not have any US unit issues. So please post what you had to change so we can understand why you had to make changes.
Second I think the cloud icon comes from the metar but Ian is the expert on that.
The cloud height is based on an internal calculation. Again Ian is the man for that.
Please post any changes you make so we can verify and correct any issues.

**Comment by steepleian** [comment]
Hi Brian,
Can you email directly please. It is probably easier to resolve things this
way then we can publish the solution in the issues log. ***@***.***
is the address that I use exclusively for this project.
Thanks
Ian

**Comment by steepleian** [comment]
That’s interesting, it commented out my email address. You will find a direct link to it on your website menu.

**Comment by steepleian** [comment]
Resolved. Sat24.com API does to cover California. Cloud height, reverted to Metar data as WeeWX and PHP calculations proving to inaccurate. Updates made in development branch only at this stage.

**Comment by steepleian** [comment]
Just looking at your website and noticed cloud height value missing.
Checked the Metar feed and it appears that some of the data has been
omitted for some reason?

**Comment by k6bpm** [comment]
That seems to happen when there are no clouds. Right now the celling is unlimited wit no clouds in sight.

— Brian - K6BPM

**Comment by k6bpm** [comment]
And, the early morning marine layer has just moved in. So probably when there is no cloud data a message could say “Unlimited” or “None”.


— Brian - K6BPM

**Comment by steepleian** [comment]
OK will put a check in for that.

**Comment by steepleian** [comment]
Hi Brian,

Can you try this version please. It has a check for clear skies and if true replaces the cloud height number with “No Cloud Base”

Cheers,
Ian

**Comment by k6bpm** [comment]
Hi Ian,

Sorry, no attachment on this one.

— Brian - K6BPM

**Comment by steepleian** [comment]
Whoops, sorry about that. In my defence is was 4am when I sent it!

Trying again.

**Comment by k6bpm** [comment]
Hmmm… nothing in this one either. Maybe you can try a new thread? I don’t know if my mail client might be at fault. I don’t thinks so, I get attachments all the time, but you never know.

— Brian - K6BPM

**Comment by steepleian** [comment]
trying a zip

**Comment by k6bpm** [comment]
Nope. You know, this is coming through GitHub. Could that have anything to do with it?

— Brian - K6BPM
