### ISSUE TITLE
Highcharts: Wrong reported date in minimum and maximum values

### ISSUE THREAD

**Issue by MauroSwiss88** [steepleian/weewx-Weather34#79]
Hi Ian
Hi Jerry
Hi Everyone

What I wanted to report today is not an actual malfunction, but something I noticed after months and months of observation.
I thought it was only happening to me, but it's also the case for all the sites viewed that use the same skin.

To explain briefly what I mean I enclose images of my graphics.

Taking yesterday's temperature range s an example the max observed was 15.7 C. (fig. 1) and going inside the daily charts I see the max observed temperature exactly during the day of the 14th November (fig. 2).

_(fig.1)_

![Schermata 2021-11-15 alle 14 23 43](https://user-images.githubusercontent.com/64233475/141791605-eefc99f0-90b7-4b81-9605-85aaa45b8064.png)

_(fig. 2)_

![Schermata 2021-11-15 alle 14 28 17](https://user-images.githubusercontent.com/64233475/141791661-9edb5a69-9bbf-45de-973c-27c5248418d1.png)

So far, nothing strange, but going back at least of one month and checking another interval, the reported dates (fig. 3) are always wrong and in advance of one day (fig. 4) between yearly almanac and daily chart. In this last example, I have deliberately taken a graph from another site to show that it happens everywhere. 

_(fig.3)_

![Schermata 2021-11-15 alle 14 38 32](https://user-images.githubusercontent.com/64233475/141792062-fd7fa53f-26d2-4423-874f-bf8e4f215a2d.png)

_(fig. 4)_

![Schermata 2021-11-15 alle 14 48 58](https://user-images.githubusercontent.com/64233475/141792960-86123bfb-d898-4fab-bce6-864c7f0266e8.png)

And to conclude, in all the graphs I looked at, the 31th October is missing, although there were intervals collected (fig. 5 and 6 from to different sites)

_(fig. 5)_

![Schermata 2021-11-15 alle 14 55 23](https://user-images.githubusercontent.com/64233475/141793990-45eef04d-4077-4597-8d3b-2eb6c3debf7b.png)

_(fig. 6)_
![Schermata 2021-11-15 alle 14 55 53](https://user-images.githubusercontent.com/64233475/141794078-368df44b-26cb-476e-b794-8345d29464e9.png)

I didn't want to bore you, but just point it out. Do you have any idea what it could be?

Mauro

**Comment by steepleian** [comment]
Mauro,

I am not sure what is going on here, I will see if I can pick this up with Jerry.

Thanks,
Ian

**Comment by MauroSwiss88** [comment]
Hi Ian,

Good! It was just to let you know about this. 

Greetings

Mauro

**Comment by balloonhotair** [comment]
If there is missing data then the charts will be off, it is a limitation of the current design and not something that can be fix easily.
Why the data on 31 is missing can be a number of reasons but the most likely one I have seen is missing timestamps at start of day, or bad timestamps. The data and timestamps are fed into highcharts as two arrays that must be in sync otherwise drift will occur.

**Comment by MauroSwiss88** [comment]
Hi Jerry

Thank you for your answer and explanation. What about the wrong date shown in the example?

**Comment by balloonhotair** [comment]
If a date is missed all dates get off my the number of dates missed. Not sure if that is what you are asking about.

**Comment by MauroSwiss88** [comment]
Just to be sure I've understand you: as soon as one date is missing, the dates get messed up because they are anyway put into sequence, right? 

To be also sure you understand me, just an example: 

I have the highest Temperature observed on the 1st August this year and it's correctly reported into the json_day daily chart. 

But if I open the whole Temperature Almanac to see the temperature interval (json files) above this highest value it's reported the 31th July and not the 1st August.

Hope you understand what I mean.
