### ISSUE TITLE
Posted by Invidia on WXforum

### ISSUE THREAD

**Issue by steepleian** [steepleian/weewx-Weather34#8]
I installed for the first time, get the following in syslog, thanks for the help:

Feb  8 03:20:45 raspberrypi weewx[2806] INFO weewx.manager: Added record 2021-02-08 03:20:00 CET (1612750800) to database 'weewx.sdb'
Feb  8 03:20:45 raspberrypi weewx[2806] INFO weewx.manager: Added record 2021-02-08 03:20:00 CET (1612750800) to daily summary in 'weewx.sdb'
Feb  8 03:20:48 raspberrypi weewx[2806] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 2.14 seconds
Feb  8 03:20:49 raspberrypi weewx[2806] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 1.26 seconds
Feb  8 03:20:49 raspberrypi weewx[2806] INFO weewx.reportengine: Copied 0 files to /home/weewx/public_html
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** Ignoring template /home/weewx/skins/Weather34/serverdata/archivedata.php.tmpl
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: **** Reason: cannot find 'format' while searching for 'format'
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: ****    File "/home/weewx/bin/weewx/cheetahgenerator.py", line 324, in generate
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: ****    File "_home_weewx_skins_Weather34_serverdata_archivedata_php_tmpl.py", line 2517, in respond
Feb  8 03:20:49 raspberrypi weewx[2806] ERROR weewx.cheetahgenerator: ****  NameMapper.NotFound: cannot find 'format' while searching for 'format'
Feb  8 03:20:49 raspberrypi weewx[2806] INFO weewx.cheetahgenerator: Generated 0 files for report Weather34Report in 0.06 seconds
Feb  8 03:20:49 raspberrypi weewx[2806] INFO weewx.reportengine: Copied 0 files to /home/weewx/public_html/weather34/
Feb  8 03:20:52 raspberrypi weewx[2806] INFO weewx.cheetahgenerator: Generated 7 files for report w34Highcharts in 2.55 seconds
Feb  8 03:20:52 raspberrypi weewx[2806] INFO weewx.reportengine: Copied 0 files to /home/weewx/public_html/weather34/w34highcharts

**Comment by steepleian** [comment]
Closing no further feedback

**Comment by dgunnell** [comment]
I see this bug also was introduced with your lightening check code added.  I went back to prior version and fixed the problem.

**Comment by invidia191** [comment]
Hello, I still have this problem. Any solution ?
