### ISSUE TITLE
Forecast & METAR Stopped 26 Oct

### ISSUE THREAD

**Issue by gary-hammer** [steepleian/weewx-Weather34#8]
W34-HC-IMJD-3.0.0
I noticed 3-4 days ago that my forecast and METAR have not updated since 26 OCT.
I'm attaching logs, but there is nothing related in them.
I also note that when choosing 'weekly' for any chart, I only get the current day chart. 
[Debug111320.txt](https://github.com/steepleian/weewx-Weather34/files/5540006/Debug111320.txt)
[gh-access.log](https://github.com/steepleian/weewx-Weather34/files/5540007/gh-access.log)

**Comment by steepleian** [comment]
Gary,

Do you have the weewx.conf section of your debug report?

**Comment by gary-hammer** [comment]
The debug out is attached.
[ghdebug.txt](https://github.com/steepleian/weewx-Weather34/files/5540761/ghdebug.txt)

**Comment by steepleian** [comment]
Gary,

You are running version 3.0.0 but your weewx.conf has is set up for the previous versions. Web services settings have been moved from the skin settings to weewx.conf

You effectively need to create a new weewx.conf. We have created a pre-install settings feature which makes this process easier for you. Check out the installation guide for the details.

Ian

**Comment by gary-hammer** [comment]
I did use the setup page, put the resulting file into the install
directory, then installed.

What if I fully remove, then install?

There have been a number of one-off changes made along the way.

**Comment by steepleian** [comment]
Gary,
Make sure you backup your customisations then a clean install would be very
good idea. I always do a clean install install myself once a new versions
has been finalised.
Ian

**Comment by gary-hammer** [comment]
Sounds good.
I'll do this over the weekend.

**Comment by gary-hammer** [comment]
So, how do I uninstall completely?

**Comment by steepleian** [comment]
My normal method is to rename my weather34 folder, weewx.conf and skin.conf files. I then run wee_config --reconfigure to create a new weewx.conf file with my default weewx setup. Restart weewx then start the weather34 pre-install and install processes.

**Comment by gary-hammer** [comment]
I believe I got it removed, though I'll use your method if I have to again.
I stopped weewx, edited weewx.conf and removed anything with Weather3 in it.
Erased all files in the weewx tree that were the date and time I installed this.
Deleted everything below /var/www/html/weewx and there were a couple of files still in weewx/public_html
I then followed the install guide and installed. Started weewx, went to my weather page and it was the new site with odd data.
I open settings and made my changes, saved it. Restarted weewx.

I have good data, but there are some issues with it.

First, The forecast seems to be taking US measurements as if they were metric and converting them to US measurements.
https://weather.ghammer.net to see exactly what I'm talking about, but tomorrow won't be a high of 140F and a low of 83F.

Second, the Cloud Cover 1% (1 okta) issue has returned. I thought this was taken care of by a program change, but looks like it didn't make it into the normal release. I can confirm that the two sat images are indeed downloaded to /tmp and have clouds in them.

Lastly, all charts do not have weekly display if I choose weekly. Yearly and monthly seem to work.

I'm attaching darksky.txt, wuforecast.txt, services.txt, and ghdebug.txt in a zip package in case you need.

**Comment by steepleian** [comment]
Gary,

Cloud cover. I was assured that the sat24.com was now functional in the
Americas. Looking at the images for your location, that does not appear to
be the case. Just remove that section from weewx.conf. The modified current
conditions did make it through to the release, it should kick in once you
have made the change.

Moving web services to weewx.conf from settings1.php caused the forecast
conversions to break. Apologies for that. I will get this resolved asap,
just need to consult on how to do that efficiently without a lot of code
disruption.

Ian

**Comment by gary-hammer** [comment]
Ian,
So, I'll just set enable=False under [Weather34CloudCover]
I'm attaching the sat files that are created in /tmp
They look ok, but then, I do not know what they should be.

I'll await the conversion fix. All else seems to be accurate.
[sat-pics.zip](https://github.com/steepleian/weewx-Weather34/files/5542690/sat-pics.zip)

**Comment by steepleian** [comment]
Gary,

OK the DarSky forecast is fixed. You need to update easyW34skinSetup.php
and outlookds.php, open the settings page and set the units for DarkSky
forecast in the units section.

Weather Underground forecast is going to take much longer. Changes in the
API mean that the whole thing needs to be re-written which is going to take
a lot longer. Will let you know when complete.
Ian

**Comment by gary-hammer** [comment]
Ian,

All is displaying properly after following your instruction.
The displayed 3 day and the pop out 8 day forecasts have the correct values as do the hourly.

Thanks for the prompt fix.
Gary

**Comment by steepleian** [comment]
Great. I have now fixed Weather Underground. You need to update
forecast3wu.php
<https://github.com/steepleian/weewx-Weather34/blob/main/www/forecast3wu.php>
and forecast3wularge.php
<https://github.com/steepleian/weewx-Weather34/blob/main/www/forecast3wularge.php>
then re-run easyW34skinSetup.php to select you WU forecast units.

Ian

**Comment by gary-hammer** [comment]
Ian,

I thought I had replied, sorry.

I replaced the files and set the forecast units.
The 3 day, daily, and hourly forecasts all display the desired units.

Gary

**Comment by steepleian** [comment]
Thanks Gary. Glad it is all working for you. I am looking at a more elegant
solution so that you don't have to enter the unit code in the post settings
page as well. and will update the repo when this is done.
Ian
