### ISSUE TITLE
Not Seeing Air Quality

### ISSUE THREAD

**Issue by dgunnell** [steepleian/weewx-Weather34#80]
airqualitydata.php is not being generated in serverdata dont see any settings in weewx.conf or Weather34/skin.conf.  Its showing on the website as Offline as a result.  How is this configured.  I have the api.waqi.info settings configured with my access token and I have confirmed the url works and returns aqi data.  Running Weewx 4.5.1 and latest version of Weather34 all under Python 3.

**Comment by steepleian** [comment]
Hi, first question, when you installed did you follow this section in the installation instructions: -

"Go to https://steepleian.github.io/weewx-Weather34 to complete the pre-install web services settings which which generates 'services.txt' in your default Download folder. IMPORTANT the unit codes that you select for the Weather Underground and DarkSky forecast APIs must be identical to those that you select in the post-install settings page. Failure to do so will possibly produce some bizzare data."

Notwithstanding, there have been several changes since this current release. I will provide you with a walk through of how to remedy the problem later today.

Regards,
Ian

**Comment by dgunnell** [comment]
Yes I followed those procedures to generate services.txt and ran the installer.  I installed weewx with the setup.py method and selected that as the install method used when installing weather34.  Weather34 seems to run fine and produce forecasts, etc. other than the aqi stuff.  Here are the Weather34WebServices settings with my token/api keys removed:

[Weather34WebServices]
    aq_url = https://api.waqi.info/feed/geo:34.7883;-84.2827/?token=##############################
    aq_interval = 3600
    ds_url = https://api.forecast.io/forecast/##############################/34.7883,-84.2827?lang=en&units=us
    ds_interval = 3600
    wu_url = https://api.weather.com/v3/wx/forecast/daily/5day?geocode=34.7883,-84.2827&language=en&format=json&units=e&apiKey=#############################
    wu_interval = 3600
    eq_url = https://www.emsc-csem.org/service/rss/rss.php?typ=emsc
    eq_interval = 3600
    eq_xml_data = False
    ki_url = https://services.swpc.noaa.gov/products/noaa-planetary-k-index-forecast.json
    ki_interval = 21600
    me_url = https://api.checkwx.com/metar/KDZJ/decoded
    me_header = X-API-Key:b01ffe6a895741348108b13118
    me_interval = 3600
    pu_url = https://www.purpleair.com/json?show=
    pu_interval = 3600
    enable_uk = undefined
    uk_url = https://metoffice.gov.uk/public/data/PWSCache/WarningsRSS/Region/
    uk_interval = 3600
    uk_xml_data = undefined
    services = aq.wu.eq.ki.me
and here is link to site:
http://www.gricewoodsweather.com/weewx/weather34/index.php

**Comment by steepleian** [comment]
I have just been going through the waqi documentation and there are some changes to the API. I am doing a rewrite now. Just one thing, do you use the full size module with the smily face or the smaller top row module to display? Whichever it is I will concentrate on that one first.

**Comment by dgunnell** [comment]
Using the default layout so that would be the two small ones top center and the "World (US EPA)  larger one in bottom right.  No preference on which one first.

**Comment by steepleian** [comment]
Ok can you email me you latitude and longitude so that I can check that things are working for your location. (steepleian@btinternet.com)

**Comment by steepleian** [comment]
OK, the large module is now working, replace airqualitymodule.php with the attached.
[airqualitymodule.php.zip](https://github.com/steepleian/weewx-Weather34/files/7546456/airqualitymodule.php.zip)

**Comment by dgunnell** [comment]
Main one below bottom right is now working and seems to be the right number
when I check outside of weather34.  You can see here:


<goog_1618023251>
http://www.gricewoodsweather.com/weewx/weather34

Dave

**Comment by steepleian** [comment]
Both large and small modules reworked for Location AQI using waqi API

The attached zip file contains all the files that need to replaced in your weather34 folder. When installed, go to the settings menu to sellect top_aqi_waqi.php for top row small module and/or airqualitymodule.php for the large AQI module.

[aqiModuleUpdates.zip](https://github.com/steepleian/weewx-Weather34/files/7547035/aqiModuleUpdates.zip)

**Comment by dgunnell** [comment]
Installed updates and ran setup and reconfigured all seems to be working fine now.

Thanks,

Dave

**Comment by steepleian** [comment]
Ok thank you I will close the issue now.
