### ISSUE TITLE
Weather34 not honouring RSYNC Port option?

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#81]
Hi all,

I just changed web hosts and they use port 27 for their ssh/rsync connections. The regular weewx rsync updates appear to be working, and it works fine from the command prompt but the fast weather34 updates are failing with this error in the weewx debug log (I removed the IP addresses)

"Jan  1 16:58:03 weewx-pi weewx[17961] DEBUG weeutil.rsyncupload: rsyncupload: cmd: [['rsync', '--archive', '--stats', '-e ssh', '/tmp/weather34/serverdata/', 'us...@changed.ip.for.privacy:/home/user/public_html/weather34/serverdata']]
Jan  1 16:58:03 weewx-pi weewx[17961] ERROR weeutil.rsyncupload: [['rsync', '--archive', '--stats', '-e ssh', '/tmp/weather34/serverdata/', 'us...@changed.ip.for.privacy/home/user/public_html/weather34/serverdata']] reported errors: ssh: connect to host changed.ip.for.privacy port 22: Connection refused. rsync: connection unexpectedly closed (0 bytes received so far) [sender]. rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]

Cheers
Chris

**Comment by balloonhotair** [comment]
Untested change submitted to dev branch to read the weewx config Rsync port config entry.

**Comment by chrisale** [comment]
Wow you're fast. I've replaced weather.py in /bin/user with your updated file but still get the same error unfortunately.

**Comment by balloonhotair** [comment]
What does you config entries in the Rsync look like?

**Comment by chrisale** [comment]
As below. I've only changed the username and added the port

 [[RSYNC]]
        # rsync'ing to a webserver is treated as just another report
        skin = Rsync

        # If you wish to use rsync, you must configure passwordless ssh using
        # public/private key authentication from the user account that weewx
        # runs to the user account on the remote machine where the files
        # will be copied.
        #
        # If you wish to use rsync, set "enable" to "true", then
        # fill out server, user, and path.
        # The server should appear in your .ssh/config file.
        # The user is the username used in the identity file.
        # The path is the destination directory, such as /var/www/html/weather.
        # Be sure that the user has write permissions on the destination!
        enable = true
        server = alberniweather.ca
        path = /home/user/public_html
        user = user
        port = 27

        # To upload files from something other than what HTML_ROOT is set
        # to above, specify a different HTML_ROOT here.
        #HTML_ROOT = /var/www/html/weewx

        # Rsync can be configured to remove files from the remote server if
        # they don't exist under HTML_ROOT locally. USE WITH CAUTION: if you
        # make a mistake in the remote path, you could could unintentionally
        # cause unrelated files to be deleted. Set to 1 to enable remote file
        # deletion, zero to allow files to accumulate remotely.
        delete = 0

**Comment by balloonhotair** [comment]
Do not see anything, so there is a debug version of weather34.py to print the port being sent to weewx rsync. Need to have debug set to 1 to see output.

**Comment by chrisale** [comment]
I think it might have something to do with the command that is being issued.

The debug shows port 27 being used.  But when I manually recreate the command on the command line like this:
sudo rsync --archive --stats -e ssh -p 27 /var/www/html/weewx/ user@alberniweather.ca:/home/user/public_html

I get the same error. It ignores the port number and tries on 22

**Comment by chrisale** [comment]
Which would make it a weewx problem?

**Comment by chrisale** [comment]
The command is missing the quotes. It needs to be:
sudo rsync --archive --stats -e 'ssh -p 27' /var/www/html/weewx/ user@alberniweather.ca:/home/user/public_html

**Comment by balloonhotair** [comment]
Yea if the debug shows 27 then it is a weewx problem since the template is calling the weewx rsync functionality.

**Comment by chrisale** [comment]
OK. I have a thread going there too so I'll add it in there. Thank you for your quick help!

**Comment by chrisale** [comment]
It just occurred to me it can't all be on weewx as the standard skin has been updating OK through all of this. There is definitely something going on with weather34. Perhaps there is some sort of "hand off" to the weewx function that is not being handled correctly?

**Comment by chrisale** [comment]
A comment/suggestion from a weewx developer:
"I just browsed through the WeeWX Weather 34 code and saw calls to the WeeWX rsync upload code with the port forced to None. That will cause the rsync uploader (used by the Weather 34 code) to always use port 22. Setting the port number under [StdReport] [[RSYNC]] only affects rsync reports runs under the WeeWX StdReport service (ie it will have no impact on the Weather 34 code).

So yes in all likelihood your issue is with the Weather 34 code and not WeeWX."

**Comment by balloonhotair** [comment]
Wrong version of code was looked at. The development version has the port sent to what the config entry is. Hope you are testing with the development version.

**Comment by balloonhotair** [comment]
So if you look in the weewx rsync code there are no single quotes around the ssh port part of the command.  It is line 67 in rsyncupload.py in the weewxutil directory. (My version of the code) I would add the missing quotes and redo your test.

**Comment by chrisale** [comment]
Tom Keffer has attempted a fix but it doesn't appear to have fixed the issue. Still defaulting to port 22.
Here's the thread on the weewx-user list:
https://groups.google.com/g/weewx-user/c/BMVd3Y-_pwk

Here's the bug fix today:
https://github.com/weewx/weewx/blob/68bf6c40332d37b9999db7b2e81803edb4141fb9/bin/weeutil/rsyncupload.py

I'm going to go back and double check I'm using both the updated weather34.py and rsyncupload.py

**Comment by chrisale** [comment]
All is well! Looks like I was applying the change in an old install file. Not used to the file structure on my Pi yet evidently.  Both patches are now applied and updates are continuing normally!

Thank you for your quick work! Attentive and precise as always!

**Comment by steepleian** [comment]
Thanks Chris, now closing as an issue

**Comment by balloonhotair** [comment]
Can this issue be closed now?

**Comment by steepleian** [comment]
Closed
