### ISSUE TITLE
weewx can't restart after weather34 install - missing weewxserverinfo.txt

### ISSUE THREAD

**Issue by chrisale** [steepleian/weewx-Weather34#9]
Hi there,

I'm giving the updated skin a shot with python3 and weewx4.1.1.

After install, weewx complains that weewxserverinfo.txt is missing, here is the message from the log:

weewx[68267] DEBUG weewx.engine: Loading service user.weather34.Weather34RealTime
weewx[68267] INFO user.weather34: service version is 0.0.5
weewx[68267] INFO user.weather34: output goes to /Users/Shared/weewx/public_html/weather34/w34realtime.txt
weewx[68267] INFO user.weather34: 'None' values will be displayed as NULL
weewx[68267] CRITICAL __main__: Caught unrecoverable exception:
weewx[68267] CRITICAL __main__:     ****  Command '['hostname', '-s', '-I']' returned non-zero exit status 1.
weewx[68267] CRITICAL __main__:     ****  Traceback (most recent call last):
weewx[68267] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/weewxd", line 148, in main
weewx[68267] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
weewx[68267] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/weewx/engine.py", line 75, in __init__
weewx[68267] CRITICAL __main__:     ****      self.loadServices(config_dict)
weewx[68267] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/weewx/engine.py", line 138, in loadServices
weewx[68267] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self,config_dict)
weewx[68267] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/user/weather34.py", line 679, in __init__
weewx[68267] CRITICAL __main__:     ****      weewxserver_ip = subprocess.check_output(['hostname', '-s', '-I']).split(b" ")[0].decode()
weewx[68267] CRITICAL __main__:     ****    File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
weewx[68267] CRITICAL __main__:     ****      **kwargs).stdout
weewx[68267] CRITICAL __main__:     ****    File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
weewx[68267] CRITICAL __main__:     ****      output=stdout, stderr=stderr)
weewx[68267] CRITICAL __main__:     ****  subprocess.CalledProcessError: Command '['hostname', '-s', '-I']' returned non-zero exit status 1.
weewx[68267] CRITICAL __main__:     ****  Exiting.

**Comment by balloonhotair** [comment]
Hi,
Change submitted to dev to try and find the ip address if previous attempts fail. Protection code will now prevent and the critical error. Also if this approach fails a message is logged in syslog that the config field weewxserver_address field in W34Reattime section needs to be used. Here is a untested version for Mac if you want to try it. Just rename the file without the txt.
[weather34.py.txt](https://github.com/steepleian/weewx-Weather34/files/5120432/weather34.py.txt)

**Comment by chrisale** [comment]
Thanks!

I had my remote server's DNS name in the weewxserver_address field in weewx.conf as "alberniweather.ca".

As an aside, I haven't been able to find what the "weewx_file_transfer" option in weewx.conf should have in it? Suggestions?

**Comment by balloonhotair** [comment]
Hi,
The field is supposed to be an ip address but sometimes DNS entries may work, it really depends on the os to return an ip address or when doing a socket/rsync connection the os does the translation.
The transfer field is an override for how files can be transfer. Usually it is empty but if you always want to do an unsecure socket connection to transfer data to the webserver then socket be the entry. If you want secure then rsync would be the entry. Note you have to have ssh keys setup correctly for this to work, which sometimes is hard to get correct.

**Comment by chrisale** [comment]
That's great, I would use rsync as I already have that up and running. Is that the default, or should I specify it? I will change my DNS address to an IP just to be sure though DNS would probably be preferable in the long run. Thanks for your help!

**Comment by balloonhotair** [comment]
Hi,
Rsync is the default if the webserver_address is filled in and it is different than the ip address of the weewx machine.
The DNS entry should work if all the pieces are in place since the code does a gethostbyname if the webserver field is not numeric.
So all you need to set up is the webserver_address field in the W34Realtime section and leave the transfer field empty. The weewxserver_address can be left empty also. It is only needed if the code cannot figure out the ip address of the weewx machine and if that happens a log entry will point that out.

**Comment by chrisale** [comment]
With the new file you provided I now get this error after re-installing Weather34 and attempting to restart weewx:

weewx[5026] DEBUG weewx.engine: Loading service user.weather34.Weather34RealTime
weewx[5026] INFO user.weather34: service version is 0.0.5
weewx[5026] INFO user.weather34: output goes to /Users/Shared/weewx/public_html/weather34/w34realtime.txt
weewx[5026] INFO user.weather34: 'None' values will be displayed as NULL
weewx[5026] INFO user.weather34: units will be displayed as METRICWX
weewx[5026] INFO user.weather34: zambretti forecast: False
weewx[5026] ERROR user.weather34: Failed to open config file or create dictionary: /Users/Shared/weewx/public_html/weather34/settings1.php, Error: [Errno 2] No such file or directory: '/Users/Shared/weewx/public_html/weather34/settings1.php'
weewx[5026] ERROR user.weather34: Failed to open config file or create dictionary: /Users/Shared/weewx/public_html/weather34/settings1.php, Error: [Errno 2] No such file or directory: '/Users/Shared/weewx/public_html/weather34/settings1.php'
weewx[5026] INFO user.weather34: CloudCover: not installed
weewx[5026] DEBUG user.weather34: CloudCover: due to error No Dictionary
weewx[5026] CRITICAL __main__: Caught OSError: [Errno 2] No such file or directory: 'public_html/weewxserverinfo.txt'
weewx[5026] CRITICAL __main__:     ****  Traceback (most recent call last):
weewx[5026] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/weewxd", line 148, in main
weewx[5026] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
weewx[5026] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/weewx/engine.py", line 75, in __init__
weewx[5026] CRITICAL __main__:     ****      self.loadServices(config_dict)
weewx[5026] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/weewx/engine.py", line 138, in loadServices
weewx[5026] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self,config_dict)
weewx[5026] CRITICAL __main__:     ****    File "/Users/Shared/weewx/bin/user/weather34.py", line 756, in __init__
weewx[5026] CRITICAL __main__:     ****      with open(d.get('weewxserverinfofilename', config_dict['StdReport'].get('HTML_ROOT', '/var/www/html/weewx') + '/weewxserverinfo.txt'), 'w') as f:
weewx[5026] CRITICAL __main__:     ****  FileNotFoundError: [Errno 2] No such file or directory: 'public_html/weewxserverinfo.txt'
weewx[5026] CRITICAL __main__:     ****  Waiting 10 seconds then retrying...

**Comment by balloonhotair** [comment]
Hi,
First make sure this entry in weewx.conf is correct for Mac
[Weather34WebServices]
    filename = **/var/www/html/weewx/w34weather/settings1.php**

**Comment by balloonhotair** [comment]
Hi,
What happens if the config entries are not correct the code defaults to the most common which is /var/www/html...

**Comment by balloonhotair** [comment]
Hi,
Also this file needs to be present.
/Users/Shared/weewx/public_html/weather34/settings1.php.
Did you create it by running the w34easysetup before starting weewx.
It is sort of a chicken and the egg issue since weather34.py needs to start with weewx, but the settings file needs to be there.
The install put a settings1.default.php file but now it would be better just to put a settings1.php so weather34.py can startup. Note to Ian to look into this.

**Comment by balloonhotair** [comment]
Hi,
FYI Testing on Mac is very hard at the moment since both Ian and I had our Macs quit working recently. :-(

**Comment by balloonhotair** [comment]
Hi,
Here is a version of weather34.py that has protection if the write to weewxserverinfo.txt fails. Note this will prevent the critical error but without the file being created Highcharts will not work, but at least weewx will not exit.
[weather34.py.txt](https://github.com/steepleian/weewx-Weather34/files/5121542/weather34.py.txt)

**Comment by chrisale** [comment]
I normally do not have a web server running on my weewx box. So if weather34 requires all the settings1 files and whatnot to be generated *before* the remote side is generated and accessible, then that's a definite chicken and egg problem! :)

Perhaps an option could be set in weewx.conf telling weather34 it is in a "setup remote" mode, that allows weewx to start and has w34 run the rsync process to transfer the needed files to the remote side. Then the web page is accessible, and the w34easysetup can occur?

Then the user can copy any critical generated settings files back to the weewx server side, turn off the 'setup remote' flag, and proceed normally.

I am sure anyone with this kind of remote setup would not be averse to the added couple of steps.

**Comment by chrisale** [comment]
What I'm going to see if I can basically force that to happen by manually copying the new weather34 directory up to the remote side and accessing the easy setup page there.  I'll let you know.

**Comment by chrisale** [comment]
It would also be adantageous if the rsync process in w34 could specific a username and used a hostname.

I'm currently using rsync and have a key setup for (example) chris@myweather.ca

w34 is trying to connect with (example) root@122.22.22.22

**Comment by balloonhotair** [comment]
Hi,
There is protection code in weather34.py so that it should not stop weewx from starting if the settings1.php file is not found but highcharts will not function. So right now it expects to find a local copy of settings1.php. This may have to be re-thought and move the info that weather34.py needs at startup from settings1.py into weewx.conf. This does removes the dependency but may require same info to be in two locations. 

yes weather34.py rsync is using the weewx built-in rsync so that rsync runs as the user of the process which has advantages of additional security since a user cannot put in any username. Allowing a user name may open a security hole that is not expected so this would require careful thinking.

**Comment by chrisale** [comment]
That's a good point.

**Comment by chrisale** [comment]
Have setup the root based rsync key. It is connecting now but it is expecting to put w34RealTime.txt into the same path as is specified in weewx.conf for the local machine. That path does not exist on the remote side so we need a variable in weewx.conf to specify that.

webserver_filename = ""

Could be a good option 

weewx[9385] INFO weewx.restx: Wunderground-RF: Published record 2020-08-27 14:26:14 PDT (1598563574)
weewx[9385] ERROR weeutil.rsyncupload: [['rsync', '--archive', '--stats', '-e ssh', '/Users/Shared/weewx/public_html/weather34/w34realtime.txt', '199.204.214.53:/Users/Shared/weewx/public_html/weather34/w34realtime.txt']] reported errors: rsync: connection unexpectedly closed (8 bytes received so far) [sender]. rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [sender=2.6.9]

**Comment by balloonhotair** [comment]
Hi,
The version of weather34.py I am working on allows the user to choose the location of the rsync dest file. I am moving all the web services config entries and cloud cover entries into weewx.conf so there will be no dependency on settings1.php by weather34.py. I am doing the testing now.

**Comment by chrisale** [comment]
Thanks for that! Also, I realized that the weewx.conf file, in its RSYNC section, allows you to specify a user to use to connect RSYNC.

So weewx is already exposing that potential security hole. However, there is also perhaps an opportunity for w34 to piggy back on those variables? Then users could set it just once?

Thanks for all your work!

[[RSYNC]]
    # rsync'ing to a webserver is treated as just another report
    skin = Rsync
    
    # Rsync can be configured to remove files from the remote server if
    # they don't exist under HTML_ROOT locally. USE WITH CAUTION: if you
    # make a mistake in the remote path, you could could unintentionally
    # cause unrelated files to be deleted. Set to 1 to enable remote file
    # deletion, zero to allow files to accumulate remotely.
    delete = 0
    
    # If you wish to use rsync, you must configure passwordless ssh using
    # public/private key authentication from the user account that weewx
    # runs as to the user account on the remote machine where the files
    # will be copied.
    #
    # The following three lines determine where files will be sent.
    server = alberniweather.ca
    path = /var/www/vhosts/alberniweather.ca/img
    user = root

**Comment by balloonhotair** [comment]
Hi,
Just to give a status on this. I have submitted changes to development that now moves all the config entries needed by weather34.py from settings1.php to weewx.conf. So now there is no longer a dependency between the two files. Also when using rsync the "user" config entry in weex.conf is used and if it is not present then the user of the weewx process is used. Also all the files used by the webserver (archivedata.php, airquality.php, w34realtime.txt,weewxserverinfo, /json, /json_day are now rsynced to remote webserver(s). Once testing is complete Ian will move the changes into the master branch.

**Comment by chrisale** [comment]
That's fantastic. Thank you again for all of your work!
