### ISSUE TITLE
Clean install, several 'issues'

### ISSUE THREAD

**Issue by devonian** [steepleian/weewx-Weather34#97]
I just made a clean install of W34 on my existing weewx and have no display for:
Wind, Forecast and Current Conditions.
Weewx is running fine and setting debug to 1 reports no issues?
Look here for weewx
www.nthead.co.uk/weewx
and for W34
www.nthead.co.uk/weewx/weather34

Running a davis VP2 with FARS and UV/solar

Something I have done? (I know just enough to be dangerous!!).
Attached is a grab of a w34reatime.txt

regds,
Nigel

[w34realtime.txt](https://github.com/steepleian/weewx-Weather34/files/8193556/w34realtime.txt)

**Comment by steepleian** [comment]
Hello Nick,
The missing alert and forecasts are caused because you are not generating the correct data. When did you download and did you generate a services.txt file. Did you sign up to AerisWeather? I can give you a fuller response this evening in the meantime can you email me directly at ***@***.*** with your weewx.conf file redacting any sensitive info with a bit of place holder text.
Thanks
Ian

**Comment by devonian** [comment]
Hi Ian,

I've replied to your gmail address - let me know if there's any problem or if you require more info....

Regds,

Nigel

**Comment by steepleian** [comment]
Hi Nigel,
It’s not through yet. I suspect you may have to zip it to get through the email security.
Ian

**Comment by devonian** [comment]
Hi Ian,

Sent again with attachment as txt file.

I also sent you a seperate email before, did you get any of my emails to your gmail account?
If not, I will send via a gmail account I have as well.

Nigel.

**Comment by devonian** [comment]
Ian,

I am sending to steepleian at gmail dot com but all messages are getting returned as undeliverable?

What is the correct address - github is masking your correct address with stars **** 

Nigel

**Comment by steepleian** [comment]
Can you send to ***@***.*** please. Thanks

**Comment by devonian** [comment]
Hi Ian,
Sorry, no worky!
Github is masking emails with stars.

You could send to me - devonian21<at>gmail<dot>com and we can continue from there as I will hopefully get your real email address.

This is what I receive via github email...

Can you send to [***@***.***](mailto:***@***.***) please. Thanks

**Comment by devonian** [comment]
Gee, how hard can it be with github!!
How about this...
devonian21 hat gmail dit com (hope you can work it out!).

Nigel

**Comment by stogs** [comment]
i find i am having a similar issue, no forecast. I have signed up for AerisWeather.  Looking at the code in forecast3aw.php.  It is looking for a file jsondata/ad.txt.   I don't have that file in that directory
<img width="493" alt="Screen Shot 2022-03-08 at 9 39 37 AM" src="https://user-images.githubusercontent.com/42517518/157271968-848e7a84-6acf-4ea6-b91e-6cb5b8c39f63.png">
.

**Comment by steepleian** [comment]
Ok I have fixed the forecast. It looks like a merge from the development branch to the main branch had failed. I am very sorry that happened. Can you try again please.
Ian

**Comment by stogs** [comment]
That resolved my issue.  Thank you for the quick response and fix.

**Comment by steepleian** [comment]
OK thats good, I can tick that one off the list.

**Comment by Rayvenhaus** [comment]
@devonian Have you updated to the latest code release, v4.2.5?  I also had the same issue as you and that fixed it for me and others.  Please respond as we'd like to get this issue closed if possible.

**Comment by steepleian** [comment]
Closing, the issues are resolved by version 4.2.5
Thanks to Devonian and Stogs for raising the issues and allowing us to fix them

**Comment by Rayvenhaus** [comment]
Closed as per [steepleian](https://github.com/steepleian)
